### ISSUE TITLE
Azure Functions edition of Azure Mobile Apps

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps#130]
We would like to be able to run Azure Mobile Apps table controllers inside the Azure Functions runtime, complete with authentication.

**Comment by adrianhall** [comment]
Can't do this without a full rewrite of server,

**Comment by velocitysystems** [comment]
@adrianhall Just curious if this is on the roadmap? Thanks.

**Comment by adrianhall** [comment]
No, it isn't.

**Comment by ForkBug** [comment]
Well, several months ago Azure Functions team added asp.net core integration.
Is it feasible now to run server-side code on Azure Functions? @adrianhall
