### ISSUE TITLE
Quickstart download does not work correctly in Safari on OS X

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-mobile-apps#15]
If you hit the download link for the quickstart in Safari on OS X you will either get
a) nothing
b) a web page that appears to be a string rendering of the bytes in the zip

Need to figure out what is going on here. Temporary workaround in the meantime is to use Chrome on OS X.

**Comment by thyeggman** [comment]
Pending deployment - waiting on vendor OGFs
