### ISSUE TITLE
Sync: Expose pending operations

### ISSUE THREAD

**Issue by phvannor** [Azure/azure-mobile-apps#2]
see: https://github.com/Azure/azure-mobile-services/issues/696

"Hi,

is it possible to get the local pending operations in mobile service SQLite which are going to push to azure.
if yes, how can I get the pending list of items from mobile service sync context , it is providing only number of pending operations, not actual items.

Thanks. 
Shib"

**Comment by phvannor** [comment]
With MobileApps CamelCaseText is false by default, meaning enums should stay cased as they are expected Client/Server by default.

**Comment by icsd** [comment]
So what is the answer in this question? 
"is it possible to get the local pending operations in mobile service SQLite which are going to push to azure."

Thank you

**Comment by lindydonna** [comment]
Yes, you use the PendingOperations property on the SyncContext. Here's a sample for the managed client SDK, and the other SDKs have a similar property.

**Comment by kwstoikonomou** [comment]
aaaand the sample is? Disappeared i guess?

**Comment by lindydonna** [comment]
I've updated the comment with the link.

**Comment by icsd** [comment]
This sample provides only the number of the pending operations. As the initial topic of the issue says, we want to get the actual list with the Pending Operations, not the size of it! How is it possible?

Thank you

**Comment by lindydonna** [comment]
I misread the original issue--it looks like it was closed by accident. You're right that we currently expose only the number of pending operations.

**Comment by Epican** [comment]
What does it mean when pending ops returns a -1?  I am seeing this in release versions of my app.

**Comment by supreettare** [comment]
any updates on this? I guess we still get the number of pending operations & the details are still not exposed?

**Comment by InquisitorJax** [comment]
yeah - would also be interested in this to give user an indication if his changes on a record up sync'ed yet (unless there's another better way to relay that information?)

**Comment by elamalani** [comment]
Hi everyone, please have a look at the Readme section for the future of [Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps#future-of-azure-mobile-apps). Closing this issue for now. Thanks!
