### ISSUE TITLE
Remove option of 'storage' account in Add Data Connection blade, or make it very clear that only a SQL Database connection is OK

### ISSUE THREAD

**Issue by ghost** [Azure/azure-mobile-apps#21]
I'd like to suggest an improvement to the 'Add Data Connection' blade -- remove the option of a 'Storage' account, or alternatively, make it very clear (before the Data Connection blade shows up) that only a SQL Database account is OK for mobile apps.

**Background:**

When I create a mobile app for the first time, I can create a data connection. 

To do this, I go to the "Add Data Connection" screen. 

On this screen, once I hit "+", I can create either a SQL Database connection or a Storage connection.

I was puzzled that I could create a Storage connection. I didn't see how that could work. Still, since it was an option, I went ahead and created it.

Once I created it, I was disappointed to find out I couldn't actually use it...since the mobile app expected a SQL Server connection. But I expected it to work since it was an offered as an option.

Attached are a couple of screenshots that illustrate this. The first screenshot shows the storage connection I've created. The second screenshot shows what happens when I try to use this connection with my mobile app.

<img width="546" alt="db-step1" src="https://cloud.githubusercontent.com/assets/1638063/13436717/76813f62-df95-11e5-9821-daadeff7b202.png">

<img width="573" alt="db-step2" src="https://cloud.githubusercontent.com/assets/1638063/13436727/7b33757a-df95-11e5-9c0d-c29fcfad3b0c.png">

**Comment by elamalani** [comment]
Hi there, please have a look at the Readme section for the future of [Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps#future-of-azure-mobile-apps). Closing this issue for now. Thanks!
