### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by ctolkien** [Azure/azure-mobile-apps#212]
The documentation links to:
https://docs.microsoft.com/en-us/previous-versions/azure/app-service-mobile/app-service-mobile-value-prop

Which has a banner stating:
>This content has been retired and may not be updated in the future. The product, service, or technology mentioned in this content is no longer supported.

**Comment by JasonHaley** [comment]
It looks like 26 days ago the readme.md was updated with some wording about .net core ... it would be nice to know more detail or if any help is needed to get it there (I'd be willing to donate some time to it - but don't want to start a port if it really is being worked on)

**Comment by adrianhall** [comment]
It's not dead.  We're just working on an ASP.NET Core update (which you can see in the checked in code, but it hasn't been released yet).
