### ISSUE TITLE
Error when I use the Quick Start blade to create the 'TodoItem' table

### ISSUE THREAD

**Issue by krisragh** [Azure/azure-mobile-apps#22]
Hi, I get an error when I use the Quick Start blade to create the 'TodoItem' table...even though the table actually does get created. The client app also works fine.

So, the issue is that the portal reports an error when there does not seem to be one. 

Here is a screenshot of the error that popped up.

<img width="1052" alt="screen shot 2016-03-01 at 10 06 27 am" src="https://cloud.githubusercontent.com/assets/1638063/13439262/86581288-dfa1-11e5-9a0c-22e619ba0ed7.png">

**Background**:

This is for a Mobile App I just created. Before clicking on 'Create TodoItem Table', I set up a SQL Server data connection for this Mobile App. I also pre-emptively enabled Easy Tables.

It did NOT already have a TodoItem table. It has one now. 

When I go to audit logs, I see no errors, at either the top level or digging into any of the lower levels of logging.

I'm not sure what's going on. I wanted to make sure this isn't hiding a more serious bug, so I'm alerting you.

**Comment by jwallra** [comment]
Based on recent investigation, I don't think this is a bug, it seems to be just a transient error.  If you can still reproduce this, please reopen the issue and provide repro steps.
