### ISSUE TITLE
Support Geospatial Data Type

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps#23]
From UserVoice: https://windowsazure.uservoice.com/admin/forums/216254-mobile-apps/suggestions/3317361-add-support-for-geo-spatial-types-and-queries

Belief (to be verified): Geography Type is available in the ASP.NET Backend.  It is not available in the Node.js backend

Specific questions on design
1) Does the OData v3 specification support geography data types?
2) Are there any API changes that are required to support geospatial in offline sync mode?

What output is required; aside from the client updates?  Documentation is obvious.  Do we need client samples?  What should the client samples do (minimally)?

**Comment by adrianhall** [comment]
From Joel / UserVoice:

Many mobile apps have location based features. While there is a workaround to support storing and querying Geography types using server side scripts, it would be much more powerful to have Geography supported natively in Mobile Services for storage and querying (example: query all nearby users). Mobile Services should expose the Geography features of SQL Azure.

**Comment by adrianhall** [comment]
From Jay / UserVoice:

Can not seem to apply a spatial index to geography data type column in SQL database (is this only a restriction to the free 20MB?)

**Comment by adrianhall** [comment]
From Miranda / UserVoice:

Nick Harris, one of the developer evangelists on the Mobile Services team has a geolocation sample Windows Store app available for download here: http://code.msdn.microsoft.com/windowsazure/Geolocation-sample-end-to-5d9ee245

Chris Risner, another developer evangelist on the Mobile Services team has two great iOS posts: 
-Displaying information on maps: http://chrisrisner.com/31-Days-of-iOS--Day-20%E2%80%93Displaying-Information-on-Maps 
-Showing the user's location on maps: http://chrisrisner.com/31-Days-of-iOS--Day-19%E2%80%93Showing-the-User%27s-Location-with-Maps

I know these aren't the desired level of support, but I hope these are useful in the interim nonetheless.

**Comment by adrianhall** [comment]
Reference for Geospatial data support in OData: (Blog)  http://www.odata.org/blog/geospatial-data-support-in-odata/

**Comment by tofutim** [comment]
Any update on this? Can I use spatial index yet?

**Comment by adrianhall** [comment]
You cannot use geospatial on the .NET backend yet.  There is a wierd confluence of library dependencies that is preventing it.  I'm also not expecting the .NET backend to support anything more than what it supports today for a long time to come (perhaps ever) unless a community member provides something.

**Comment by tofutim** [comment]
"I'm also not expecting the .NET backend to support anything more than what it supports today for a long time to come (perhaps ever) unless a community member provides something." O_o - whoa... so is node.js backend preferred then? Or no changes at all to either?

**Comment by adrianhall** [comment]
Our plans for the .NET framework edition are (a) to release a v2.0 release that is the same code, but upgraded to .NET Framework v4.6, then (b) start working on .NET Core release.    In the interim (until we get a .NET Core edition working), the Node.js edition may be the better option unless you explicitly need something that ASP.NET edition gives you.

**Comment by zaabalonso** [comment]
Hey guys any update on that for node backend?

**Comment by adrianhall** [comment]
Not yet - sorry.  We work from the issues, so this is the place to watch.

**Comment by saadfarooq** [comment]
What's the workaround mentioned in the comment? I could find any examples for .Net. Only the one for Javascript.
