### ISSUE TITLE
Support Promise / Callback to allow customers to handle expiring auth tokens

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps#24]
There is a blog post (https://blogs.msdn.microsoft.com/carlosfigueira/2014/03/12/caching-and-handling-expired-tokens-in-azure-mobile-services-managed-sdk/) for caching and handling expired tokens in AMS.  

Minimally, this needs to be tested and updated for Azure App Services plus put in the documentation.

Ideally, this should be added as an SDK feature so that it can be easily incorporated.

**Comment by elamalani** [comment]
Hi there, please have a look at the Readme section for the future of [Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps#future-of-azure-mobile-apps). Closing this issue for now. Thanks!
