### ISSUE TITLE
Support "per-user-data" in Easy Tables

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps#25]
Customer wishes to be able to have a "per-user-table" pattern explicitly available within Easy Tables.  The pattern should be an authenticated table - inserts should be tagged with the user ID.  queries should only show records tagged with the user ID.

For information from UserVoice: https://feedback.azure.com/forums/216254-mobile-apps/suggestions/3406442-automate-creating-reading-user-specific-data

**Comment by danderson00** [comment]
Portal work is not mine - likely @alrod or @fabiocav. Added  https://github.com/Azure/azure-mobile-apps-node/issues/381 as a placeholder for SDK work.

**Comment by adrianhall** [comment]
Agreed - you can blame @paulbatum for the assignment :-)

**Comment by elamalani** [comment]
Hi there, please have a look at the Readme section for the future of [Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps#future-of-azure-mobile-apps). Closing this issue for now. Thanks!
