### ISSUE TITLE
New Abstraction proj/nuget with interfaces and enum

### ISSUE THREAD

**Issue by fileman** [Azure/azure-mobile-apps#258]
**Is your feature request related to a problem? Please describe.**
To reuse models/dto in different platforms, they should be under netstandard instead of in .netX

And free from specific platform dependency like Microsoft.AspNerCore.OData as example

**Describe the solution you'd like**
Separate interfere and enum in new abstraction project/nuget. https://github.com/Azure/azure-mobile-apps/pull/254

**Comment by fileman** [comment]
in reply at https://github.com/Azure/azure-mobile-apps/pull/254#pullrequestreview-806711421 we can't use EfCore/InMemory Repositories without Core, because "exceptions" have dependencies with Microsoft.AspNetCore.Http and Microsoft.AspNetCore.Mvc

**Comment by adrianhall** [comment]
Wouldn't any other repository you define have the same exceptions?  Those are core to how the repository pattern works in this library.  

Also, .NET Standard 2.0 is superceded by .NET 6; in the service side code, you would want to define a net6.0 TargetFramework.  What is causing the back-rev to .NET Standard?

**Comment by fileman** [comment]
I try to explain myself better:
> Wouldn't any other repository you define have the same exceptions? Those are core to how the repository pattern works in this library.
>
since in the core package there are some dependencies needed for the efcore / inmemory repositories, so they cannot be used without the core package, why you say to add the new package as a direct dependency in the efcore / inmemory packages in https://github.com/Azure/azure-mobile-apps/pull/254#pullrequestreview-806711421?

> Also, .NET Standard 2.0 is superceded by .NET 6; in the service side code, you would want to define a net6.0 TargetFramework. What is causing the back-rev to .NET Standard?
>
sorry ignore "netstandard" it's my mistake, due to the habit of working with .net core 3.1, so it's ok net5.0 TFM, my goal is to have no platform specific dependencies like Microsoft.AspNetCore.* for better code share;
I wrote net5.0 because the source code has this, you plan to upgrate to net6.0 in next beta?

**Comment by adrianhall** [comment]
Yes - the next beta will be .NET 6.0 now that the .NET team has put the clock on net5.0.  I've got a PR in progress for updating this now.  (Actually, the same PR to do #255

**Comment by fileman** [comment]
ok, I will update #254 to #255 if you decide to accept it.

**Comment by adrianhall** [comment]
I think we will be pretty close once I merge in the PR for #255 (which I'm going to do before I merge this one).  The changes don't seem to conflict.

**Comment by adrianhall** [comment]
Merged in PR #254
