### ISSUE TITLE
Support NativeScript

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-mobile-apps#27]
Ported from https://github.com/Azure/azure-mobile-services/issues/887

> Nativescript is proving a very popular and rapidly growing JavaScript framework for Mobile development, which with the release of Angular 2.0 is only likely to increase. It would be great to support this new platform and I know there is a community demand for a NativeScript Plugin for Azure Mobile Services.

**Comment by paulbatum** [comment]
@georgeedwards Would a NativeScript wrapper be similar in structure to our [cordova client](https://github.com/Azure/azure-mobile-apps-cordova-client)? I'd like to understand whether there is anything blocking you from writing a wrapper yourself.

**Comment by georgeedwards** [comment]
I believe something very similar would likely be effective. I will start going through this to see if there is anything which would cause an issue. Some prime candidates will be the lack of DOM and some other JavaScript features.

**Comment by georgeedwards** [comment]
@paulbatum does the cordova wrapper have unit tests anywhere? Or a specification? It would be helpful to identify if some of the code works "as is".

**Comment by georgeedwards** [comment]
I am making some progress, and hosting my experimental project [here](https://github.com/georgeedwards/Angular-Azure-Nativescript). Nativescript doesn't have a DOM and as such, one issue with the SDK out of the box is that it doesn't support  `window`, you can see a stacktrace showing the errors this causes. 

```
JS: ERROR BOOTSTRAPPING ANGULAR
JS: EXCEPTION: ReferenceError: window is not defined in [null]
JS: ORIGINAL EXCEPTION: ReferenceError: window is not defined
JS: ORIGINAL STACKTRACE:
JS: ReferenceError: window is not defined
JS:     at Object.exports.getSdkInfo (/data/data/org.nativescript.AzureAngularNativescript/files/app/tns_modules/azure-mobile-apps-client/dist/MobileServices.Web.min.js:8:23757)
JS:     at new MobileServiceClient (/data/data/org.nativescript.AzureAngularNativescript/files/app/tns_modules/azure-mobile-apps-client/dist/MobileServices.Web.min.js:7:28886)
JS: undefined
```

How would I structure a wrapper to work around these limitations, whilst still depending on the official SDK, if that is possible?

**Comment by elamalani** [comment]
Hi there, please have a look at the Readme section for the future of [Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps#future-of-azure-mobile-apps). Closing this issue for now. Thanks!
