### ISSUE TITLE
Link broken in portal between Azure Mobile App and Push Notification Hub info

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/azure-mobile-apps#29]
Hi, 
In the HealthClinic subscription, under the Mobile App services (https://ms.portal.azure.com/#resource/subscriptions/f2756440-b605-4c6f-b69d-d8e7423dfe75/resourceGroups/HealthClinic/providers/Microsoft.Web/sites/HealthClinicMobile ), I have an issue related to the Push Notification Hub. The link/info on push notifications I used to have is not there anymore even when the hub is working and the notifications are working, but I cannot get to the push notification hub from my MOBILE APP config:
NOTE: A few weeks ago this was working properly, I could access to my notification hub properties from the mobile App, in fact, I can access to the notification hub if I search from “All resources” and the push notifications are working with the apps themselves..
See attached screenshot.
![mobileapp_pushnotifications](https://cloud.githubusercontent.com/assets/1712635/15025274/5081a894-11ed-11e6-99a0-8a11f7bacba6.jpg)

**Comment by elamalani** [comment]
Hi there, please have a look at the Readme section for the future of [Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps#future-of-azure-mobile-apps). Closing this issue for now. Thanks!
