### ISSUE TITLE
Enabling authentication causes runtime error in UWP.

### ISSUE THREAD

**Issue by abhidotnet** [Azure/azure-mobile-apps#290]
## Describe the bug

I am unable to proceed with the tutorial of authentication. On Android, the application gets stuck after the logging in process has been done. On UWP, the application proceeds beyond logging in, but there are runtime errors.

## To Reproduce

1. Go to https://github.com/Azure/azure-mobile-apps/tree/main/samples/xamarin-forms/ZumoQuickstart/ZumoQuickstart
2. git clone the repository.
3. Follow instructions at [this tutorial](https://docs.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/quickstarts/xamarin-forms/authentication) to add authentication
4. Run the application.

## Expected behavior

The application will run after logging me in through Azure AD

## What platforms?

  * UWP, Android
  * GitHub repository containing the code (optional, but helps!)
  * 

* Client (.NET, JavaScript, iOS, Android):
  * .NET Runtime Environment (WPF, UWP, Xamarin.Forms, etc.):
  * Library versions?
  * What platform versions are you running on?
  * Does it happen in an emulator/simulator, or only on a real device?
  * Yes. It happens in the emulator.

## Screenshots
Attached two videos.

https://user-images.githubusercontent.com/164457/147167481-d8a3662a-f93b-412c-9f19-3c3f7a2ef4eb.mp4

https://user-images.githubusercontent.com/164457/147167489-71771d6e-8ceb-4a97-a78e-caefb4337486.mp4

**Comment by abhidotnet** [comment]
I believe I have figured out the reasoning behind the Android Emulator. The Android Emulator is using WebView by default. I think Webview is unable to share the session information and thus it is stuck on that view. I used another Emulator with Google Play installed. This had the Chrome browser on it and it worked as expected. You may want to confirm this.

**However, the issue with UWP still exists.**

**Comment by adrianhall** [comment]
Thanks for the report.  I will go through the tutorial again to verify with UWP.  This may take some time as I am taking time off for Christmas.

**Comment by scottfeirn** [comment]
Abhijit when you report for Android "On Android, the application gets stuck after the logging in process has been done" I am experiencing similar description. At the LoginADALAsync task the AquireTokenAsync method is executed and I can login OK, however it seems never to hit the next line of code and the client app just returns to the last page, but no further code is executed. The below is the code where it "stops" from Chapter 2.

I read your issue above and so I tried a different emulator (Pixel 3 R 11.0 - API30) but still same issue.

Is my description the same as what you experienced?
Can you post the details about the emulator you used?

The execution stops at authContext.AcquireTokenAsync line

`#region Azure AD Client Flow
        public async Task<string> LoginADALAsync()
        {
            Uri returnUri = new Uri(Locations.AadRedirectUri);

            var authContext = new AuthenticationContext(Locations.AadAuthority);
            if (authContext.TokenCache.ReadItems().Count() > 0)
            {
                authContext = new AuthenticationContext(authContext.TokenCache.ReadItems().First().Authority);
            }
            var authResult = await authContext.AcquireTokenAsync(
                Locations.AppServiceUrl, /* The resource we want to access  */
                Locations.AadClientId,   /* The Client ID of the Native App */
                returnUri,               /* The Return URI we configured    */
                new PlatformParameters((Activity)RootView));
            return authResult.AccessToken;
        }
        #endregion`

**Comment by abhidotnet** [comment]
@scottfeirn 
Did you reach a login screen from the browser? What is the browser where your login screen is currently being displayed on the emulator? If it is Android WebView, the process will get stuck.

Thank You.

**Comment by scottfeirn** [comment]
@abhidotnet 
yes I go to browser and authentication process occurs requesting email and password then the emulator leaves the browser and the client xamarin app reappears but code after acquireasync dont appear to be executing eg if I put a breakpoint at "return authResult.AccessToken;" from above it is not hit. 

If you were getting stuck in the browser then sounds like a different issue I have. Doesnt look like I have any user sign-ins on azure though so I will recheck all settings

**Comment by abhidotnet** [comment]
@scottfeirn 
Which tutorial are you following? I am using the Zumoquickstart tutorial. 
I did a search across files and I don't see this specific variable - authResult

I am using the MobileServiceClientExtensions library to perform the login from the app. Have you got a git repo?

**Comment by scottfeirn** [comment]
@abhidotnet 

Sorry I am using Adirans book [https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/](url) so its different to this one. Just your description looked similar to my problem.

**Comment by adrianhall** [comment]
The book is a little out of date w.r.t. authentication at this point.  I will be doing an update to the book once the new client is out.

**Comment by scottfeirn** [comment]
the book is excellent. Updates to it will be great to see. cant wait!

**Comment by adrianhall** [comment]
The new clients are now out, and the UWP tutorial has been published.  I've verified it works with MSAL now.
