### ISSUE TITLE
Provide Client SDK access to the /.auth/me EasyAuth endpoint

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps#30]
Provide a client SDK routine to retrieve the /.auth/me endpoint to a client application.

PROPOSAL:
   var identity = client.CurrentUser.GetIdentityAsync(); // .NET
   var identity = client.currentUer.getIdentity(); // JS

Additional Proposal:
- Identity is retrieved on "first access"
- login, logout and refresh token actions cause a refresh of identity next time it is retrieved
- Should be ignored (never stored in persistent storage) when the currentuser is serialized.

**Comment by fabiocav** [comment]
We need to make sure the API accepts the provider/IdP for the identity that should be retrieved.

**Comment by nhwilly** [comment]
+1

**Comment by elamalani** [comment]
Hi there, please have a look at the Readme section for the future of [Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps#future-of-azure-mobile-apps). Closing this issue for now. Thanks!
