### ISSUE TITLE
ZumoQuickStart Question

### ISSUE THREAD

**Issue by twierman** [Azure/azure-mobile-apps#300]
You say:
The browser will display an error about a missing X-ZUMO-VERSION parameter if the server is working properly.

My browser displays:
"No route registered for '/tables/ToDoItem'"
for:
https://zumo-4kjqnfj5t3qlc.scm.azurewebsites.net/tables/ToDoItem

The App then does not get any data and crashes, on:

        public override int ItemCount => itemList.Count;

Saying that itemList "is not set to an instance of an object" = null.

 public static class Constants
    {
        /// <summary>
        /// The base URL of the backend service within Azure.
        /// </summary>
        public static string BackendUrl { get; } = "https://zumo-4kjqnfj5t3qlc.scm.azurewebsites.net";
    }

**Comment by adrianhall** [comment]
This is a backend issue, rather than a frontend view.  The controller for TodoItemController is not being registered in ASP.NET Core.
