### ISSUE TITLE
Add useful error message when redirect from http to https occurs

### ISSUE THREAD

**Issue by danderson00** [Azure/azure-mobile-apps#32]
When App Service Authentication is turned on and the mobile app URL is using http, the mobile app server will issue a 302 for every request. We should provide a useful error message for this so the user knows what is going on.

**Comment by elamalani** [comment]
Hi there, please have a look at the Readme section for the future of [Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps#future-of-azure-mobile-apps). Closing this issue for now. Thanks!
