### ISSUE TITLE
Question: compatability betwen new and old versions

### ISSUE THREAD

**Issue by anpin** [Azure/azure-mobile-apps#322]
Hi I'm looking into updating existing Xamarin.Forms solution to MAUI and I wonder if client from this repo would be compatible with legacy backend utilizing `Microsoft.Azure.Mobile.Server` from [that](https://github.com/Azure/azure-mobile-apps-net-server) repo? If not would there be any documentation on porting existing solution over? Thanks in advance.

**Comment by adrianhall** [comment]
No - the newer client is not compatible with the older server.  The older client is, however, compatible with the newer server.

I also have not tested as yet with MAUI.  While there is no reason it wouldn't work, it's not been tested.
