### ISSUE TITLE
VS Online Site Extension is Sometimes Not Installed When Opening Easy APIs

### ISSUE THREAD

**Issue by danderson00** [Azure/azure-mobile-apps#33]
After clicking on Easy Tables, if the VSO site extension is not installed, a banner appears saying "Installing Visual Studio Online site extension". This does not always happen when clicking on Easy APIs.

**Comment by elamalani** [comment]
Hi there, please have a look at the Readme section for the future of [Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps#future-of-azure-mobile-apps). Closing this issue for now. Thanks!
