### ISSUE TITLE
Uppercase GUID result invalid Id

### ISSUE THREAD

**Issue by fileman** [Azure/azure-mobile-apps#330]
## Describe the bug
Uppercase GUID are invalid for regex

## Expected behavior
since GUID are [case insensitive](https://datatracker.ietf.org/doc/html/rfc4122#section-3), why invalidate uppercase?

@adrianhall if is ok for you to remove this limitation I can submit a PR for this

**Comment by adrianhall** [comment]
Really good point - easy fix.   No need for a PR - I'll have it checked in today before I do the GA release.

**Comment by adrianhall** [comment]
Although - just to be clear - the IDs are case sensitive.  Even though we use (by default) a GUID, you can't mix case and expect it to work.  We don't demand a GUID - it's just convention.

**Comment by adrianhall** [comment]
Old regular expression for Id: `[a-z0-9-_.]{0,127}$`
New regular expression for Id: `^[a-zA-Z0-9][a-zA-Z0-9-_.]{0,126}$`

**Comment by fileman** [comment]
I didn't say it to mix upper and lower case, but if I have to use an upper case GUID generated by another software and I have the database in common it shouldn't be considered wrong.
