### ISSUE TITLE
Sqlite sample

### ISSUE THREAD

**Issue by FM1973** [Azure/azure-mobile-apps#339]
Can you please add a sample using Sqlite for offline sync?
I´m really interested how you handle the DateTimeOffset limitations in Sqlite since you are using DateTimeOffset in ITableData.

Thanks a lot!

**Comment by adrianhall** [comment]
Take a look at the tests - the Datasync Integration Tests use SQLite.  I'm not going to be producing a SQLite backend sample - it's an anti-pattern.

**Comment by FM1973** [comment]
Hi.
I didn´t mean on the server, but on the client side.

**Comment by adrianhall** [comment]
The tutorial covers SQLite offline.  I've published the WPF tutorial, and I'm working my way through the others to get them published as well.
