### ISSUE TITLE
Exception on RefreshItems

### ISSUE THREAD

**Issue by henda79** [Azure/azure-mobile-apps#345]
## Describe the bug
String was not recognized as a valid DateTime.

I've setup a ToDo demo by following the new examples. When RefreshItems items is called, this exception is thrown which seems to come from PullItemsAsync.

I tried to debug this myself, but I'm not sure what is the best way to do this as I cant seem to find the PDB symbols to load.

## To Reproduce

Run the ToDo demo

## Expected behavior

Should refresh with no exception.

## What platforms?

Xamarin Forms Android on emulator

## Screenshots

![image](https://user-images.githubusercontent.com/67002466/169719762-23588fb6-a16f-402e-87e2-c3e806fe4b3e.png)

**Comment by maxchristophudri** [comment]
I experienced this error as an faulty configured DateTimeOffset-Parser (missing the InvariantCulture-CultureInfo) while using any different CurrentCulture than en-us.

https://github.com/Azure/azure-mobile-apps/blob/2ac2751c918c8381f25b5d56988fd84497dff144/sdk/dotnet/src/Microsoft.Datasync.Client/Serialization/ServiceSerializer.cs#L119-L128

It should work using:
`return DateTimeOffset.Parse(updatedAt, CultureInfo.InvariantCulture);`

**Comment by adrianhall** [comment]
Happy to take a PR - thanks!

**Comment by adrianhall** [comment]
Thanks for the PR @maxchristophudri
