### ISSUE TITLE
Use LiteDb on client side

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps#356]
I want to be able to use LiteDb on the client side.

LiteDb does not use .NET 6.0, so likely will have to wrap the code and deal with it there.

**Comment by stephenhauck** [comment]
I'm interested in this as well

**Comment by Arslan007** [comment]
@adrianhall Do you have any plans for this? I am interested in this as well and happy to chip in for this part

**Comment by adrianhall** [comment]
I do have plans to do it, but happy to accept contributions.  Looking out the next couple of months, I'll be primarily working on publishing the first version of the JS/TS library, and potentially upgrading the SQLite .NET library used in SQLiteOfflineStore so that it can be used by Blazor applications.

If you are going to be working on it, let me know and we'll see how we can collaborate.

**Comment by adrianhall** [comment]
Due to the fact that we need access to internals of LiteDB to do this, it isn't going to move forward.
