### ISSUE TITLE
Patch request to server SDK doesn't recognize EF Core 1:N conventions

### ISSUE THREAD

**Issue by Vroomer** [Azure/azure-mobile-apps#370]
## Describe the bug

Server SDK doesn't seem to properly recognize properties defined in models for the purpose of EF Core 1:N convention mapping.

## To Reproduce

Example: 3 models defining data in SQL server tables: PriceCustomer, Customer, PriceStandard.
Customer and PriceStandard have M:N relationship represented by PriceCustomer as two 1:N relationships.

```
public partial class PriceCustomer : EntityTableData 
{ 
    public decimal? Price { get; set; }  

    public string CustomerId { get; set; }
    public Customer Customer { get; set; }

    [Column("PriceId")]
    public string PriceStandardId { get; set; }
    public PriceStandard PriceStandard { get; set; }
}
```
_Notice that PriceCustomer has the foreign key for PriceStandard under different name in database, which is handled by annotation._

```
public partial class PriceStandard : EntityTableData
{
    public string? Description { get; set; }

    public decimal? Price { get; set; }

    public ICollection<PriceCustomer> PriceCustomers { get; set; }
}
```

```
public partial class Customer : EntityTableData
{
    public string? Name { get; set; }

    public ICollection<PriceCustomer> PriceCustomers { get; set; }
}
```

Models are set up based on conventions defined here: https://www.entityframeworktutorial.net/efcore/one-to-many-conventions-entity-framework-core.aspx using the 4th type.

Patch request with json body:
```
{"price":2.0,"customerId":"2D863256-CC75-4F01-AD64-2F813B4BA853","PriceStandardId":"28ATT0A7-7448-405A-8203-3DB2A964958C","id":"180DFE19-ADCE-478D-9BB5-BRQD0E408EEB","deleted":false,"updatedAt":"2022-06-05T16:13:24.868Z","version":"AAAAAAABCaE="}
```

Returns 400 Bad Request:
```
{
    "customer": [
        "The Customer field is required."
    ],
    "priceStandard": [
        "The PriceStandard field is required."
    ]
}
```

## Expected behavior

In previous SDK for .NET Framework this wasn't an issue. SDK did recognize these conventions. Using 2nd convention defined in https://www.entityframeworktutorial.net/efcore/one-to-many-conventions-entity-framework-core.aspx seems to work, however if the foreign key uses any annotation such as in the case of this example, it has to be explicitly defined in the model.

## What platforms?

Microsoft.AspNetCore.Datasync - 5.0.3
Microsoft.AspNetCore.Datasync.EFCore - 5.0.3
Microsoft.EntityFrameworkCore.Design - 7.0.0-preview.4.22229.2
Microsoft.EntityFrameworkCore.SqlServer - 7.0.0-preview.4.22229.2
Microsoft.EntityFrameworkCore.Tools - 7.0.0-preview.4.22229.2
Tested using Postman, staged in localhost.

**Comment by adrianhall** [comment]
Azure Mobile Apps doesn't support JOINs (and never has).  You have to define your models so that the individual tables can be pushed separately. 

You can do this, but would have to set up a repository that explicitly sets up the EF model based on what is coming in.

**Comment by Vroomer** [comment]
I think you misunderstood my point. I do understand that Azure Mobile Apps doesn't support JOINs and I do push tables separately as unrelated entities. However I do use EF code first approach for database creation, so I need to have models defined with relationships, for which I use EF Core conventions. This wasn't an issue previously as I used the exact same models with Azure Mobile Apps and it did correctly ignore fields that are defined solely for the purpose of connection - i.e. following properties:
```
public Customer Customer { get; set; }
```
```
public PriceStandard PriceStandard { get; set; }
```
Now it requires these fields, which results in 400 Bad request, because I'm obviously not pushing those fields in json.

**Comment by adrianhall** [comment]
Can you post the body of the response?

I'm wondering if the object validator is finding them required because of the .NET6 language (#nullable)?

**Comment by Vroomer** [comment]
The body of the response is included in the issue description:
```
{
    "customer": [
        "The Customer field is required."
    ],
    "priceStandard": [
        "The PriceStandard field is required."
    ]
}
```

**Comment by adrianhall** [comment]
I think you would benefit from the Automapper repository (see #371) in that case - the DTO is different from the domain model, so mapping between them is valid.  Thoughts?

**Comment by adrianhall** [comment]
Alternatively, maybe making PriceStandard and Customer an optional (add a ? on the end)?

**Comment by adrianhall** [comment]
Can you check to see if the Automapper fix (which is in main, so you will have to build from source right now) fixes this issue?

**Comment by Vroomer** [comment]
Sorry I forgot about this. I tried to add ? for the property and it now properly ignores it resulting in 200 Success. However I haven't tried to generate new database with this code to see if it doesn't affect the EF convention.

**Comment by adrianhall** [comment]
Closing for 30 day notice.  Looks like it is fixed.  Re-open and comment if creation of the database is affected.
