### ISSUE TITLE
Add a WinUI3 Sample

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps#372]
**Is your feature request related to a problem? Please describe.**
Need a sample for WinUI3

**Comment by CaseNewmark** [comment]
Have a look at #373

**Comment by adrianhall** [comment]
Thanks for that.  Love it.  The PR will be sitting there for a while so I can figure out the problem with the library; once I've got that done, I'll be able to merge it in.  I appreciate your submission!

**Comment by CaseNewmark** [comment]
You are welcome. Btw. downgrading to 5.0.2 works like a charm (obviously). :)

**Comment by adrianhall** [comment]
Hmm - that's actually stranger, because the "per-platform" code was introduced in 5.0.2 - 5.0.3 was just an upgrade to the SQLite version.  I will investigate.

**Comment by CaseNewmark** [comment]
Uhmm. Not at work atm and I'm not completely sure, I didn't downgrade to 5.0.1.

**Comment by adrianhall** [comment]
No worries - I'm not working on this until Friday - would be good to have an idea.

**Comment by adrianhall** [comment]
Figured out the problem with WinUI - It's going to require a release, so there will be a 5.0.4 that supports WinUI3.  Basically, net6.0-windows was using Microsoft.Maui.Storage - I switched it to use Windows.Storage instead, then tested on WPF, UWP, WinUI, and MAUI Windows to ensure it works properly.  Once 5.0.4 is out, I'll be able to work on the WinUI tutorial.
