### ISSUE TITLE
EntityTableRepository constraint issue

### ISSUE THREAD

**Issue by henda79** [Azure/azure-mobile-apps#382]
Would it not make more sense to have the constraint on the EntityTableRepository class as ITableData ?

For my use case where I want to use other types for the Id rather than string, it would be easier as I could just create my own base class which implements ITableData which then can replace EntityTableData

`  public class EntityTableRepository<TEntity> : IRepository<TEntity> where TEntity : ITableData
  {...}`

The workaround at the moment is to just copy the EntityTableRepository code and use that.

**Comment by adrianhall** [comment]
We actually need a specific concrete type where we can add attributes to the properties that EF requires.

You have the right idea though - you need to copy the EntityTableRepository and EntityTableData to create your own repository.
