### ISSUE TITLE
Add documentation for IdGenerator.

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps#383]
## Describe the bug

The IdGenerator code is not documented in the HOWTO

**Comment by fileman** [comment]
How can I add it to wiki / howto?

**Comment by adrianhall** [comment]
Don't worry about this one - you can't, so I will.

**Comment by adrianhall** [comment]
Added docs for IdGenerator to the Wiki - let me know what you think (and I will transfer to the HOWTO on the main docs site)

**Comment by fileman** [comment]
it seems to me that it is fine, if for someone it is not clear they will ask for information

**Comment by adrianhall** [comment]
Docs merged into main docset.
