### ISSUE TITLE
NullReferenceException on OfflineSQLiteStore in UpsertAsync method

### ISSUE THREAD

**Issue by henda79** [Azure/azure-mobile-apps#384]
## Describe the bug

I've came across an exception when playing with the TodoApp demo.

This exception is thrown in the OfflineSQLiteStore UpsertAsync method.

## To Reproduce

I have made changes to the app and the schema of the Database so maybe this is my doing.

## Expected behavior

I would have though the null reference should not be thrown.

## What platforms?

ASP.Net Core 5.0.1

Xamarin.Forms, Android Emulator

* Client (.NET, JavaScript, iOS, Android):
  * .NET Runtime Environment (WPF, UWP, Xamarin.Forms, etc.):
  * Library versions?
  * What platform versions are you running on?
  * Does it happen in an emulator / simulator, or only on a real device?

## Screenshots

![image](https://user-images.githubusercontent.com/67002466/173556434-e09ec8ae-fcaf-4549-884d-20ca03639974.png)

## Additional context

The variable c is null for the column definition.

I am debugging this today to see why this happens and will report back.

**Comment by henda79** [comment]
It seems when using the `JsonIgnore` attribute one must use the same library. In my model I was using:

`System.Text.Json.Serialization` when I should have been using `Newtonsoft.Json`

At least this mistake highlighted a bug and hopefully can educate others, I never knew about this.

@adrianhall , I recommend updating the code as shown above and closing this issue.

**Comment by adrianhall** [comment]
I can see the bug - feel free to submit a PR if I don't get to it first.

**Comment by henda79** [comment]
@adrianhall , I've done a PR but it's my first one so not sure if I've don't it correctly.

**Comment by adrianhall** [comment]
I saw - thank you!  There is a style issue to fix, and a build issue I need to fix.

Welcome to the open source contributors community!
