### ISSUE TITLE
Add JavaScript / TypeScript library

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps#405]
**Is your feature request related to a problem? Please describe.**

* Support for React Native
* Support for Blazor

Offline mode to use react-native-sqlite-2 on React Native and IndexedDb on web properties - implement as separate packages.

**Comment by zmachine82** [comment]
My expertise is more in Angular/Ionic. Would love support there.

**Comment by adrianhall** [comment]
We will not be supporting a TypeScript library at this time.  This is because (a) the REST API is available, and (b) I don't have enough time or the requisite knowledge to support the TypeScript library for offline capabilities.
