### ISSUE TITLE
NULL values are not updated when calling IOfflineTable.PullItemsAsync

### ISSUE THREAD

**Issue by cbs-cbt** [Azure/azure-mobile-apps#408]
## Describe the bug

When a field of an item is changed from any value to null, then this field is not updated on other clients after a PullAsync.

### Phase 1
**On client 1:**
```
MyObject.MyStringProperty = "This is a string"
await MyObjectsOfflineTable.ReplaceItemAsync(MyObject);
await MyObjectsOfflineTable.PushItemsAsync().ConfigureAwait(false);
await MyObjectsOfflineTable.PullItemsAsync().ConfigureAwait(false);
```
**Server's database:**
✔ Table MyObjects, MyStringProperty of the item is "This is a string"

**On client 2:**
`await MyObjectsOfflineTable.PullItemsAsync().ConfigureAwait(false);`
✔ `MyObject.MystringProperty` is now "This is a string"

### Phase 2
**On client 1:**
```
MyObject.MyStringProperty = null
await MyObjectsOfflineTable.ReplaceItemAsync(MyObject);
await MyObjectsOfflineTable.PushItemsAsync().ConfigureAwait(false);
await MyObjectsOfflineTable.PullItemsAsync().ConfigureAwait(false);
```
**Server's database:**
✔ Table MyObjects, MyStringProperty of the item is NULL

**On client 2:**
`await MyObjectsOfflineTable.PullItemsAsync().ConfigureAwait(false);`
❌ `MyObject.MyStringProperty` stays "This is a string"

## Expected behavior

In phase 2 and on client 2, `MyObject.MyStringProperty` should be null and not remain "This is a string" 

## What platforms?

* Server: ASP.NET Core, Net 6.0:
  * Microsoft.AspNetCore.Datasync, Version=5.0.5
  * Microsoft.AspNetCore.Datasync.EFCore, Version=5.0.5
  * Azure SQL database
  * Azure

* Client: UWP and Android (not yet tested on iOS, but the bug should also exist):
  * Xamarin.Forms
  * Version: 5.0.0.2478
  * Platforms: UWP and Android
  * This happen on any device

## Screenshots

**Example 1:**
![image](https://user-images.githubusercontent.com/15328452/175088915-2b5dee92-ab15-41d4-8263-6f4fa3948966.png)

**Example 2:**
![image](https://user-images.githubusercontent.com/15328452/175091742-caae54ce-2aa2-436a-bcc3-c8c7ee0a823d.png)

## Additional context

In my opinion, this bug occurs because the TableController<TEntityTableData> does not return fields that have a null value in JSON objects and as a result the client does not update the object properties because there is no field with the property name in the JSON object
Above (in Screenshots) two examples of query results on the "Supports" table of our database. In example 1, the text field "Tasks" contains the value "This is a string", in the second example, this field has the value NULL in the database

**Comment by adrianhall** [comment]
So, this turned into a bigger problem than I thought it would.  Basically, we assume null values are not transmitted all over the tests, resulting in a major re-factoring of the tests.  It will likely be a multi-week affair to update these.

**Comment by adrianhall** [comment]
Finally figured it out - basically, the `DatasyncClientData` needed to be updated to have defaulted values for transfer, then a bunch of tests (about 400 of them) needed to be updated to account for the fact that they were no longer null.

I also fixed a race condition in the tests that had been bugging me.

@cbs-cbt Would appreciate a test of the code in your situation when you have a chance (and the PR is merged - it's currently running through the test suite) so that we can be confident I have fixed the issue.

**Comment by cbs-cbt** [comment]
Hello Adrian,
We have done some tests with the new version of the library integrated in our software and everything works as it should now.

I can confirm that the issue has been resolved.

Thank you very much for your responsiveness and professionalism.
