### ISSUE TITLE
ServiceSerializer.GetUpdatedAt throws System.FormatException on client

### ISSUE THREAD

**Issue by cbs-cbt** [Azure/azure-mobile-apps#409]
## Describe the bug

`Microsoft.Datasync.Client.Serialization.ServiceSerializer.GetUpdatedAt` throws 
`System.FormatException: 'String '06/22/2022 11:01:27' was not recognized as a valid DateTime.'`
when PullItemsAsync on client

## To Reproduce

Call `await MyObjectsOfflineTable.PullItemsAsync().ConfigureAwait(false);` on client, this will throw `System.FormatException`

## Expected behavior

`System.FormatException` is not thrown

## What platforms?

* Server: ASP.NET Core, Net 6.0:
  * Microsoft.AspNetCore.Datasync, Version=5.0.5
  * Microsoft.AspNetCore.Datasync.EFCore, Version=5.0.5
  * Azure SQL database

* Client: UWP and Android (not yet tested on iOS, but the bug should also exist):
  * Xamarin.Forms
  * Version: 5.0.0.2478
  * Platforms: UWP and Android
  * This happen on any device

## Screenshots

**Location of the exception:**
![image](https://user-images.githubusercontent.com/15328452/175227911-e5a21546-8e28-4894-903a-037879bc527a.png)

**Content of `item` JObject:**
![image](https://user-images.githubusercontent.com/15328452/175231058-d9b3e340-80a7-441d-a54a-d5b439c614c9.png)

**`UpdatedAt` value cast directly from JObject:**
![image](https://user-images.githubusercontent.com/15328452/175230658-f2815a8c-ea8a-4dc0-bc33-5728499d6c63.png)

## Additional context

To solve the problem, it would be necessary to define the expected date format in `DateTimeOffset.Parse` because `DateTimeOffset` does not necessarily expect the ISO 8601 format
_We may have missed something, maybe we need to configure the JSON serializer used on our client. Because I don't understand why this code works on your clients._

After analysis, it seems that the `updatedAt` value can be directly cast from `item` JObject thanks to the JSON deserializer, without the need to go through a transformation of a string.
Here is the code we use to work around the problem and it works on the clients we use:
```
public static DateTimeOffset? GetUpdatedAt(JObject item)
{
  var l_jvValue = item[SystemProperties.JsonUpdatedAtProperty];

  try
  {
    var l_dtResult = ((DateTimeOffset?)l_jvValue);

    if (l_dtResult.HasValue) return l_dtResult;
  }
  catch
  {

  }

  string updatedAt = item.Value<string>(SystemProperties.JsonUpdatedAtProperty);
  
  if (updatedAt == null)
  {
    return null;
  }
  // Throw an error if the service returned a bad date format.
  return DateTimeOffset.Parse(updatedAt);
}

```

**Comment by adrianhall** [comment]
Very wierd.  As you said - the pullitemsasync tests should catch this and they aren't.  We tend to be fairly liberal on the format of the date being returned by the service - hence the Parse and not ParseExact usage.  Will take a look.

**Comment by adrianhall** [comment]
I cannot reproduce this error.

I've got a "KitchenSink" folder in the Integration.Test project.  Any chance you can add a test that showcases the error, then post the test case?

**Comment by cbs-cbt** [comment]
Hello Adrian,
The tests present in the library are already failing on my PC. Apparently it's a locale issue.
The tests fail when I run them on my PC with the fr-CH locale (settings I use by default).
On the other hand, if I set the locale to en-US then everything works fine.

![image](https://user-images.githubusercontent.com/15328452/175926329-4495ec23-00b7-4414-a18f-0d0ca07c3209.png)

![image](https://user-images.githubusercontent.com/15328452/175927005-f7053273-ae9a-4a6d-9856-7cfedd4a02e7.png)

**Comment by fileman** [comment]
Did you have the lastest commit?
I see less test, I have 3954 tests with 1219 in Integration.Test while you have 2921 and 686

**Comment by cbs-cbt** [comment]
Hello Fileman,
Thanks for the remark.

After pulling the latest version of the library (which forced me to install VS 2022 Preview), all tests pass regardless of the regional settings configured on the PC.

While inspecting the code, I noticed that on May 25 _mcudri_ changed the last line of code of the `GetUpdatedAt` function which changed from `return DateTimeOffset.Parse(updatedAt);` to `return DateTimeOffset.Parse(updatedAt, CultureInfo.InvariantCulture);`

This change solved the problem.
