### ISSUE TITLE
Unable to install Microsoft.Azure.Mobile.Client.SQLiteStore.2.1.1 NuGet in XS

### ISSUE THREAD

**Issue by jamesmontemagno** [Azure/azure-mobile-apps#41]
Please change:
portable-win+net45+wp8+wpa81+monotouch+monoandroid
to
portable-win+net45+wp8+wpa81

or add on Xamarin.iOS10 such as: portable-win+net45+wp8+wpa81+monotouch+monoandroid+Xamarin.iOS10

Microsoft.Azure.Mobile.Client.SQLiteStore.2.1.1 refuses to install in XS due to this.

**Comment by jamesmontemagno** [comment]
Please see: https://bugzilla.xamarin.com/show_bug.cgi?id=43619

**Comment by lindydonna** [comment]
@dhei @pragnagopa Could one of you take a look?

**Comment by pragnagopa** [comment]
Will address this as part of the next release.

**Comment by pragnagopa** [comment]
Updated profile to include xamarinios10 and published Microsoft.Azure.Mobile.Client.SQLiteStore.3.0.0-beta.
