### ISSUE TITLE
Microsoft.OData.ODataException: 'The Any/All nesting limit of '1' has been exceeded. 'MaxAnyAllExpressionDepth' can be configured on ODataQuerySettings or EnableQueryAttribute.'

### ISSUE THREAD

**Issue by anpin** [Azure/azure-mobile-apps#417]
## Describe the bug
Using combination of `$expand` and `$filter` query results in `Microsoft.OData.ODataException: 'The Any/All nesting limit of '1' has been exceeded. 'MaxAnyAllExpressionDepth' can be configured on ODataQuerySettings or EnableQueryAttribute.'` even when controller/action is decorated with `[EnableQuery(MaxAnyAllExpressionDepth = 5)]`

## To Reproduce

Invoke controller with query similar to
```
?$filter=(updatedAt%20gt%20cast(1970-01-01T00%3A00%3A00.000Z,Edm.DateTimeOffset))%20or%20(Preset%2Fany(p%3Ap%2FupdatedAt%20gt%20cast(1970-01-01T00%3A00%3A00.000Z,Edm.DateTimeOffset)))%20or%20(Video%2Fany(v%3Av%2FupdatedAt%20gt%20cast(1970-01-01T00%3A00%3A00.000Z,Edm.DateTimeOffset)))&__includedeleted=true&$expand=Preset,Video
```

## Expected behavior

Requested value expands

## What platforms?

* Server (ASP.NET Framework, ASP.NET Core, NodeJS):
  * Library versions? 5.0.6
  * What database are you using? SQL
  * Where are you running the server? AppService and locally 
  * GitHub repository containing the code (optional, but helps!) sorry I can't

* Client (.NET, JavaScript, iOS, Android):
  * .NET Runtime Environment (WPF, UWP, Xamarin.Forms, etc.): net6.0
  * Library versions? 5.0.6
  * What platform versions are you running on? MAUI Windows 
  * Does it happen in an emulator / simulator, or only on a real device? yes 

## Additional context

This discussion https://github.com/Azure/azure-mobile-apps/discussions/325 points me to the fact that `[EnableQuery]` is not compatible with `ODataQueryOptions` validation here https://github.com/Azure/azure-mobile-apps/blob/63da39887ff3ab9e6be0308fc8376cef9d106f89/sdk/dotnet/src/Microsoft.AspNetCore.Datasync/Tables/TableController.cs#L308

However this used to be working with previous `.NET Framework` solution and we need a way to expand objects or include them if nested data was updated, maybe we need to pass `MaxAnyAllExpressionDepth` through `TableControllerOptions`? I would actually prefer passing instance of `ODataValidationSettings` to `TableControllerOptions` as it seems to have all the necessary checks regarding value ranges and should be more efficient

**Comment by anpin** [comment]
> It sounds like you actually need a generic OData service, which is not what this is. I've tried to stay away from OData except as a means to an end (to provide a query language for LINQ operations).
> 
> Can you provide an example of how this would help offline operations in a single table?

This won't help a single table indeed, however I'm porting legacy project which had this functionality and I need this for compatibility reasons with older clients in the hope to drop support of legacy project. Made a very crude workaround here https://github.com/anpin/azure-mobile-apps/tree/feature/odata-validation

**Comment by adrianhall** [comment]
You are quite welcome to fork and use the new service as you described.  I will not be implementing this change.

**Comment by anpin** [comment]
I totally get that, but would you accept PR with this functionality? On Fri, Jul 1, 2022 at 8:52 PM, Adrian Hall ***@***.***> wrote:  
You are quite welcome to fork and use the new service as you described.  I will not be implementing this change.

**Comment by adrianhall** [comment]
As long as the implmentation defaults did not change (they do now).  I'd also likely suggest changing the semantics.  Something like:

``` csharp
var options = new TableControllerOptions
{
  ODataExpansionOptions = new ODataQueryExpansionOptions 
  {
    MaximumAnyAllExpressionDepth = 1,   // Defaults to 1
    MaximumExpansionDepth = 1,  // Defaults to 1
    MaximumNodeCount = 100, // Defaults to MaxTop
  }
}
```

I would also make them conditional on seeing $expand.  ie.

``` csharp
if (Options.ODataExpansionOptions != null && context.Request.QueryString.Contains("$expand=", StringComparison.OrdinalIgnoreCase)) 
{
  validationSettings.MaxAnyAllExpressionDepth = Options.ODataExpansionOptions.MaximumAnyAllExpressionDepth;
  validationSettings.MaxExpansionDepth = Options.ODataExpansionOptions.MaximumExpressionDepth;
  validationSettings.MaxNodeCount = Options.ODataExpansionOptions.MaximumNodeCount ?? Options.MaxTop;
}
```

... something like that.  In that way, the settings are only available if you really know that you want them, and can't be enabled (with possible side effects) unless you explicitly request expansion.
