### ISSUE TITLE
Adding index to offline local db

### ISSUE THREAD

**Issue by FrancoisM** [Azure/azure-mobile-apps#42]
Hi,

How would you define constraints (indexes) for the local tables created with DefineTable in Microsoft.WindowsAzure.MobileServices.SQLiteStore.MobileServiceSQLiteStoreExtensions?

I want to replicate the constraints of my backend db.

**Comment by shrishrirang** [comment]
Currently there is no API which lets you do this. But till we have such an API, you can create a connection to the database file yourself and define the index. [This](https://github.com/Azure/azure-mobile-apps-net-client/blob/master/src/Microsoft.WindowsAzure.MobileServices.SQLiteStore/MobileServiceSQLiteStore.cs#L540) is how the SDK executes SQLite statements. You will have to be careful though when you bypass the SDK and run SQLite statements yourself.

**Comment by elamalani** [comment]
@FrancoisM Closing this issue as @shrishrirang shared an alternative on how to define the index to your database file by creating a connection. Please feel free ask us any questions related to Azure Mobile Apps.  Thanks!
