### ISSUE TITLE
Where is Microsoft.Azure.Mobile.Server.SignalR?

### ISSUE THREAD

**Issue by tofutim** [Azure/azure-mobile-apps#43]
I do not see it in nuget. How can I get it? Am trying to solve my localhost signalr+zumo debugging issue in http://stackoverflow.com/questions/40033175/enabling-authentication-with-signalr-against-azure-mobile-services-when-debuggin - any tips much appreciated.

**Comment by elamalani** [comment]
@tofutim Sorry for the long delay in responding to your issue but as it is mentioned in the conversation on stackoverflow - "You are following a tutorial for Azure Mobile Services, yet using Azure Mobile Apps. The two are not compatible. Explicitly, we have not included SignalR in the latest SDKs - this is something you are going to have to implement yourself. When you have Authentication set up properly, a simple [Authorize] tag on any controller will ensure the user is authenticated. The SignalR setup is orthogonal to Azure Mobile Apps now."

I will close this issue but feel free to open another ticket if you have any questions related to Azure Mobile Apps. Thanks!

**Comment by tofutim** [comment]
Are you the new maintainer for zumo?

**Comment by elamalani** [comment]
@tofutim Yes, I am.

**Comment by tofutim** [comment]
Fantastic, thank you!

**Comment by tofutim** [comment]
Any chance you can give us an update on future directions?

**Comment by elamalani** [comment]
@tofutim Sure. We are committed to supporting Azure Mobile Apps including support for the latest OS releases, bug fixes, and documentation updates.

We are doing user research right now to understand the evolving needs for these services and plan to build the next generation of Azure Mobile Apps as part of Visual Studio App Center. We are re-imagining key developer workflows and adding new features, as well as integrating them into an end-to-end CI/CD solution that helps developers ship better apps faster.
