### ISSUE TITLE
'Required 'id' property is not found.

### ISSUE THREAD

**Issue by henda79** [Azure/azure-mobile-apps#436]
## Describe the bug
I get an exception 'Required 'id' property is not found only when Updating a row in an offline Sqlite Db but NOT when inserting.

My client models have a base class of 

```
        [JsonProperty("id")]
        public Guid Id { get; set; } = Guid.NewGuid();

        [JsonProperty("deleted")]
        public bool Deleted { get; set; }

        [JsonProperty("updatedAt")]
        public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.MinValue;

        [JsonProperty("version")]
        public string? Version { get; set; }

        [JsonProperty("createdAt")]
        public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;
```

Notice I am using a Guid for the id property instead of string. I know this is causing this issue as there is on the system properties which check is they are present and also their type. But the problem here is this exception only happens on updating

Is there some reason for this ?

## Expected behavior

I'd expect the exception to be thrown for all Db actions.

## What platforms?

Android, Emulator, Xamarin Forms

**Comment by adrianhall** [comment]
It's perfectly valid to submit a record without an ID, so this is expected.  It should also throw on deletions.

**Comment by henda79** [comment]
@adrianhall , sorry I don't follow or maybe you don't get what I mean,

If I try to update a record using a valid Id (Guid), with the model above, I get an exception
