### ISSUE TITLE
Require a method to Pull all tables from client.

### ISSUE THREAD

**Issue by henda79** [Azure/azure-mobile-apps#440]
### Discussed in https://github.com/Azure/azure-mobile-apps/discussions/439

As per the discussion, it would be good to be able to pull all the tables by only having to call one method as at the moment we need to keep a track of defined tables and iterate through them getting the reference to each and then calling PullItemsAsync.

Maybe have an overloaded method that allows to somehow specify a selection of tables in cases where you don't want to pull all defined tables.

**Comment by adrianhall** [comment]
Thinking about this, it's a little hairy in the generalized case.  However, (once the PR happens), you'll be able to write:

``` csharp
await client.PushTablesAsync();
var listOfTables = await store.GetTablesAsync();
foreach (var tableName in listOfTables) {
  var tableRef = client.GetOfflineTable(tableName);
  await tableRef.PullItesmAsync("", new PullOptions());
}
```

... to pull all items from all tables.  In more complex cases, you will want to set up a map of options/query and table names, then use the query and PullOptions from there (and if not set, assume the basics above).

**Comment by henda79** [comment]
Looks good, just waiting for the merge.

**Comment by adrianhall** [comment]
Merged - will be in next release.

**Comment by henda79** [comment]
> 

I'm testing this out, can you provide a short example on the more complex cases of pulling only certain tables ? I'm not sure what to pass through to PullOptions.

**Comment by adrianhall** [comment]
The method provided gives you a list of all offline tables you have defined.  You get to define what to do with that list.  It's best used when you are pulling "everything" from "everywhere" - in which case the snippet I provided above would be enough.  After that, it's a case of defining the exceptions, then changing the loop to say "if there is an exception, use it; otherwise do the default".

**Comment by henda79** [comment]
Yes, I imagine it is fine as-is for pulling everything, but what is the query parameter used for. You mentioned in an earlier comment about more complex cases and mapping tables.

**Comment by adrianhall** [comment]
The query is an OData filter.  Let's provide an example.  Let's say that you have the following:

``` csharp
Dictionary<string, string> queryMap = new Dictionary<string, string> {
  "table2", "(cacheLocally eq true)",
  "table4": "##do-not-sync##"
};

Dictionary<string, PullOptions> pullOptionMap = new Dictionary<string, PullOptions> {
  "table3", new PullOptions { PushOtherTables = false }
};
```

The first dictionary maps a table name to an OData query.  The second dictionary maps a table name to the required pull options.  I'm also using a "non-OData" magic string to say "don't sync this table" in the query map.  You can now do the loop:

``` csharp
var listOfTables = await store.GetTablesAsync();
foreach (var tableName in listOfTables) {
  var tableRef = client.GetOfflineTable(tableName);
  string query = queryMap.ContainsKey(tableName) ? queryMap[tableName] : "";
  PullOptions options = pullOptionMap.ContainsKey(tableName) ? pullOptionMap[tableName] : new PullOptions();
  if (!query.StartsWith("##")) {
    await tableRef.PullItesmAsync(query, options);
  }
}
```

This code allows you to put exceptions in the two dictionaries according to your needs.  If there is no exception, all records will be pulled in an incremental sync manner.  So it's highly flexible.

**Comment by henda79** [comment]
Thanks for that Adrian.
