### ISSUE TITLE
Can't find a constructor for the Azure Mobile Service Client

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-mobile-apps#441]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#30016](https://github.com/Azure/azure-sdk-for-net/issues/30016).

## Details

When calling our Azure API endpoint UserController.CurrentUser() action, it uses the Azure MobileServiceClient  assembly. However sometimes it generates and error message is basically that it can't find the method on the Azure MobileServiceClient class and the method it's looking for is the constructor for the MobileServiceClient that takes in a string URL and a list of HttpMessageHandlers. The use the latest version of the MobileServiceClient assembly version 4.2.

**Comment by rensohollhumer** [comment]
This issue is intermittent too and we cannot reproduce it on-demand. Next time it happens to one of our customers using our website or thin-client desktop we'll post the exception here

**Comment by adrianhall** [comment]
We no longer support the MobileServiceClient v4.2

The latest version is here: https://www.nuget.org/packages/Microsoft.Datasync.Client
