### ISSUE TITLE
Pulling items fetches the same set of records repeatedly

### ISSUE THREAD

**Issue by wedgeley** [Azure/azure-mobile-apps#442]
### Symptoms
Watching the sync in Fiddler, I see that my client is sending the same request and getting the same 3 pages of records every time PullItems is called.

(You can see this behaviour in the sample TodoApp application as well.)

### Reason
When pulling items from the server, the client gets the latest changes by applying a $filter on field "UpdatedAt". It remembers this value from the last returned record. This strategy doesn't work unless the records are returned in UpdatedAt order.

The query is missing:"$orderby=updatedAt".

### Code
It looks like the relevant code module is SyncContext.cs method PullItemsAsync. I might have been able to workaround the problem by ordering my query manually, but this method wipes any orderings (queryDescription.Ordering.Clear()).

I can see deltaTokenFilter is going to add "UpdateAt > x", so perhaps this is the place to add:

`queryDescription.Ordering.Add(new OrderByNode(new MemberAccessNode(null, SystemProperties.JsonUpdatedAtProperty), OrderByDirection.Ascending));`

**Comment by adrianhall** [comment]
See also #438 - need to fix both to correct issue.

**Comment by adrianhall** [comment]
TO DO:
* Update `SyncContext.cs` PullItemsAsync to add an ordering for UpdatedAt
* Update the 24 tests (12 for JSON, 12 for Generic) that test the PullItemsAsync for the client.

**Comment by wedgeley** [comment]
Confirmed fixed in 5.0.10. 
Thanks for the quick response.
