### ISSUE TITLE
Aggregate Pull into one call to server

### ISSUE THREAD

**Issue by FrancoisM** [Azure/azure-mobile-apps#45]
I often (if not always) triggers multiple pulls for different tables at once.
I wish there were an aggregated pull to avoid round trips to the server. There would be a endpoint calling individual endpoints and sending back individual results aggregated that the mobile client service would then parse.

**Comment by elamalani** [comment]
@FrancoisM Sorry for the delayed reply on this issue and thanks for sharing your feedback. We don't support this functionality in the SDK right now and also, there is no plan to add it in the near future.

**Comment by elamalani** [comment]
Hi there, please have a look at the Readme section for the future of [Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps#future-of-azure-mobile-apps). Closing this issue for now. Thanks!
