### ISSUE TITLE
MAUI ToDo Authentication: multiple logins

### ISSUE THREAD

**Issue by LKujala** [Azure/azure-mobile-apps#458]
## Describe the bug

Authentication Dialog shown X times (once for every data item in table).
the Items Observable Collection is repopulated with all X items on each call to the Authentication dialog.

## To Reproduce

1. Follow steps in "Add authentication to your .NET MAUI app"
2. Run Windows App
3. Add Multiple items
4. Close App and restart
5. Get the authentication dialog once for each saved item

## Expected behavior

Authentication dialog should show once.

## What platforms?

Code from https://docs.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/quickstarts/maui/
applied changes as per https://docs.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/quickstarts/maui/authentication
testing ToDoApp.MAUI running Windows (but also occurs on Android emulator)

* using VS 2022 17.4.0 Preview 1 (updated as of Aug 23 2022)
* update all nuget packages to latest version (updated as of Aug 23 2022)

## Additional context

* Issue only occurs on start up.
* Once app is running, can clear/refresh list of items without getting the authentication dialog.
* stepping through the debugger, the authentication dialog seems to be triggered by the For Each call in To List Async (in System.Linq.Async.ToListAsync)
![image](https://user-images.githubusercontent.com/98625461/186279898-a1ca1604-4e16-4793-a29c-3344381678e2.png)

* Update: changing focus between apps causes the list to automatically refresh (eg alt+tab to another app, then alt+tab back)

**Comment by LKujala** [comment]
Issue seems to be with ToDoListViewModel.OnActivated() being call by the MainPage OnAppearing() event. the OnAppearing event will be called everytime the Window receives Focus; the OnActivated function then calls RefreshItemsAsync() without checking to see if there is an outstanding call.

* the OnActivated is called multiple times, because the Authentication dialog pops up, which changes focus away from parent window
* need to decouple the "show window" event from the "refresh data" data event.

Fix / Hack: remove the RefreshItemsAsync() from OnActivated() and add a button to "refresh" data.

**Comment by adrianhall** [comment]
Thanks for the report - probably better to do a lock around the RefreshItemsAsync() code block such that multiple calls to RefreshItemsAsync() are ignored.  Something as simple as:

``` csharp
if (IsRefreshing) { return; }
```

(TodoApp.Data project in MVVM/TodoListViewModel.cs - RefreshItemsAsync method - see https://github.com/Azure/azure-mobile-apps/blob/main/samples/TodoApp/TodoApp.Data/MVVM/TodoListViewModel.cs#L68).  It's a little more complicated than that, but that would be a good first approach.

Can you test that out and see if it solves your problem?  If it does, I can get that checked in pretty quickly (or you can do a PR); if not, then I'll delve into this on Friday.

**Comment by LKujala** [comment]
sure; I can muck around with that.

**Comment by LKujala** [comment]
Tested adding the check for IsRefreshing; this does resolve the issue.

**Comment by LKujala** [comment]
Note: the fix resolves the error condition, but does not address the quirky functionality of refreshing data every time the window gets focus. OnAppearing doesnt seem like the right trigger event for getting data.

**Comment by adrianhall** [comment]
Agreed - this was "the best I could do" given the constraints of supporting eight or nine different environments.   If I were building **just** a MAUI app, then I would go splash screen => login (with multiple providers) => rest of app - then I don't have to worry about the authentication.  However, there are environments where that doesn't work (most notably, app environments where there is no concept of a startup window and hook ins to lifecycle are completely different).

At the end of the day, this is a tutorial about integrating Azure Mobile Apps into various environments - not about writing the best MAUI code.
