### ISSUE TITLE
What happend to the File Management Repos

### ISSUE THREAD

**Issue by stefffdev** [Azure/azure-mobile-apps#46]
Until recently the repos 
([https://github.com/Azure/azure-mobile-apps-net-files-server])
and 
[(https://github.com/Azure/azure-mobile-apps-net-files-client)]
were available and contained a rough implementation of a file sync.

They are still linked under "misc" in 
[https://github.com/Azure/azure-mobile-apps/blob/master/README.md]

I couldn't find any comment our announcement regarding this.

**Comment by Quilll** [comment]
Was wondering the same???  Hoping that it has been incorporated somewhere else.

**Comment by stefffdev** [comment]
See [https://github.com/Azure/azure-mobile-apps-net-client/issues/318](https://github.com/Azure/azure-mobile-apps-net-client/issues/318)
