### ISSUE TITLE
MAUI Offline Sync push operation failed

### ISSUE THREAD

**Issue by LKujala** [Azure/azure-mobile-apps#460]
## Describe the bug

Exception: Push operation fail opening app, when app is closed with "unsaved" changes.

## To Reproduce

1. Run app and login (list of items shown with IsComplete set correctly)
2. Click on item to change IsComplete state
3. Alt+Tab to another app
4. Alt+Tab back
5. See error
6. restarting app shows error immediately

## Expected behavior

Exception handler should recover from error condition

## What platforms?

complete how to tutorial
https://docs.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/howto/data-sync

## Screenshots

![image](https://user-images.githubusercontent.com/98625461/186516861-bf285f17-d672-4930-9b1e-ea6af38f76c6.png)

## Additional context

the PushResult status is "precondition failed"; not sure what this actually means.

**Comment by LKujala** [comment]
Update: the "If-match" condition in http request shows an older version number for the requested record than what is shown in the data store. ... somehow changes were commited to the datastore but the offline store did not get updated with those changes (killing the app while debugging?)

no matter how the offline store became out of sync with data store; need to "recover" from this situation.
recommendation seems to be to pull data with If-Match="*"; not sure how to do that when making the call to
`_table = _client.GetOfflineTable<TodoItem>();`

alternative is in exception handler to purge local copy with
`IOfflineTable<T>.PurgeAsync`

is there another alternative approach?

**Comment by adrianhall** [comment]
So, let's talk about data sync :-)

When you change an offline table:
1) An entry for the change gets placed in the operations queue
2) The offline database gets updated

The version for the item has not yet changed.

When you push changes - for each entry in the operation queue, the appropriate method gets executed (DELETE, PUT, POST) with an If-Match: "<version>".  If the versions do not match, a 412 Precondition Failed is returned by the server, and that results in a ConflictException.  These are bundled up into a PushFailedException which you can trap when you are pushing.  Each error has the following methods:

* `CancelAndDiscardItemAsync()` cancels the operation and discards the item locally.
* `CancelAndUpdateItemAsync()` cancels the operation and stores the server version in the offline store.
* `UpdateOperationAsync()` updates the operation with the server version so it can be retried.

You can use these to handle sync errors.  Any non-trivial offline app will HAVE to handle synchronization errors - we don't do it in the sample TodoApp as it would add too much complexity.  However, see https://docs.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/howto/client/dotnet#synchronize-an-offline-table for an example on how to synchronize in an appropriate manner.

In the end, how you do conflict resolution is up to you.  You can "prefer server" or "prefer client" easily and programmatically. 

Does this answer the question?  If so, feel free to close the issue!

**Comment by LKujala** [comment]
Thank you for the detailed response and including the link.
One thing I liked about the .NET MAUI getting started articles for learning, is the progressive steps adding new functionality. (and I manage to breaks things along the way, which helps learning the architecture).
As a suggestion, why not add another article to the "getting started" section that incorporates your comments and demonstrates the different means of handling sync errors.

thanks again.

**Comment by adrianhall** [comment]
Love the idea!  If only there were more hours in the week :-)
