### ISSUE TITLE
DataSyncClient does not respect Uri value

### ISSUE THREAD

**Issue by mstaessen** [Azure/azure-mobile-apps#461]
## Describe the bug

DatasyncClient only keeps the Host of the configured Uri and strips away everything else.

In Development, I use Azure Relay/Hybrid Connections (through https://github.com/Azure/azure-relay-aspnetserver) to expose my locally running app on a public endpoint, because I cannot connect my mobile device to the same network as my workstation. 

As such, I configure the Uri for the DataSyncClient as https://[namespace].servicebus.windows.net/[hybrid-connection-name], but [hybrid-connection-name] gets removed in calls to the remote table. 

## To Reproduce

1. Install Azure Relay Hosting in the ASP.NET Core App.
2. Configure Azure Relay

```
builder.WebHost.UseAzureRelay(options =>
{
    options.UrlPrefixes.Add("[RelayConnectionString]");
});
```
3. Configure DatasyncClient

```
var client = new DatasyncClient("https://[namespace].servicebus.windows.net/[hybrid-connection-name]", options);
```

5. Pull remote table and watch the HTTP traffic

    [HTTP] >>> GET https://[namespace].servicebus.windows.net/tables/stores?$filter=(updatedAt gt cast(1970-01-01T00:00:00.000Z,Edm.DateTimeOffset))&$orderby=updatedAt&__includedeleted=true

## Expected behavior

I expect to see the full base-uri: https://[namespace].servicebus.windows.net/**[hybrid-connection-name]**/tables/stores?$filter=(updatedAt gt cast(1970-01-01T00:00:00.000Z,Edm.DateTimeOffset))&$orderby=updatedAt&__includedeleted=true

## What platforms?

* Client (.NET, JavaScript, iOS, Android): All, v5.0.11, tested on Windows and Android, on the actual devices

**Comment by adrianhall** [comment]
Thanks for the detailed report.  I did, indeed, deliberately strip away the path.  Workaround right now is to use the table name resolver in options to generate the path to the table - see https://docs.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/howto/client/dotnet#tableendpointresolver

**Comment by mstaessen** [comment]
That is indeed what I ended up doing, but it is not very user-friendly. :)

Just wanted to add that there is a multitude of scenarios where you could end up in this situation. For example, when hosting in virtual directories or when exposing the API through API Management.
