### ISSUE TITLE
Add delegate eventing for sync operations.

### ISSUE THREAD

**Issue by LKujala** [Azure/azure-mobile-apps#463]
**Is your feature request related to a problem? Please describe.**
When clicking on a row, there can be a 1s to 15s delay before the HTTP request is sent and the HTTP response is received.
There is no visual indicator that "something is happening" in the background; which gives the false impression that the app is not responding.

**Describe the solution you'd like**
In winforms, could use background worker process that allows the UI to show a "progress bar" or "activity indicator".
In WPF there is something similar. 
Need to use the MAUI equivalent for reporting on progress of background task.

For the actual UI would like to show two status:
* per changed record (new, modified, deleted): additional icon to indicate saved to local db, but not yet sync to remote
* per view model the view would have a status bar (or similar indicator) that shows state of background activity: { blank = nothing running, pending = local changes waiting, sync = http request sent }

**Describe alternatives you've considered**
* change cursor to "busy": works for windows, but not for tablets/phones that dont have cursor
* popup progress dialog: design is inconsistent with standard tablet/phone ui
* change page to show "sync in progress": design is often used in "update applets" (eg google play store, samsung galaxy store)

**Additional context**
I havent seen tablet/phone apps that show the status of background tasks; the apps generally crash out if something doent work (eg when sending mail fails because of connectivity, attachment size, or authentication problems I need to reboot my phone to clear the "send" error so I can fix it...). So the suggestion is based on how I would show status in a Windows UI. If MAUI has a different standard approach, I would like to see it.

StackOverflow has a few questions related to this... suggestions include:
* use ReportProgress like.. `async Task CallTaskAbc(aViewModel viewModel, IProgress<SyncStatus> progress)`
* use `Dispatcher.Dispatch(async() => await CallTaskAbc());`
* use Synchronization Context (which seems like a variation on Report Progress)

any other approaches to look at?

**Comment by adrianhall** [comment]
An interesting problem that can probably easily be solved by a few event models.

Let's say I introduce a "SyncEvents" delegate within the client.  The client would then fire an event (captured by your delegate) for "sync-start", "sync-end", "sent-entity", and "received-entity" - each one capturing some state (we know, for example, how many items are in the queue, so sent-entity can send the item# and the total # items).  Would that suffice?

**Comment by LKujala** [comment]
the "syncevents" approach is consistent with current task structure, so should deal with the sync process.
what about showing record status though? (local to remote in sync or not).

**Comment by LKujala** [comment]
could use the RefreshView to handle the visualization?

**Comment by adrianhall** [comment]
So, firstly, you can't tell if the local is in sync with the remote for any specific entity without fetching that entity (at which point it's in sync).  You can say whether you have a queued push waiting for a given entity (might be worth exposing this as a helper method).

For the RefreshView - do you mean adding a "sync" indicator to the samples?

**Comment by LKujala** [comment]
A - I agree, that once you have a pull then everything is in sync and no indicator is required.
where I notice the issue is a) on the initial pull (start the app and go into la la land until something shows up) and b) on the initial push (make a change and app goes into la la land until something shows up).... I notice this on initial test run; I expect the back end service "hibernates" after a period of inactivity and needs time to "wake up" when the first pull comes in.

B- the "queued" items waiting to push is what I am referring to by "pending". the local copy has been changed and is in the queue to be pushed. would like a visual indicator that something is queued.

C - according to docs, Refresh View combines two things: the command to start the refresh (eg use a swipe gesture instead of a button) and an activity indicator (the busy icon). The app as is, has the refresh button, so could add the activity indicator when any of the "sync events" are active. as you indicated, there a lots of changes coming through, hard to keep up with the firehose.

**Comment by adrianhall** [comment]
Got it.  The way I would do this is in the intermediate service - the RefreshView can bind to a bindable property that is true/false..  Then I bind to the state changes, setting the initial value to false.  When I trigger the refresh, it sets the value to true (on the UI thread so the binding picks it up), goes about the refresh, then sets it back to false in a "finally" block.  You don't need to have anything fancy or in SDK for handling that.

Another possibility is to trigger the refreshing bindable property change on the sync state change (i.e. delegate that receives the sync-started / sync-finished events).

Anyhow - the eventing is a good idea, and I'll work on it soon.

**Comment by adrianhall** [comment]
Added a SynchronizationProgress event handler - something like:

``` csharp
client.SynchronizationProgress += (sender, args) => 
{
   // args is SynchronizationEventArgs
};
```

The SynchronizationEventArgs class looks like this:

``` csharp
    public enum SynchronizationEventType
    {
        PushStarted,
        ItemWillBePushed,
        ItemWasPushed,
        PushFinished
    }

    public class SynchronizationEventArgs
    {
        public SynchronizationEventType EventType { get;  }
        public long QueueLength { get; }
        public string? TableName { get; }
        public string? ItemId { get; }
        public bool IsSuccessful { get; }
    }
```

When a push happens, you will get a PushStarted (with the queue length), then ItemWillBePushed / ItemWasPushed events either side of a single item, then finally a PushFinished.

**Comment by LKujala** [comment]
thanks for the changes.
the event stream (start, item updated, finish) should do the trick for keeping the UI "fresh".
