### ISSUE TITLE
Wrong TableOperation in ReadAsync method of class TableController<TEntity>

### ISSUE THREAD

**Issue by xzhu005** [Azure/azure-mobile-apps#468]
## Describe the bug

After reading the source code of the TableController.cs in [https://github.com/Azure/azure-mobile-apps/blob/122c585cd7221014b7186b707c15fbe7f66ce28a/sdk/dotnet/src/Microsoft.AspNetCore.Datasync/Tables/TableController.cs](url), I found a issue in the ReadAsync method. In line 402, we should pass TableOperation.Read instead of TableOperation.Delete to  the AuthorizeRequest method.

**Comment by adrianhall** [comment]
Actual placement: https://github.com/Azure/azure-mobile-apps/blob/main/sdk/dotnet/src/Microsoft.AspNetCore.Datasync/Tables/TableController.cs#L432 - completely correct - it's a bug.  Thanks for the report.
