### ISSUE TITLE
GenericAuthenticationProvider - System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by henda79** [Azure/azure-mobile-apps#470]
## Describe the bug

**System.ArgumentOutOfRangeException:** 'The added or subtracted value results in an un-representable DateTime.

This happens in the GenericAuthenticationProvider IsExpired method when the ExpiresOn property is not set and defaults to  
DateTimeOffset.MinValue which the subtract is then applied to resulting in the exception,

## To Reproduce

Just don't set AuthenticationToken.ExpiresOn

## Expected behavior

This is expected behaviour but maybe should be checked before the subtract.

**Comment by adrianhall** [comment]
The System.ArgumentOutOfRangeException is actually the right thing to be returning, but we are doing it in the wrong way - totally agree here.
