### ISSUE TITLE
Offline sync -- android sdk issue

### ISSUE THREAD

**Issue by Navpreet2289** [Azure/azure-mobile-apps#48]
for com.microsoft.azure:azure-mobile-android:3.2.0@aar
and for sever version 2.0.0

Offline sync is not working at all

**Comment by Navpreet2289** [comment]
even tried azure:azure-mobile-android:3.3.0 still not working

**Comment by ericbrunner** [comment]
@Navpreet2289 
1. Specify what Version of Azure.MobileService.Client you have installed. 3.3.0 or 3.2.0 is no available version
2. Post a code snippet what is not working
3. Describe a test case of what is not working

I utilize offline sync since it's availability and it is working for sure.

**Comment by elamalani** [comment]
@Navpreet2289 Can you share more details to investigate this issue like SDK version that you using in your app, code snippet, error details if you see any and repro steps?

Unless you have fixed it for your app, we need more information to help you. Thanks!

**Comment by elamalani** [comment]
@Navpreet2289 I'm closing this issue for now as we haven't heard back from you. But please feel to ask us questions related to Azure Mobile Apps.  Thanks!
