### ISSUE TITLE
Access to PendingOperations

### ISSUE THREAD

**Issue by stew978** [Azure/azure-mobile-apps#484]
**Is your feature request related to a problem? Please describe.**
In previous version of Azure Mobile Apps Client we had access to the the SyncContext and to the PendingOperations.
The SyncContext is now internal to the DatasyncClient, and it seems that the PendingOperations are not exposed.
I assume that the SyncContext being internal is for a good reason.

**Describe the solution you'd like**
Could it be possible to access to the SyncContext or to expose if there are any PendingOperations directly on the DatasyncClient?

**Comment by adrianhall** [comment]
I like the idea.

Would you prefer total pending operations, or pending operations per table, or both?

**Comment by stew978** [comment]
For my use case having total pending operations would be enough.
But I can imagine cases where having pending operations per table could be a nice to have.

Would you like me to try to create a PR for this issue?

**Comment by adrianhall** [comment]
I'm happy to take a PR, as long as it also contains tests!  Perhaps you can propose an API first?

**Comment by stew978** [comment]
You were faster than me.
Thank you
