### ISSUE TITLE
How to force pull of table, and dismiss pending operations

### ISSUE THREAD

**Issue by stew978** [Azure/azure-mobile-apps#494]
**Is your feature request related to a problem? Please describe.**
I'am using the DatasyncClient with offline tables.
I would wish that on Pull every tables having new datas would be pulled, and update the table datas.

**Describe the solution you'd like**
I would like to have on option to pass a collection of tables which would be Pull only.
On Pull we would retrieve datas from the server, so that the server version of the data is always the version of the data we want to be shared accross all device syncing the data.

**Comment by adrianhall** [comment]
Try:

```csharp
var tables = await store.GetTablesAsync();
foreach (var table in tables) {
  var ref = client.GetOfflineTable(table);
  await ref.PullItemsAsync();
}
```

You can, of course, do it in parallel.

```csharp
var tables = await store.GetTablesAsync();
var tasklist = new List<Task>();
foreach (var table in tables) {
  tasklist.Add(client.GetOfflineTable(table).PullItemsAsync());
}
await Task.WhenAll(tasklist);
```

I could do the same code in `client.PullItemsAsync(optional IEnumerable<string> of tables)`, but that prevents you from setting per-table options, which is generally a big deal in more complex applications with lots of tables.

Thoughts?  What are you missing?

**Comment by stew978** [comment]
Thank you, it's all good.

I've got everything needed to perform the pull operations.
