### ISSUE TITLE
Quickstart giving "The resource you are looking for has been removed, had its name changed, or is temporarily unavailble" error

### ISSUE THREAD

**Issue by scout208** [Azure/azure-mobile-apps#495]
## Describe the bug

Following one of the TodoApp sample quickstart guides works well up until after the publish step. Once the backend is published, going to `https://APPSERVICENAME.azurewebsites.net/tables/todoitem?ZUMO-API-VERSION=3.0.0` gives a blank page with just the text `The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.` instead of showing the empty JSON array like it shows in the tutorial.

## To Reproduce

1. Follow along with any of the TodoApp sample quickstarts up until Publish the service code - step 18
2. Go to `https://APPSERVICENAME.azurewebsites.net/tables/todoitem?ZUMO-API-VERSION=3.0.0` as step 18 suggests
3. Observe that the page shows `The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.`

## Expected behavior

Expected to get a page that looks like this

![image](https://user-images.githubusercontent.com/9426329/197033335-1ee27433-2af3-4c3c-a569-fccbc8110a00.png)

## What platforms?

* Server (ASP.NET Framework, ASP.NET Core, NodeJS): ASP.NET Core
  * Library versions? 5.0.11
  * What database are you using? SQL Server
  * Where are you running the server? Azure
  * GitHub repository containing the code (optional, but helps!)  https://github.com/Azure/azure-mobile-apps/tree/main/samples/TodoApp

## Screenshots

![image](https://user-images.githubusercontent.com/9426329/197033508-1e20c6f6-63f6-4381-b324-2febc2b9bb61.png)

**Comment by adrianhall** [comment]
This means your service is not running.  You need to follow normal Azure App Service debugging to ensure that the service is running.

Good point though - we don't provide any assistance in debugging.  I'll link out to the debugging section of Azure App Service documentation when I next update the docs.

**Comment by adrianhall** [comment]
To follow up - my belief is that you didn't click on the button to actually publish the site.  You probably set it up, but didn't do that final step.

**Comment by scout208** [comment]
@adrianhall You're totally right I just forgot to click "Publish". I was confused since my website was showing the default page correctly, I assumed it was already deployed. My mistake.
