### ISSUE TITLE
Deserialize complex SQLite queries result on offline database throw Newtonsoft.Json.JsonSerializationException

### ISSUE THREAD

**Issue by cbs-cbt** [Azure/azure-mobile-apps#499]
## Describe the bug

Using `ExecuteQueryAsync` on the offline database will return `IList<JObject>`.
Deserializing the returned `JObjects` generates a `Newtonsoft.Json.JsonSerializationException` exception for items that were created with the `DatasyncClient.GetOfflineTable<T>().InsertItemAsync(T item);`
Indeed, the creation of an item in the offline database defines the 3 columns `deleted`, `updatedAt` and `version` to NULL. This even if a value is defined for these fields before invoking `InsertItemAsync`

### 1. Insert a new item in the database invoking `InsertItemAsync`:
```
public async Task UpsertItemAsync<T>(T p_tData) where T : DatasyncClientData
{
  if (string.IsNullOrEmpty(p_tData.Id))
  {
    p_tData.UpdatedAt = DateTimeOffset.UtcNow;
    p_tData.Deleted = false;

    await m_dscData.GetOfflineTable<T>().InsertItemAsync(p_tData);
  }
  else
  {
    await m_dscData.GetOfflineTable<T>().ReplaceItemAsync(p_tData);
  }
}
```
Here is the result of this command in the database:
![image](https://user-images.githubusercontent.com/15328452/200651142-1cb9601d-1367-4135-95c9-5b593b3674af.png)

### 2. Execute `ExecuteQueryAsync` on the offline database
```
var l_strPolesTableName = m_dscData.GetOfflineTable<Pole>().TableName;

l_strQuery = $"SELECT {l_strPolesTableName}.* FROM {l_strPolesTableName} INNER JOIN {l_strSupportsTableName} ON {l_strPolesTableName}.SupportID={l_strSupportsTableName}.Id WHERE {l_strSupportsTableName}.CenterID=@CenterID AND (({l_strPolesTableName}.{nameof(DatasyncClientData.Deleted)}=0) OR ({l_strPolesTableName}.{nameof(DatasyncClientData.Deleted)} IS NULL))";

var l_arjPoles = await m_ossData.ExecuteQueryAsync(l_strPolesTableName, l_strQuery, l_dicCenterIDParameter);

var l_arpPoles = l_arjPoles.Select(X => X.ToObject<Pole>()).ToArray();
```

`X.ToObject<Pole>()` will throw the following exception:
```
Newtonsoft.Json.JsonSerializationException
  HResult=0x80131500
  Message=Error converting value {null} to type 'System.Boolean'. Path 'deleted'.
...
Inner Exception 1:
InvalidCastException: Null object cannot be converted to a value type.
```
## Expected behavior

There are two possibilities to solve this problem:
1. `deleted`, `updatedAt` and `version` columns should not contain NULL after calling `InsertItemAsync` on an offline database
2. It should be possible to use the `ServiceSerializer` to deserialize the objects obtained by `ExecuteQueryAsync` (set `DatasyncClient.Serilaizer` property as `public`)

... or both

## What platforms?

* Server ASP.NET Core:
  * Microsoft.AspNetCore.Datasync 5.0.12
  * Azure SQL database
  * API server runs on the development machine (`localhost`)

* Client (.NET, JavaScript, iOS, Android):
  * Xamarin.Forms 5.0.0.2515
  * Microsoft.Datasync.Client.SQLiteStore 5.0.12
  * SQLite for offline store
  * Windows 10 Home edition 21H2
  * It happens on a real device?

**Comment by adrianhall** [comment]
Thanks for the report - I'll take a look later this week.

**Comment by adrianhall** [comment]
I made the serializer public (in next release) - this means your select becomes the following:

```csharp
var l_arpPoles = l_arjPoles.Select(X => m_dscData.Serializer.Deserialize<Pole>(X)).ToArray();
```

**Comment by georg138** [comment]
Is there anything I need to take into account when using the `ServiceSerializer`? Because when trying to deserialize table data I'm getting the same exception from the converter as described in the first post because `deleted` etc. are `null`.

**Comment by adrianhall** [comment]
@georg138 - this was corrected over a year ago, so you should NOT be having problems unless you've done something else (e.g. adjusted the server side serialization).  Please open a new bug.
