### ISSUE TITLE
new tables cannot be created (todoapp) when there are already tables present. 

### ISSUE THREAD

**Issue by innomotionmedia** [Azure/azure-mobile-apps#515]
Hello,

this issue basically renderes the whoe todoapp useless. 

after creating a second table, you will be returned "500 internal server error" from azure. only if you delete the existing table (todoitem) are all the other tables created. so each time you have to create a new table, all old ones including their contents will have to be deleted. then you can run the middleware again and all tables are created. 

I am already in touch with the microsoft support on this, and I will just copy the content that THEY wrote back to me here for all the information: 
Hello Julius,

We have been able to investigate your issue further and we were also walking through the steps from [Build a .NET MAUI app with Azure Mobile Apps | Microsoft Learn](https://learn.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/quickstarts/maui/?pivots=vs2022-windows) . Instead of using the Mobile Client we have used the WPF client and we worked on a repro there.
(One note regarding Azure Mobile Apps / Microsoft DataSync Framework is not supported by us,  Microsoft Support Services. The only support for this is via its GitHub repo. See https://github.com/Azure/azure-mobile-apps/blob/main/SUPPORT.md)
 
We build the sample and we were able to successfully connect to the table that was generated by the code that was in the Github project.
 
As a next step we have created a second table by duplicating the parts of the code that was relevant for the creation of the database table and just changed the name for the table so that a new table was created. After doing so we could replicate the error message that you had
'internal server error' (500). We were not yet able at that point why this error was showing up.
 
We have then installed “Azure Data Studio” to be able to get a control to the Azure database:
[Download and install Azure Data Studio - Azure Data Studio | Microsoft Learn](https://learn.microsoft.com/en-us/sql/azure-data-studio/download-azure-data-studio?view=sql-server-ver16)
 

There were no logs available from here that could explain us why the ‘Internal Server Server’ was returned to the .NET Client.

After deleting the first table using this SQL Command:

The Tables could be created successfully.

In the AppContext.cs file there is the Database.EnsureCreatedAsync().ConfigureAwait(false), which is highlighted below
 
namespace CosmosTodoService.Db
{
    public class AppDbContext : DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
        {
        }
 
        /// <summary>
        /// The dataset for the TodoItems.
        /// </summary>
        public DbSet<TodoItem> TodoItems => Set<TodoItem>();
 
        /// <summary>
        /// Do any database initialization required.
        /// </summary>
        /// <returns>A task that completes when the database is initialized</returns>
        public async Task InitializeDatabaseAsync()
        {
            await this.Database.EnsureCreatedAsync().ConfigureAwait(false);
        }
 
It seems that this method is only called when there are no tables present and this is the one that is relevant for creating the tables. So deleting the table on the server end has caused the problem to be resolved.
 
After making this modifications we could see that new table that we have created the “CustomTodoItem” table, while the sample table “TodoItem” was also generated:
 
Table

Description automatically generated
 
So the reason for the “Internal Server Error (500)’ was that the second table was not present but we were trying to add a new column to the table.
 
As a first step to resolve the problem you might backup (in case you have data present) and delete the first table as well and let Visual Studio recreate the tables again.
 
We are currently also investigating a solution to recreate the tables without the need to delete the table. I will let you know about our results.

**Comment by adrianhall** [comment]
This is a standard Entity Framework Core problem (and not one with Azure Mobile Apps).  You need to research "Entity Framework Core Migrations), or just look here: https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli
