### ISSUE TITLE
cannot open azure app after latest updated today

### ISSUE THREAD

**Issue by lbowser18** [Azure/azure-mobile-apps#54]
I have an iphone 6, and before the update today, I was able to login with my fingerprint. Now, every time I try to open the app, it immediately closes.

**Comment by jwallra** [comment]
Hi @lbowser18, you're talking about the Azure *Portal* app.  This is the main repo for Azure Mobile Apps, the App Service offering for mobile backends.  We agree it's confusing 😅

You can open a ticket on the Azure Portal to get in touch with the team [here](https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/newsupportrequest).
