### ISSUE TITLE
No data query in IOfflineTable

### ISSUE THREAD

**Issue by michaelcoelsch** [Azure/azure-mobile-apps#541]
If using an **IOfflineTable**, i do not have the ".ToListAsync()" Method to query data in that table.
"GetAsyncItems()" gives no records. 

On **IRemoteTable** i have  the ".ToListAsync()" Method and can query the table.

How can i query data properly from an **IOfflineTable** in Azure Mobile Apps??
Could you show any sample code?

Thanks

**Comment by michaelcoelsch** [comment]
Found the solution.

I had to add _System.Linq.Async_ from Nuget.
That gave me "ToListAsync<>()" on the **IOfflineTable**

Overseen this in the documentation.

**Comment by adrianhall** [comment]
Glad it was fixed easily!
