### ISSUE TITLE
Net Standard 2 reference broke IIS

### ISSUE THREAD

**Issue by michaelwda** [Azure/azure-mobile-apps#56]
I have a PCL that I updated to NetStandard 2. It's referenced in my .NET mobile app service project. Nothing fancy, just some shared models and a reference to sqlite-pcl for some field attributes.
This app also uses custom auth with the token store.

When deployed I started getting 500 internal server errors. Removing the NetStandard reference and just making a copy of the model classes into the project works.

**Module**: DynamicModule_Microsoft.Owin.Host.SystemWeb.OwinHttpModule, Microsoft.Owin.Host.SystemWeb, Version=3.1.0.0
**Notification**: PreExecuteRequestHandler
**Handler**: ExtensionlessUrlHandler-Integrated-4.0
**Error Code**: 0x00000000
**Requested URL**: https://xxxxxxxxx:80/.auth/login/mycustomauth
**Message**: This error means that there was a problem while processing the request. The request was received by the Web server, but during processing a fatal error occurred, causing the 500 error. 

Definitely seems related to something with the custom auth. I had updated to netstandard because I share the models between my xamarin app and the api project.

**Comment by dhei** [comment]
@michaelwda We don't support .NET standard 2.0 in the Azure Mobile Apps SDK. We are not actively developing in the SDK, please see [Future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps#future-of-azure-mobile-apps). I will close the issue for now but feel free to contact us if you have any questions.
