### ISSUE TITLE
Mobile apps

### ISSUE THREAD

**Issue by maristhek** [Azure/azure-mobile-apps#57]
Nothing on the Azure portal looks like what's shown on this tutorial.

Nothing.

**Comment by achocron** [comment]
Sorry, would you please post the images directly to the GitHub site, they don't appear properly here. Thanks.

**Comment by maristhek** [comment]
What I was trying to show was that the image shown in the tutorial the right-hand pane of the portal has a bunch of controls for filtering etc.

When I log into the portal with my credentials and select Create Resource the subsequent right-hand pane is completely blank.  This happens on all browsers.

**Comment by maristhek** [comment]
Following your instructions this is what I see
[cid:image001.png@01D4A828.9D387C70]

**Comment by achocron** [comment]
I unfortunately can't see the image you posted. If you drag it into the text box in the GitHub issue directly on the website, it should be uploaded properly.

**Comment by maristhek** [comment]
This is weird.  I can't seem to drag files nor copy pix into this text box.

Bottom line : the right-hand pane title bar shows "Everything" as title.
Search textbox with mobile apps int the text area.  Three dropdowns with Pricing, Operating System and Publisher titles respectively.  All dropdowns content is "All",
And the text "No results found." on the next text entry in the panel.

**Comment by clpolet** [comment]
Closing this issue until we have a clear scenario to reproduce it.
