### ISSUE TITLE
PushItemsAsync bug ?

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps#571]
### Discussed in https://github.com/Azure/azure-mobile-apps/discussions/570

<div type='discussions-op-text'>

<sup>Originally posted by **henda79** January 16, 2023</sup>
I have noticed an issue when trying to push a single table, but I'm not sure if its a bug or intended,

At the moment I have a single record in the _errors table for table A, now if I try to push table B I get an error which seems odd because the pushing of table B worked fine. It returns the error due to the previous error of table A now stored in the __errors table.

It is this code here in the PushItemsAsync method. It just gets all records from the __errors table and reports the problem.

Surely it should just get errors from the table I am trying to push ?

```
            List<TableOperationError> errors = new();
            PushStatus batchStatus = batch.AbortReason ?? PushStatus.Complete;
            try
            {
                errors.AddRange(await batch.LoadErrorsAsync(cancellationToken).ConfigureAwait(false));
            }
            catch (Exception ex)
            {
                batch.OtherErrors.Add(new OfflineStoreException("Failed to read errors from the local store.", ex));
            }
            SendPushFinishedEvent(batchStatus != PushStatus.Complete);

            // If the push did not complete successfully, then throw a PushFailedException.
            if (batchStatus != PushStatus.Complete || batch.HasErrors(errors))
            {
                List<TableOperationError> unhandledErrors = errors.Where(error => !error.Handled).ToList();
                Exception innerException = batch.OtherErrors.Count > 0 ? new AggregateException(batch.OtherErrors) : null;
                throw new PushFailedException(new PushCompletionResult(unhandledErrors, batchStatus), innerException);
            }
```</div>

**Comment by adrianhall** [comment]
Converting to issue.

I believe that the following is the minimal set of work:

1. Add methods for handling errors on the store:
    * `GetErrorsAsync()`
    * `DeleteErrorAsync()`
    * `ClearErrorsAsync()`
1. The `batch.HasErrors(errors)` should only return true if the current push created an error.  This probably means:
    * When doing a push, start by generating a PushCorrelationId (just a GUID)
    * Each error that is generated is tagged with the PushCorrelationId
    * When we LoadErrorsAsync(), we only load errors with the same PushCorrelationId

**Comment by henda79** [comment]
I thought when we did a push if there was an error we just handled it via the PushFailedException and then use the methods on TableOperationError.

I suppose I'm kind of confused on how errors / conflicts are handled correctly as this feels like 2 different things.

**Comment by adrianhall** [comment]
That's correct.  Those will result in the errors being removed.  However, you can (with the current code) ignore an error (don't call any of those methods) and the error will then linger, with no way of processing it.  Your 500 error is a classic example of that - it's not a conflict, so it sits in the errors queue without a way to remove it.

**Comment by henda79** [comment]
and it also stops the pushing anymore data for that table as it just returns the cached error.

**Comment by adrianhall** [comment]
Thinking more on this, I should just delete any "unhandled errors" after they are compiled into the PushFailedException (which is a composite error), with a push option that allows them to remain around (along with the three methods mentioned).

**Comment by henda79** [comment]
Whatever you think best Adrian, I don't really have a preference on this, just need a way to be able to re-sync in the case of a server error which is then fixed (server side). as in its current state, its just returns that cached error.

**Comment by josuuribe** [comment]
When i was using the SDK, I thought that methods like _CancelAndDiscardItemAsync
CancelAndUpdateItemAsync_ will also removed all relevant information, like pending queue item, errors, etc…
In other side i think there should be always a way for _remove all_ that includes all tables anda data, sthg like _the final purge_ :)

**Comment by adrianhall** [comment]
I've made two minimal changes in #581:

1. When the store is initialized, all errors are cleared.
2. When a sync is finished, all non-conflict errors are cleared.

This should sort out the issues that were reported.  If there are more conditions when errors cause problems, let me know via a new bug and I'll fix the situation.
