### ISSUE TITLE
Using AppCenter.Start() with OfflineSQLiteStore in Maui iOS causes SQLite MISUSE and throws "Unable to configure sqlite3 for URI connection strings."

### ISSUE THREAD

**Issue by ryanlpoconnell** [Azure/azure-mobile-apps#573]
### **Description**

Using `AppCenter.Start()` with `OfflineSQLiteStore()` in Maui iOS causes SQLite MISUSE and throws "Unable to configure sqlite3 for URI connection strings.".

The following line of code will fail for Maui iOS if `AppCenter.Start()` is called during startup (But works as expected with Maui Android)...
`var store = new OfflineSQLiteStore(connectionString);`

To clarify using OfflineSQLiteStore from Microsoft.Datasync.Client.SQLiteStore works for Maui iOS using simplified example code from ...
https://learn.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/quickstarts/maui/offline?pivots=vs2022-mac 
... until using this line in App.xaml.cs > OnStart()
`Microsoft.AppCenter.AppCenter.Start("ios=appid;android=appid",typeof(Microsoft.AppCenter.Analytics.Analytics), typeof(Microsoft.AppCenter.Crashes.Crashes));`

Exception.Message = "Unable to configure sqlite3 for URI connection strings."
Exception.Source. ="Microsoft.Datasync.Client.SQLiteStore"

**NOTE**: I believe the message re URI is a red herring due to the way any non-success result is handled in SQLiteConnection 
```
if (raw.sqlite3_config (17, 1) != 0) {
      throw new SQLiteException ("Unable to configure sqlite3 for URI connection strings.");
}
```

Developer is only able to determine sqlite misuse error response RE Application output (see repro steps)

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Use provided zip example Maui project
[MauiAppCenterSqliteMisuse.zip](https://github.com/microsoft/appcenter-sdk-dotnet/files/10481004/MauiAppCenterSqliteMisuse.zip)
2. Select Debug > iPhone Simulator (to produce in Maui iOS)
3. Run the example App and click the button called **Initialise Sqlite** (see screenshot below)
4. Note Sqlite failure in Application Output: "2023-01-23 14:56:01.770644+0000 MauiAppCenterSqlite[11274:199190] [logging] misuse at line 179186 of [554764a6e7]"
5. Example App catches exception to display ex.Message "Unable to configure sqlite3 for URI connection strings."
6. To prove `Microsoft.AppCenter.AppCenter.Start` is contributing to this issue, comment the line of code in App.xaml.cs > OnStart() > Line 19 and repeat steps 1-5

### **Details**

1. Using Microsoft.AppCenter SDKs version 5.0.1
2. Using Microsoft.Datasync.Client.SQLiteStore SDK version 5.0.20
3. iOS 16.2 (iPhone 14 Pro Max)
4. XCode 14.2

### **Screenshot**
![Simulator Screen Shot - iPhone 14 Pro Max - 2023-01-23 at 15 04 46](https://user-images.githubusercontent.com/18209358/214076843-4bec6393-ac77-4ecc-8937-fd2b63e9c885.png)

**Comment by adrianhall** [comment]
What you've got is two libraries trying to do offline with the same library at the same time.  They aren't going to work.  You need to pick one.

Will leave this open for a discussion, but this is not going to be actioned.

**Comment by adrianhall** [comment]
I have no insight into what AppCenter is or is not doing.  

You are welcome, as always, to fork the library and produce your own OfflineSQLiteStore component that uses the precise SQLite library that AppCenter (or your own app) uses and to rig things so that only one of them does the configuration (and the other skips it).

**Comment by ryanlpoconnell** [comment]
Both libraries which are both provided by Microsoft offer two very fundamental Mobile App features.

Wouldn't it be madness if they didn't work together out of the box (anymore)?

This would surely affect thousands of developers who previously didn't need to fork underlying libraries to make the Microsoft components work together on Xamarin.  We're not talking about some obscure 3rd party library. 

I don't mean to sound rude but I feel like I'm in the twilight zone atm.

**Comment by adrianhall** [comment]
Azure Mobile Apps is an open-source project which is carried on via a labor of love by those that worked on it for many years.  It does not have "official support". (i.e. you can't call up Microsoft and expect any sort of official support).  We do the best we can to ensure that customers who are using it can continue to use it.  We support on a best effort basis.

As part of that support, we ensure (a) that the product works with each and every platform that we test on (and we provide the platforms that we test on), (b) we release to NuGet on a regular basis, and (c) you have the source code in a form that can be easily compiled for your own use if you run into compatibility problems.

**Comment by ideas2appsaustralia** [comment]
I’ve got this error as well but do not use app centreThis only happens the first time I start the simulator. If I stop the app then restart app this error then doesn’t occur. I am concerned this will happen on first installation Still can’t see cause of error though in my case as if database doesn’t exist it should just be created Regards ScottOn 27 Jan 2023, at 4:42 am, Ryan OConnell ***@***.***> wrote:﻿
Both libraries which are both provided by Microsoft offer two very fundamental Mobile App features.
Wouldn't it be madness if they didn't work together out of the box (anymore)?
This would surely affect thousands of developers who previously didn't need to fork underlying libraries to make the Microsoft components work together on Xamarin.  We're not talking about some obscure 3rd party library.
I don't mean to sound rude but I feel like I'm in the twilight zone atm.

**Comment by adrianhall** [comment]
Since it's outside of AppCenter, please open a new issue with all the details of your setup.

**Comment by Arslan007** [comment]
@adrianhall I am facing same issue in our project. I know this issue is closed here but can I get some directions from you where to look first to avoid these Sqlite conflicts when using both libs and wanted to use both because both are equally important for my project. One is for Sync and other for Crash tracking. 

Any pointer will be helpful. Thanks

**Comment by adrianhall** [comment]
The answer is (a) ensure that the version of SQLite being used is the same, and (b) initialize once.

Unfortunately, that is inevitably custom code and a fork of one of the libraries.

**Comment by blackeyedyl** [comment]
@adrianhall not sure if you had a chance to check the mention above from @DmitriyKirakosyan 

> @ryanlpoconnell @Arslan007 after looking into it, here is what I found
> 
> `raw.sqlite3_config(raw.SQLITE_CONFIG_URI, 1)` returns `(21) SQLITE_MISUSE` (see https://sqlite.org/rescode.html).
> 
> `OfflineSQLiteStore` [throws exeption](https://github.com/Azure/azure-mobile-apps/blob/14fc881b8c89bbcc2de6b703bfca986009398698/sdk/dotnet/src/Microsoft.Datasync.Client.SQLiteStore/Driver/SqliteConnection.cs#L47) if setting `raw.SQLITE_CONFIG_URI` doesn't return `SQLITE_OK`. I believe this behaviour can be improved avoiding throwing, as it is done in app center sdk.
> 
> The reason why `SQLITE_MISUSE` is returned is because the AppCenter SDK already set this flag. See [MSACDBStorage.m#L542](https://github.com/microsoft/appcenter-sdk-apple/blob/baa9fe188859a23a1755f8fee65b228337cb11e5/AppCenter/AppCenter/Internals/Storage/MSACDBStorage.m#L542). However sdk doesn't throw if setting the flag fails. See [MSACDBStorage.m#L41](https://github.com/microsoft/appcenter-sdk-apple/blob/baa9fe188859a23a1755f8fee65b228337cb11e5/AppCenter/AppCenter/Internals/Storage/MSACDBStorage.m#L41).
> 
> So, there is nothing AppCenter SDK can do to solve this issue. It should be fixed on the [azure-mobile-apps](https://github.com/Azure/azure-mobile-apps) side.
> 
> #### WORKAROUND
> Initialize `OfflineSQLiteStore` first, then call `AppCenter.Start`. This way `OfflineSQLiteStore` will set the flag successfully, then AppCenter SDK will fail setting the flag but won't crash. After that, you will be OK using both libs.

Based on his findings would it be possible to reopen this issue and apply the recommended fix based on how the AppCenter team is handling the SQLite connection?
