### ISSUE TITLE
DeltaTokens all have 000 for the milliseconds components

### ISSUE THREAD

**Issue by hgjunip** [Azure/azure-mobile-apps#574]
## Describe the bug

When saving the updatedAt DateTimeOffset as the delta token in the `__config` table all tokens always end in 000 (milliseconds get lost). These leads to incremental syncs that pull more data than what might be needed. 

## To Reproduce

1. In the Todo Maui app sample. Create an item and refresh items.
2. Open the local database and check the delta token (it will end in 000)
3. Repeat steps 1 and 2 more times to verify milliseconds are always 0

## Expected behavior

The milliseconds component of the updatedAt should be saved correctly to the __config table.

## What platforms?

I checked this on the TodoSample Maui app using version 5.0.17 on both client and server.

## Additional context

This test fails if the milliseconds component is not 0:
https://github.com/Azure/azure-mobile-apps/blob/0aeb786a9b74622010a2d7dd3b991472b3a09237/sdk/dotnet/test/Microsoft.Datasync.Client.Test/Serialization/ServiceSerializer.Test.cs#L99-L106

I believe the problem is:
https://github.com/Azure/azure-mobile-apps/blob/0aeb786a9b74622010a2d7dd3b991472b3a09237/sdk/dotnet/src/Microsoft.Datasync.Client/Serialization/ServiceSerializer.cs#L159
The JToken has a type of date and the format it uses to convert to string doesn't include the milliseconds. I could create a PR to something like (with proper checks): 
`item.SelectToken(SystemProperties.JsonUpdatedAtProperty)?.ToObject<DateTimeOffset>();`
Which does make the test pass in my machine even with milliseconds not being 0.

**Comment by adrianhall** [comment]
Great catch.  

To do:
* [ ] Add a duplicate test that has a "ms" which isn't zero.
* [ ] Correct the inevitable error
* [ ] Add tests to check that the __config table in SQLite stores the ms correctly.
* [ ] Correct any follow-on errors

However, I don't think your suggested fix actually fixes the problem.  I'll have to add additional tests to check that the storage of DateTimeOffset values with a ms component is actually correct.
