### ISSUE TITLE
Remote debugging using Visual Studio 2019

### ISSUE THREAD

**Issue by sameertotey** [Azure/azure-mobile-apps#58]
Currently I can only debug mobile apps using either VS 2015 or VS 2017.  When will VS 2019 be supported.  I can remote debug WebApi apps in Azure using VS 2019.

**Comment by elamalani** [comment]
@sameertotey We are not doing active development in this product. Please read this section in the ReadMe file on the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps#future-of-azure-mobile-apps). Unfortunately, we dont plan to fix remote debugging in VS 2019.

**Comment by sameertotey** [comment]
I guess we will migrate our app to Azure Web Api app to use VS 2019.
