### ISSUE TITLE
Cannot connect database to my App service

### ISSUE THREAD

**Issue by DeveloperBeginner** [Azure/azure-mobile-apps#59]
I am trying to  add a cloud-based backend service to an Android mobile app by using an Azure mobile app backend. I am following the below link:
https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-android-get-started

 I already have created a database. While I try to configure the server project, I am not able to connect the database to my app service. It shows me the message "Click here to learn how to create a database". I have added the connection string in the Configure section of the App service, yet the connection is not showing up.

**Comment by jwallra** [comment]
Hi @DeveloperBeginner - Have you created a table in your database yet?  If you've created a table, when you visit the Configuration section of your App, you should see a connection string filled out:

![image](https://user-images.githubusercontent.com/13154238/56251292-e4522f00-6067-11e9-84df-cec58ea8d73b.png)

If the guided configuration doesn't work, you can find your connection string for your DB in your azure subscription here:

![image](https://user-images.githubusercontent.com/13154238/56251474-97228d00-6068-11e9-88c0-ef6a55283f3d.png)

Replace {your_username} and {your_password} in the sample string with the user name and password you created for your database.  Then add the connection string to your Mobile App and download the Quickstart for your appliction.

**NOTE: Don't share your connection string here!  It has your username and password in it, so it should be treated as a secret!**

Let me know if you have any other questions!

**Comment by DeveloperBeginner** [comment]
Hi @jwallra, Thanks for your response. I have already created tables in the DB as you can see below.

![tables](https://user-images.githubusercontent.com/6328246/56266616-46fc0700-610a-11e9-8063-bddbe5de5e6c.PNG)
But I was not able to see the connection string in the Configuration section of the app section. So I manually added it myself, 

![connection_string](https://user-images.githubusercontent.com/6328246/56266976-2b453080-610b-11e9-9925-6f5a31349145.PNG)

yet I am not able to connect to the database. Following is the screen shot.

![app_quickstart](https://user-images.githubusercontent.com/6328246/56267108-7fe8ab80-610b-11e9-8fe3-101a639cd0c0.PNG)

You can notice in the above screen shot that it mentions "You already have a TodoItem Table" when I do not have any such table. Also it is not providing me an option to create/connect a database.

**Comment by jwallra** [comment]
I suspect that since you connected the database manually, the UI isn't behaving as it should.  Check the "Easy Tables" section for your App Service and see if there is a table named "TodoItem" there.  That's what needs to be present for the quickstart to work.

Once you've verified that, try downloading the quickstart and see if it works.  

Sorry about the bad UI experience.

**Comment by DeveloperBeginner** [comment]
Even before I connected the database manually I was seeing the same UI. In fact I had to connect the database manually because I was not seeing the UI as mentioned in the docs. 
I checked the "Easy Tables" section and found the "TodoItem" table to be present there. I also downloaded the quickstart and found it to be working. 
When I add more tables in the "Easy Tables" section and download the quickstart, it does not seem to be reflected in the app (I do not find the created tables in the app). Could you please tell me how do I connect an SQL database created by me and download a quickstart Android app for the same?

**Comment by jwallra** [comment]
Glad I could help!  Yes, you can set up foreign key references between your tables.
