### ISSUE TITLE
Improve SynchronizationEventArgs

### ISSUE THREAD

**Issue by Jan-NET** [Azure/azure-mobile-apps#593]
### Discussed in https://github.com/Azure/azure-mobile-apps/discussions/589

<div type='discussions-op-text'>

<sup>Originally posted by **Jan-NET** February  6, 2023</sup>
If I log the synchronization events according to the documentation (https://learn.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/howto/client/dotnet#advanced-topics), I get these logs for syncing one item based on `SynchronizationEventArgs`:

```
09:47:49:230	[0:] [SYNC] <-> todoitem, PullStarted, ItemsProcessed -1, Success False
09:47:50:819	[0:] [SYNC] <-> todoitem, ItemWillBeStored, ItemsProcessed 0, Success False
09:47:50:828	[0:] [SYNC] <-> todoitem, ItemWasStored, ItemsProcessed 1, Success False
09:47:50:858	[0:] [SYNC] <-> todoitem, PullFinished, ItemsProcessed 1, Success False
```

`IsSuccessful` in `SynchronizationEventArgs` is declared as a result for a push event only.
All non-push event types output confusing states of success, see `Success False` in alle lines above. </div>

**Proposal**
Enhance `IsSuccessful` for the correct state of success for the related action. (But as far as I can see currently `UpsertAsync `or `DeleteAsync` does not return any success state!)

**Comment by adrianhall** [comment]
Maybe switch to a BaseEventArgs with specific entities for Pre, Post, Start, and Stop, with a ToString() and ToJsonString() for logging.

**Comment by adrianhall** [comment]
What I've done is made the `bool IsSuccessful` => `bool? IsSuccessful`.  I've updated the calls so that the IsSuccessful is null where it isn't known, then true/false when it is known.  This is a breaking change, but we're doing a 5.1.0 next, so a breaking change is ok.
