### ISSUE TITLE
Transient dependency to Xamarin.AndroidX.Browser (>= 1.4.0.2) creates incompatibility with latest Xamarin.Forms

### ISSUE THREAD

**Issue by amertlich** [Azure/azure-mobile-apps#599]
## Describe the bug

The 5.0.21 SDK requires Xamarin.AndroidX.Browser (>= 1.4.0.2) but the latest Xamarin.Forms is narrowly constrained to Xamarin.AndroidX.Browser (>= 1.3.0.6 && < 1.4.0).

This causes build issues in projects referencing both Xamarin.Forms and Microsoft.Datasync.Client

## To Reproduce

Create an Android project using Xamarin.Forms 5.0.0.2545 (latest) and Microsoft.Datasync.Client 5.0.21 (latest). Build project.

## Expected behavior

Xamarin.Forms should still be supported, without having to use a MSBuild NoWarn packagereference attribute.

**Comment by adrianhall** [comment]
I think I can downgrade Xamarin.AndroidX.Browser to 1.4.0.2 - I'll look into it.
