### ISSUE TITLE
No actual quickstart for Mobile Apps

### ISSUE THREAD

**Issue by Rhywden** [Azure/azure-mobile-apps#60]
Once again, your reworking of everything leaves the documentation behind.

I followed everything to the letter but there's no "Xamarin.Forms" available for download under Quickstart (in fact, there are NO (zip, zilch, nada, niente) client quickstarts available), I'm only seeing PHP, Node.js and other assorted backend server quickstarts.

**Comment by russelarms** [comment]
Hello, @Rhywden.

There is a link to download quickstart app in the documentation:
https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-xamarin-forms-get-started

It could be downloaded from
https://github.com/Azure/azure-mobile-apps-quickstarts/tree/master/client/xamarin.forms

**Comment by Rhywden** [comment]
Yes. But my issue is that the documentation **also** states that you can download a quickstart through the Azure Portal as well.

Also, it would be great if the documentation would, instead of always relying on quickstarts and similar stuff, point to how to integrate mobile apps into an _existing_ application.

Because when you download the quickstart you then have to hunt for all references to Mobile Apps and pray that you didn't miss anything. Basically, what's missing is a "Fundamentals" - i.e. the bare minimum of code you need to get up and running and where/when to put it.

**Comment by russelarms** [comment]
> Yes. But my issue is that the documentation also states that you can download a quickstart through the Azure Portal as well.

Could you please share a link where it could be found? We might have missed something.

> Because when you download the quickstart you then have to hunt for all references to Mobile Apps and pray that you didn't miss anything. Basically, what's missing is a "Fundamentals" - i.e. the bare minimum of code you need to get up and running and where/when to put it.

@Rhywden have you checked this doc?
https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-dotnet-how-to-use-client-library

**Comment by MatkovIvan** [comment]
Hi, we haven't heard from you in a while so I'm closing this issue. Please reopen/comment if you have more questions or run into this again.
