### ISSUE TITLE
Improve initial `PullItemsAsync` for empty local table (IncludeDeleted = false)

### ISSUE THREAD

**Issue by Jan-NET** [Azure/azure-mobile-apps#601]
**Proposal**
If a local table is empty, the next pull is an initial pull. In this case I don't think there is a need to pull down the soft deleted records from the backend. So, the `{ ODataOptions.IncludeDeleted, "true" }` could send with `false`.
If a soft deleted record will be reactivated (in the backend) it will be pulled in the next sync due to a refreshed `UpdatedAt`.

**Con**
The consistency of complex business objects spread across multiple tables is at risk. 

**Request**
Expand `PullOptions `with e.g. `NoDeletedForInitialPull `for case-by-case use.

**Additional context**
See #575 for performance issue discussion.

**Comment by adrianhall** [comment]
The `GetDeltaTokenAsync` method returns `DateTimeOffset.FromUnixTimeMilliseconds(0L)` if the delta token does not exist.  We use this fact to adjust the search - the updatedAt is not checked (everything is pulled) and the __includeDeleted is not set in this case.  In all other cases, the full incremental sync query is used.

**Comment by Jan-NET** [comment]
Very good! Better than my empty table approach, cause local inserts do not “disturb” your optimization!
