### ISSUE TITLE
Throw SQLiteException when connect to SQLite offline database

### ISSUE THREAD

**Issue by pgdiamond123** [Azure/azure-mobile-apps#606]
Currently, I'm using **Microsoft.Datasync.Client** and **Microsoft.Datasync.Client.SQLiteStore** version **5.0.21**.

But when I connect to SQLite offline database with connection string:
file://localhost/data/user/0/uk.co.hydrajaws.tester.android/files/Hydrajaws.db?mode=rwc

It throws an exception: 
Microsoft.Datasync.Client.SQLiteStore.SQLiteException: Unable to open database connection to '{connectionString}'

And I changed connection string is "file://data/user/0/uk.co.hydrajaws.tester.android/files/Hydrajaws.db?mode=rwc", it doesn't work.

**Implementation:**
var store = new OfflineSQLiteStore(ConnectionString); **-> throw exception**
store.DefineTable<Client>();

![image](https://user-images.githubusercontent.com/22570017/218056843-4b285476-2de6-453a-907f-9dd49e561b40.png)

But I checked with the Todo sample project, it works well.

Please kindly help to check my issue. Thank you so much.

**Comment by adrianhall** [comment]
No way I can diagnose without the error code, which is a problem since we don't supply it.

I'll add the rc to the error message, then you can re-try on the next version and, assuming the error code doesn't give you the information you need, you can re-try.

**Comment by adrianhall** [comment]
Note that you can check the SQLiteException that is thrown when this happens - it has the message (SqliteMessage) in it.

**Comment by CelloLiu** [comment]
I got the similar issue here and the following is the SQLiteException exception. I'm using .net maui with blazor hybrid based on .net 8 here.
{Microsoft.Datasync.Client.SQLiteStore.SQLiteException: Unable to open database connection to 'file://localhost/data/user/0/com.y_social.android/files/UserTasks.db3?mode=rwc': 14 unable to open database file
   at Microsoft.Datasync.Client.SQLiteStore.Driver.SqliteConnection..ctor(String connectionString) in D:\a\_work\1\s\sdk\dotnet\src\Microsoft.Datasync.Client.SQLiteStore\Driver\SqliteConnection.cs:line 64
   at Microsoft.Datasync.Client.SQLiteStore.OfflineSQLiteStore..ctor(String connectionString) in D:\a\_work\1\s\sdk\dotnet\src\Microsoft.Datasync.Client.SQLiteStore\OfflineSQLiteStore.cs:line 57}

**Comment by madhugilla** [comment]
we are running into the same issue as @CelloLiu , any update on this @adrianhall  ?

**Comment by adrianhall** [comment]
You guys need to open a separate issue.  There is no "update" because there is nothing to be done here.

As mentioned, I can't diagnose that since it has something to do with your environment and what else is going on.   Error 14 is generic and could be anything from "I don't have access to the location specified" to "The file is locked by something else so I can't open it"
