### ISSUE TITLE
When will Azure AD B2C be a supported auth host?

### ISSUE THREAD

**Issue by jjgriff93** [Azure/azure-mobile-apps#61]

**Comment by elamalani** [comment]
@jjgriff93 Hi there, we are not doing active development in Azure Mobile Apps. Please refer to this [Readme](https://github.com/Azure/azure-mobile-apps#future-of-azure-mobile-apps) section. 

[App Center](appcenter.ms) is the next generation solution for Azure Mobile Apps and it supports [Auth service](https://docs.microsoft.com/en-us/appcenter/auth/) which is built on top of Azure AD B2C. You can easily onboard to App Center Auth service for mobile apps. Check out the [roadmap](https://github.com/Microsoft/appcenter/wiki/Roadmap#auth) for App Center Auth. Let me know if you have any other questions. Thanks!
