### ISSUE TITLE
DataSync does not support .net 7

### ISSUE THREAD

**Issue by ikeoriaku123** [Azure/azure-mobile-apps#615]
## Describe the bug
Hello, I downloaded the nuget for this sdk in my .net maui project targeting .net 7. It errors when I build the project with incompatibility issue. I noticed this only supports .net 6. How do I use this package for .net maui project targeting .net 7 and when is this going to be supported. Thank you.

## To Reproduce

1. Install the nuget package Microsoft.Datasync.Client.SQLiteStore
2. After installing, build the project
3. Build fails

**Comment by adrianhall** [comment]
What target were you using for MAUI? (iOS / Android / WinUI?)

**Comment by ikeoriaku123** [comment]
Using both ios and android

**Comment by ikeoriaku123** [comment]
You mean package version 5.1.1?

**Comment by adrianhall** [comment]
Yep - I'm going to target the next minor release for the fix.

**Comment by adrianhall** [comment]
Cannot reproduce this.  Specifically, I created a new .NET 7 based MAUI project and added the 5.1.0 versions of Microsoft.Datasync.Client and Microsoft.Datasync.Client.SQLIteStore to the project, swapped in all the code necessary to build the simple Todo app, and it built and works fine.

I'll check in the sample so you can try it out, but I'm going to need more information to figure out why it's not building.  A build trace would help immensely here.

**Comment by KrichAyyoub** [comment]
Hello Adrian,

I have same issue, unable to open database connection to 'file://'

I'm currently using DataSync.Client 5.1.2 + DataSync.Client.SQLiteStore 5.1.2

MAUI project targeting .net 7

SyncService same as ToDoService inside the sample ToDoApp project

SyncService is inside à library project targeting .NET 7 and using DI as a singleton inside MAUI project.
