### ISSUE TITLE
OfflineStore SQLite Query Monitoring

### ISSUE THREAD

**Issue by oliverw** [Azure/azure-mobile-apps#616]
**Is your feature request related to a problem? Please describe.**
There is currently no way of monitoring the SQL queries run against the SQLite Offline Store DB

**Describe the solution you'd like**
It would be helpful to have some kind of extension point at the client and/or table level to hook into the executed queries.

**Comment by adrianhall** [comment]
In 5.1.1, you'll be able to set an `ILogger` on the `OfflineSQLiteStore` object:

```csharp
store.Logger = <implementation-of-logger>;
```

You can also pass it as a parameter to the constructor:

```csharp
var store = new OfflineSQLiteStore(connectionString, logger);
```

All the logs are generated at the Debug level.

**Comment by oliverw** [comment]
> In 5.1.1, you'll be able to set an `ILogger` on the `OfflineSQLiteStore` object:

Awesome!

**Comment by oliverw** [comment]
Works great by the way 👍
