### ISSUE TITLE
Sample Source Confirmation

### ISSUE THREAD

**Issue by yourera** [Azure/azure-mobile-apps#62]
Quick start example in description

It doesn't even build

Error description : 
ZUMOAPPNAMEService: The path and / or file name you specified is too long. The fully qualified file name must be less than 260 characters and the directory name must be less than 248 characters. Failed to restore NuGet package for project.

**Comment by adrianhall** [comment]
This is a common problem (nothing to do with ZUMO) for Xamarin development.  I find placing the project right off the root drive works. (I place mine in `C:\gh\azure-mobile-apps-net-client`, for instance)
