### ISSUE TITLE
EntityTableData.Version should be virtual

### ISSUE THREAD

**Issue by oliverw** [Azure/azure-mobile-apps#625]
## Describe the bug

According to [this discussion](https://github.com/Azure/azure-mobile-apps/discussions/607#discussioncomment-5068630), the `EntityTableData.Version` property should be `virtual` but isn't.

**Comment by oliverw** [comment]
Is ther a reason why 5.1.2 is not yet available on NuGet? 🤔

**Comment by fileman** [comment]
> Is there a reason why 5.1.2 is not yet available on NuGet? 🤔

https://github.com/Azure/azure-mobile-apps/discussions/634#discussion-4897616

**Comment by oliverw** [comment]
> > Is there a reason why 5.1.2 is not yet available on NuGet? 🤔
> 
> [#634 (comment)](https://github.com/Azure/azure-mobile-apps/discussions/634#discussion-4897616)

Ah, missed that. Thanks 👍
