### ISSUE TITLE
Bug: Please remove reference to Maui.Essentials

### ISSUE THREAD

**Issue by nickrandolph** [Azure/azure-mobile-apps#630]
https://github.com/Azure/azure-mobile-apps/blob/1ed7821ac0dc2267a7a3c0a519027d266d78847e/sdk/dotnet/src/Microsoft.Datasync.Client/Microsoft.Datasync.Client.csproj#L30

This shouldn't be required in a cross-platform library and forces maui.essentials as a dependency on any application targeting net6-X

**Comment by dansiegel** [comment]
Running a quick test here if you remove that line and remove Xamarin.Essentials as a dependency from the classic Xamarin targets it still compiles just fine which tells me it's not actually used and should be removed as a dependency.

That said this really highlights an issue with the dependency chain where when installing the Datasync Client you would never know that you "need" UseMauiEssentials as it does not get passed through to the generated NuGet into the consuming project.
cc: @davidortinau @Redth
