### ISSUE TITLE
I've done all the step by step requirements of this tutorial, However, when i try to add items the error: The request could not be completed is presented to me

### ISSUE THREAD

**Issue by Lucas015** [Azure/azure-mobile-apps#64]

**Comment by AnastasiaKubova** [comment]
Hi, @Lucas015 ! Thank you for getting in touch with us!
Could you please clarify:
- What platform do you use?
- What version of SDK do you use?
- Could you please share the repo steps?
- Could you please share the logs?

**Comment by Jamminroot** [comment]
We haven't heard from you for a while, are you still facing the issue?
