### ISSUE TITLE
IReadOnlyOfflineTable

### ISSUE THREAD

**Issue by oliverw** [Azure/azure-mobile-apps#640]
**Is your feature request related to a problem? Please describe.**

It would be nice if offline tables also implemented a new interface `IReadOnlyOfflineTable<T>` which should be derived from `ILinqMethods<T>`. Additionally it should support:

```c#
Task<long> CountItemsAsync(ITableQuery<T> query, CancellationToken cancellationToken = default(CancellationToken));
IAsyncEnumerable<T> GetAsyncItems();
IAsyncEnumerable<U> GetAsyncItems<U>(ITableQuery<U> query);
new Task<T> GetItemAsync(string id, CancellationToken cancellationToken = default(CancellationToken));
```

This would allow applications to expose read-only access to the offline tables to internal components while reserving write operations to some central service/component.

**Comment by adrianhall** [comment]
I've just checked in a change today for this in the 6.0.0 release branch.  I will see about adding this to the 5.1.x branch when I return from vacation (week after next).

**Comment by oliverw** [comment]
> I've just checked in a change today for this in the 6.0.0 release branch. I will see about adding this to the 5.1.x branch when I return from vacation (week after next).

Cool. Enjoy your vacation.
