### ISSUE TITLE
Add IReadOnlyRemoteTable / IReadOnlyOfflineTable to HOW TO docs

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps#645]

**Comment by adrianhall** [comment]
Docs are being published.

**Comment by henda79** [comment]
Can you let me know when the docs are live please.

**Comment by adrianhall** [comment]
Available now: https://learn.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/howto/client/dotnet#create-an-offline-table
