### ISSUE TITLE
Question about how to access to the table from the Android app

### ISSUE THREAD

**Issue by AriLombardi** [Azure/azure-mobile-apps#65]
I followed this tutorial and all seems to work (I am new in azure and in SQL)!
But I have a question about how the table is accessed from the app. The name of the table of my datatable in Azure is ToDoItems (dbo.TodoItems), but I dont see this name in the android app: I think that the table is accessed by this line of code
`mToDoTable = mClient.getTable(ToDoItem.class);`
Is this right? Why the code works?

**Comment by russelarms** [comment]
Hi, thanks for getting in touch!
You're right.
When you call
`mClient.getTable(ToDoItem.class);`
it calls:
```
public <E> MobileServiceTable<E> getTable(Class<E> clazz) {
        return this.getTable(clazz.getSimpleName(), clazz);
    }
```
So, to simplify, `ToDoItem.class.getSimpleName ()` is used as the name of the table. The table is synchronized with the cloud table.

**Comment by AriLombardi** [comment]
Thank you very much for the answer!
