### ISSUE TITLE
Can't find easy tables

### ISSUE THREAD

**Issue by Narden56** [Azure/azure-mobile-apps#66]
Hi, I'm trying to do what the documents says in order to create an app. In step 3 there's usage of easy-tables that I can't find anywhere in the azure function. Can you please help me?

**Comment by Jamminroot** [comment]
Hello, @Narden56, sorry for misleading. As per [this article](https://azure.microsoft.com/en-us/updates/removing-easy-tables-and-easy-apis-from-azure-app-service/?cdn=disable), easy tables and easy API are removed since Nov 11, 2019.

**Comment by Narden56** [comment]
Is there an alternative?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jaelim-ms** [comment]
@Narden56 Is that a question for Azure Functions? Then you are on a wrong repository.
https://github.com/Azure/Azure-Functions/issues

There is no alternate solutions to take over easy tables and easy APIs. Sorry.

**Comment by ilyashumihin** [comment]
Hello, @Narden56!
We haven't heard from you in a while, so I close this conversation. Should you still have any questions, please contact us again.
