### ISSUE TITLE
How to migrate from Old Azure Mobile Apps to Newer One?

### ISSUE THREAD

**Issue by hirandesai** [Azure/azure-mobile-apps#662]
Looking at the documentation here -
https://learn.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/howto/client/dotnet-v4

There is no clear direction or mention for developers who have developed their Xamarin apps using old SDK v4.2.0 to the newer SDK.
Clear documentation should be written which suggests how the new SDK is different from the old one and what features are not supported form the old one to the newer one.

**Comment by adrianhall** [comment]
After a little bit of internal discussion, we've decided not to do this formally.  We will, of course, accept a submission (Wiki article, perhaps) from the community, but the internal team won't be addressing it.
