### ISSUE TITLE
Issue opening the offline sqlite store

### ISSUE THREAD

**Issue by kj4bix** [Azure/azure-mobile-apps#666]
I'm having an issue opening the OfflineSQLiteStore. I used the ToDo sample and don't see the problem. I'm running on Windows using the following connection string and the creation of the OfflineSQLiteStore is now failing. It was working in the past, but now fails. I'm using 5.1.3 of the Microsoft.Datasync.Client

Here is the connectionString:
var connectionString = new UriBuilder { Scheme = "file", Path = Path.Combine(FileSystem.CacheDirectory, localDbFileName), Query = "?mode=rwc" }.Uri.ToString();
var store = new OfflineSQLiteStore(connectionString);

Here is the exception:

Unable to open database connection to 'file://localhost/C:/Users/A_ANDERSON/AppData/Local/Packages/89572ed5-19ad-422e-9657-21583e4a02ce_hbve9c01gpnke/LocalCache/builderdb.db?mode=rwc': 14 unable to open database file

Should I use the FileSystem.Current.CacheDirectory instead? I tried it and it still didn't work. Maybe a permission issue? I also tried removing the database file entirely and it still doesn't work. It has worked in the past because my database in that directory was previously populated.

Ideas?

Thanks
Alan

**Comment by adrianhall** [comment]
Underlying this call (and the cause of the error) is that the system tries to open the file and fails.  This is normally permissions but could also be one of the directories doesn't exist.  From the information presented, I could not tell you which.

There is nothing I can do about this error.  It is something about your system.  I'd suggest (since you have control of your system) that you simplify the problem.  First off, try to use the regular file system calls and ignore OfflineSQLiteStore - directly before this line, insert code to open the file, read the first 10 bytes and then close the file.  Something like:

``` csharp
try {
  var path = Path.Combine(FileSystem.CacheDirectory, localDbFileName);
  byte[] test = new byte[10];
  using (BinaryReader reader = new(new FileStream(path, FileMode.Open)))
  {
    reader. Read(test, 0, 10);
  }
} 
catch (Exception ex) {
  Console.WriteLine($"exception - {ex.Message}"); // Put breakpoint here
}
```

You can then review the exception which is likely to have more detailed information about the failure that the underlying SQLite driver is not passing back to C# (and hence the OfflineSQLiteStore and your application).

Please let me know if this helps and/or close the bug.

**Comment by kj4bix** [comment]
Quick sample - write Hello World to the same file path using File.WriteAllText (it works)

        try
        {
            var path = Path.Combine(FileSystem.CacheDirectory, localDbFileName);
            File.WriteAllText(path, $"Hello World.");
            File.Delete(path);
        }
        catch (Exception ex)
        {
            Debug.WriteLine(ex.Message);
        }

I remove the file, then I let it try to create the database (which would be empty since the file doesn't exist), same error as above - into the same exact path, but using the UriBuilder. 

?

**Comment by adrianhall** [comment]
Underneath the covers, we use sqlite-net-pcl, which is a wrapper around the C version of sqlite.  This is actually done in SqliteConnection.cs with this code:

```csharp
int rc = raw.sqlite3_open(connectionString, out connection);
            if (rc != raw.SQLITE_OK)
            {
                var errmsg = raw.sqlite3_errstr(rc).utf8_to_string();
                throw new SQLiteException($"Unable to open database connection to '{connectionString}': {rc} {errmsg}", rc, connection);
            }
```

The sqlite3_open method is defined here: https://www.sqlite.org/capi3ref.html#sqlite3_open and you can find the meaning of the "rc" here: https://www.sqlite.org/rescode.html - 14 is SQLITE_CANTOPEN which is very very generic.  You can find out about URI filenames here: https://www.sqlite.org/uri.html - there are some examples of what works.

Your error message is coming from the heart of SQLite.  There is nothing I can do about it.  It's a lower level error than what we operate at.  We're asking SQLite to open the file you request (with ?mode=rwc means open read-write and create if doesn't exist).  SQLite is responding with "Nope - can't do that" with no other reason.

Suggestions:
1) Try a different directory.
2) Try a different filename.
3) Dump the URI and make sure it is escaped properly (it should be, but weird things sometimes happen).

**Comment by kj4bix** [comment]
I used a different filename, offline.db - still didn't work. I'll try a different directory. It is odd because it worked at some point, but now doesn't. I'll explore more tomorrow and let you know.

Thanks for your help, Adrian.

**Comment by adrianhall** [comment]
Likely true.  We had an issue with another library as well.  Basically, the Batteries.init() call doesn't properly initialize after the sqlite3_config() call on the first db is used.  I'm thinking this is a bug in the sqlite database, so I'm looking at switching the database driver to a higher level one in the 6.0.0 release.

**Comment by kj4bix** [comment]
Great, I was thinking over night about what had changed in my app, then realized I added the service that uses the local SQLite db. Commented that out this morning and magic happened. It definitely worked in the past, so it is something with SQLite I suspect. I'll write it to a JSON temporarily and keep migrating to MAUI. 

Thanks again.
ALan

**Comment by scout208** [comment]
I was running into a similar issue and it is because I was using the AppCenter SDK which also makes use of Local Storage. I removed the call to `AppCenter.Start()` and stopped receiving the error.
