### ISSUE TITLE
Selecting from OfflineTable specific columns

### ISSUE THREAD

**Issue by kj4bix** [Azure/azure-mobile-apps#677]
In the past with the Azure Mobile Client SDK you could select from the local table and pull just the column of interest. 

Here is what worked in the past:

                // Get lists for other deletions
                var fieldIssueIds = await fieldIssueTable.Where(q => q.OrderId == orderId).Select(q => q.FieldIssueId).ToListAsync();

I'm reading specific rows from my fieldIssueTable for an order id, then I select a specific column FieldIssueId from that table because I have dependent tables with data stored by the FieldIssueId. If you attempt to do this with the DataSync client SDK, it throws an exception in ServiceSerializer that your query doesn't have an Id column (around line 89) inside the method EnsureIdIsString. 

There is an easy workaround to read the filtered records with the Where clause, then do a select for the column of interest. 

            // Get lists for other deletions
            var orderFieldIssues = await fieldIssueTable.Where(q => q.OrderId == orderId).ToListAsync();
            var fieldIssueIds = orderFieldIssues.Select(q => q.FieldIssueId);

This seems to work fine, but it is a different behavior.

**Comment by adrianhall** [comment]
The old library got around this by ensuring every record had an ID.  I'll add that back.

**Comment by adrianhall** [comment]
Fixed in the next release (5.1.5, I think it is).  Note that your Select statement is wrong, however.  It should be something like:

```csharp
var fieldIssues = await fieldIssueTable.Where(q => q.OrderId == orderId).Select(q => new { q.FieldIssueId }).ToListAsync();
var fieldIssueIds = fieldIssues.Select(q => q.FieldIssueId);
```

The tables (both offline and remote) must return a list of objects due to the way that `IAsyncEnumerable` works within the library.  You can't just go to a string.

**Comment by adrianhall** [comment]
Work done:

* Updated `ServiceSerializer.cs` to properly recognize projections.
* Updated `OfflineTable.generic.cs` to allow submission of a projected remote table in constructor.
* Updated `TableQuery.cs` to use aforementioned constructor to generate a projected offline table.
* Added a test for a select of an offline table with no ID.

**Comment by kj4bix** [comment]
Thank you,  Adrian.
