### ISSUE TITLE
CancelledByAuthenticationError after 8-10 Min using of IMobileServiceSyncTable

### ISSUE THREAD

**Issue by rahultiwari007** [Azure/azure-mobile-apps#678]
## Describe the bug

we are using Xamarin forms + Azure SQL db,  with the help of  IMobileServiceSyncTable ,

but after using this for more then 8-10 minutes through mobile application , we are getting one error while pushing the data i.e.

MobileServicePushStatus.CancelledByAuthenticationError

even we are refreshing the token in case of expiration.

## Expected behavior

It should submit data when user is connected to internet and using the application.  

## What platforms?
Xamarin Forms

**Comment by adrianhall** [comment]
You are using the `IMobileServiceSyncTable`, which is part of the older library and not part of the new library.  The older library has been retired for some time and is no longer maintained.  Please upgrade to the newer library if you want to get any assistance.

**Comment by rahultiwari007** [comment]
> You are using the `IMobileServiceSyncTable`, which is part of the older library and not part of the new library. The older library has been retired for some time and is no longer maintained. Please upgrade to the newer library if you want to get any assistance.

which one is the latest version or replacement for using these features ?

**Comment by adrianhall** [comment]
Check out the documentation - it's linked in the README for this repository.
