### ISSUE TITLE
Omitting columns from the sync process

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps#681]
### Discussed in https://github.com/Azure/azure-mobile-apps/discussions/680

<div type='discussions-op-text'>

<sup>Originally posted by **henda79** May 25, 2023</sup>
I have some tables which have columns and are really only for the client. Is there a way to omit these from the sync ? I thought about some of the annotations I could use on the properties but ones like `JsonIgnore` would stop the column been created on the client wouldn't it ?!?

What's the best way to go about this if any ?

Also, is it possible to have table(s) in the database which does not sync at all. It seems overkill to have another database and all the fluff that comes with it for the sake of 1 or 2 tables.

Thanks !</div>

**Comment by henda79** [comment]
If the database does not exist on the client and is created at runtime, if the property is annotated with `JsonIgnore` won't this stop the column been created in the Db ?

**Comment by adrianhall** [comment]
Potentially.  It's one of those "what happens at reflection vs. what happens with serialization" questions.  It's not clear.   The short version is that the assumption is that the local db == remote db in form, and if necessary, the remote db is a superset of the local db.  We are now proposing to break that assumption, so lots of things likely break.

**Comment by amertlich** [comment]
We have client only tables stored in the local database that don't sync.  The way this works for us is by using a separate SQL connection outside the Datasync SDK that manages these tables on the same database.

As for specific columns that don't sync (or that aren't auto deserialized) -- we've had to use a different c# type that represents the synchronizable DTO type and then a separate c# type that we use through the separate SQL connection if we're requesting it with the extended data columns. So it's do-able, but I could see it being nice to be more officially supported.

**Comment by adrianhall** [comment]
There are two main reasons why you don't want to access SqLite from two connections:
1. You do in-memory caching at the connection level - we don't
2. You have file connection contention.
The second one is one of these "it works until it doesn't" kind of things.  If it works for OP, then fine.  However, once it doesn't, it will be a mess to clean up since the database files will be corrupted.

**Comment by amertlich** [comment]
SQLite handles concurrent reads _very_ well. It's the concurrent writes that are the potential problem. But since we control things from the same process and know how our database is accessed (through a shared DI service) we can synchronize writes in scenarios where we anticipate that happening.

**Comment by adrianhall** [comment]
This will be handled (in a different way) in the v8 client work.
