### ISSUE TITLE
Has EF Core client been implemented to allow complex models?

### ISSUE THREAD

**Issue by MarkLFT** [Azure/azure-mobile-apps#684]
I have been looking for a solution to syncing offline data from a mobile app to a remote service.  In my research everything seems to show that the sync process can only handle single, simple, table entities.  

Our application has multiple tables that are treated as a single entity, i.e. contains navigation properties, one to many, many to many etc. and I feel saving them as individual tables would be unsafe, we could end up only saving half of the entity.   

In our desktop apps we use EF Core, as the graph allows us to make all the changes, then save them as a single transaction, so all succeed, or all fail. 

Does azure mobile apps in an offline mode support this sort of functionality, and if so, do you have an example or blog somewhere? I read it was not available in version4, but might be available in version 5, so was wondering did it happen?

Many thanks in advance for your feedback.

**Comment by adrianhall** [comment]
You can't preserve navigation properties in an offline case.  You have to synchronize the entities, then set up the navigation yourself.  The reason for this is because a synchronization may break in the middle (network goes down, for example) which results in the navigation properties being broken.

**Comment by MarkLFT** [comment]
But by syncing the entities individually there is a finite time when the entity state is incomplete on the server, i.e. invoice header has been sync'd but the invoice lines have not, this then gets sync'd to other devices, and they have only partial data, which is very dangerous, especially of one of them is processing the payment for the invoice, but only knows about half of the items purchased.  

That is the whole point of saving the invoice plus items as a single transaction is all succeed or all fail.   I am sure there are many other use cases for this type of behaviour also. 

I find it very disappointing, when Microsoft is pushing mobile apps through Maui and Blazor, they do not have a complete, off the shelf, solution for offline data and syncing.
