### ISSUE TITLE
ZUMOAPPNAME OUTDATED!!

### ISSUE THREAD

**Issue by nDezai** [Azure/azure-mobile-apps#69]
This is ridiculous!

Having followed the steps in the article to the exact letter (https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-ios-get-started) I am now undone by the lack of updated Microsoft Azure and their staff have done to support Swift beyond version 3.

I press run and instantly get flagged with "Swift 3 not supported, please downgrade XCode", and if I change the language to Swift 5 (THE CURRENT LANGUAGE), I am given a failed build due to 'MicrosoftAzureMobile/MicrosoftAzureMobile.h' file not found.

If Microsoft wants people to use their cloud database, take a leaf out of Google and have up to date documentation with step by step instructions for whatever version of XCode you are running.

I'm hoping someone sees this and is able to help me figure out how to make the final step of the tutorial work. Given that most of those working at Microsoft provide extremely slow fixes, I'm praying that someone else that struggled has found a fix.

**Comment by elamalani** [comment]
@nDezai We haven't made any major changes to Azure Mobile Apps for some time now, including the update to the latest version of Swift. Sorry for the inconvenience that was caused. We will update the documentation to reflect the supported Swift version.

**Comment by adrianhall** [comment]
Closing issue due to feature work suspension,
