### ISSUE TITLE
Maui Sample: ClearButtonVisibility exception

### ISSUE THREAD

**Issue by LKujala** [Azure/azure-mobile-apps#697]
## Describe the bug

Maui sample application, main page, Entry control is throwing xaml parsing exception on the ClearButtonVisibility property.

## To Reproduce

1. Using tag 5.1.6, build and run ToDoApp.Maui Windows application
2. During start up exception is thrown
Microsoft.Maui.Controls.Xaml.XamlParseException
  HResult=0x80131500
  Message=Position 9:17. The PropertyName of Entry.ClearButtonVisibilityProperty is not ClearButtonVisibility
  Source=Microsoft.Maui.Controls.Xaml

## Expected behavior

Application should start without an exception.

## What platforms?

using Visual Studio 2022 version 17.7.0 Preview 2.0

Maui example as configured in tag 5.1.6
- microsoft.maui.dependencies 6.0.553
- microsoft.maui.extensions 6.0.553
- microsoft.maui.controls 6.0.533
- microsoft.maui.core 6.0.533
- microsoft.netcore.app 6.0.16

## Additional context

Did a little bit of debugging:
- the Entry property ClearButtonVisibility is being set through a static resource style (addItemEntry defined in Styles.xaml using a setter)
- removing the setter from the style sheet and explicitly setting the property in MainPage.xaml "resolves" the exception
- the style sheet setter property looks well formed; the style sheet hasnt changed in a year, so why would this not parse correctly anymore?

**Comment by adrianhall** [comment]
Thanks for the report.  I'll take a look and get a fix in - it shouldn't be too hard.

I suspect the MAUI version you are using is MAUI for .NET 7, which had some changes in this area.

**Comment by LKujala** [comment]
I am still using the .net 6 version in the sample ToDoApp... unless this is automagically running .net 7 even though the profile is for .net 6?

**Comment by adrianhall** [comment]
Unfortunately - yes.  .NET 7 is somewhat backwards compatible (i.e. a .NET 7 runtime can run a .NET 6 application).  Run "dotnet workload list" to see what version of MAUI you are running.  The Manifest version will tell you.

**Comment by LKujala** [comment]
as you suspected the manifest version for maui is 7.0.86

will the following work to get the previous version of maui installed? 
dotnet workload install maui `
   --skip-manifest-update `
   --source https://aka.ms/dotnet6/nuget/index.json

I assume both versions of the workload can be installed

**Comment by LKujala** [comment]
I tried a couple of different ways to install "previous version"; no joy. so I obviously misunderstand something about installing workload.
I am moving on for now (I have other things to get done). 
the hack of moving the property from the style sheet to the aspx file works (ie I can run the example).

I will probably delete my copy of the example in a few weeks, at which point I wont be able to test any fixes.
I dont really care if you get around to looking at this.

**Comment by adrianhall** [comment]
I'm going to be fixing this tomorrow :-)

**Comment by LKujala** [comment]
thx. 
currently working through Remote build and testing on iOS and MacOS (that process is gong show with Apple config).
once I get that working, I can test on those platforms as well.
