### ISSUE TITLE
Sync: ID Mutation

### ISSUE THREAD

**Issue by phvannor** [Azure/azure-mobile-apps#7]
Support a basic ID mutation workflow within the SDK.

**Comment by phvannor** [comment]
At its core we need to review the ID coming back from the server with the ID we sent on a POST (insert).  In the event that the ID has changed we need to:
- Remove the old record in the table, and add the new record in the table
- Notify the developer that we have did this so they can update all instances in memory in the app
  - this is also harder for languages not doing mutation, etc, hopefully though most devs would know if their tables can mutate IDs in their own logic
 - Figure out updates in progress (behind lock (managed), in queue (iOS)) and how they should be modified
- When the mutation is INTO an existing record ID:
 - is the record already local, if so, we need may need to trigger some type of conflict resolution if our local copy is not clean
 - Will it be possible for the ID to mutate, but the change set not be accepted?  (conflict)  Similiar to above story, we basically can end up w/a 3 way merge we need to let the dev handle.

*Assuming ID mutation is limited to creation for this*

**Comment by elamalani** [comment]
Hey everyone, please have a look at the Readme section for the future of [Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps#future-of-azure-mobile-apps). Closing this issue for now.
