### ISSUE TITLE
Net7Maui style sheet is missing styles

### ISSUE THREAD

**Issue by LKujala** [Azure/azure-mobile-apps#702]
## Describe the bug

Net7Maui style sheet is missing styles used in mainpage.xaml

## To Reproduce

Run Net7Maui ToDoAppMain
will get numerous exceptions that static resource is not found.

## Expected behavior

should not be an exception

## What platforms?

N/A

## Additional context

Copy missing style entries from the TodoApp.MAUI example or remove references from mailpage.xaml
styles that are missing

- addItemEntry
- addItemIcon
- listItemcontainer
- listItemIcon
- listItemTitle
- roundedCornerFrams
- titleViewContainer
- titleViewLabel
- titleViewIcon
- titleViewRefreshIcon

**Comment by adrianhall** [comment]
Unable to reproduce.  Attempted on Android Emulator (API Level 33, Pixel 5) and "Windows Machine".  

Can you please do a full clean and re-build, then report which specific environments are having this problem?  Also, please note your actual environment (what checkin tag are you working against, what version of MAUI workloads, what version of VS).

Thanks!
