### ISSUE TITLE
Net7Maui binding fails to target property Title, IsComplete

### ISSUE THREAD

**Issue by LKujala** [Azure/azure-mobile-apps#703]
## Describe the bug

in MainPage Binding to "TodoMauiApp.ViewModels.MainViewModel" Title and IsComplete fails. The UI is not rendered correctly.

## To Reproduce

1. Run TodoMauiApp
2. view Debug output

## Expected behavior

The UI should render the Title and IsComplete values.

## What platforms?

Running on Windows in the Maui version 7 example.

## Additional context

Comparing the code to the Maui version 6 example (TodoApp.MAUI) the main difference is the ToDoListViewModel has been merged into the MainViewModel. But that shouldn't matter. In MainPage ListView the DataTemplate data type seems correct as "models:ToDoItem", but is not actually being applied to bindings (ie the binding is looking at "MainViewModel" rather than the "MainViewModel.Items" type of "TodoItem" ).

**Comment by adrianhall** [comment]
Running the latest code in "Windows Machine", I see the UI rendering title and isComplete.  

Can you be specific about:
* What version of Visual Studio
* What versions of the MAUI workloads
* How are you running the app?
