### ISSUE TITLE
Cordova Sample gets a exports inside circular dependency error, any plans to update the library to a later Cordova Version?

### ISSUE THREAD

**Issue by doughjoe77** [Azure/azure-mobile-apps#709]
## Describe the bug

I'm testing using Cordova with the Azure Mobile and Azure AD Cordova plug-ins.  The documentation to set this up (https://learn.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/quickstarts/cordova/ and https://learn.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/quickstarts/cordova/authentication)

## To Reproduce

1. follow the directions in https://learn.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/quickstarts/cordova/
2. run the command ```cordova platform add android```

## Expected behavior

Command runs and Cordova adds the Android functionality without an error :-)

## What platforms?

* Latest version of VS Code
* Run Cordova version 8.1.2 (https://learn.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/quickstarts/cordova/#apache-cordova-812-or-earlier-required)

## Additional context

It seems like the sample uses a much older version of Cordova, will Microsoft update it's plug-ins at some point to support the latest Cordova versions?

**Comment by adrianhall** [comment]
I am not planning of re-introducing support for Apache Cordova.  Per our README (front page of the repo)

Currently, we support:

* ASP.NET Core for .NET 6.
* .NET Standard 2.0 Client - Xamarin (Native and Forms), UWP, WPF.
* .NET 6 Client - MAUI and Windows App SDK (WinUI3).
