### ISSUE TITLE
Xamarin.Forms local db being deleted every time app starts

### ISSUE THREAD

**Issue by blmiles** [Azure/azure-mobile-apps#710]
## Describe the bug

I have had my XF app running live for two years + now. Same db mechanics since the start.
Not doing anything different to this ... https://learn.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/howto/client/dotnet-v4

But since the latest iOS updates AND now updating the plugin libraries, my local db on the device is cleared every time the app is quit and restarted.

`
                    var store = new MobileServiceSQLiteStore(dbPath); //path is to the local Personal folder on device

                    store.DefineTable<Appointment>();

                    //Initializes the SyncContext using the default IMobileServiceSyncHandler.
                    await client.SyncContext.InitializeAsync(store);

                    appointmentTable = client.GetSyncTable<Appointment>();
`
_All db mechanics follow, no change, all works._

I start the app, navigate to calendar, add appointments, navigate around the app, everything still in the db. Editing and adding fine.
Quit the app. Restart the app. All data is gone.

I thought there was an issue connecting to Azure to sync. but commenting out the sync mechanics, it still clears the db every time after adding/editing data, quit and restart.

QUESTION:

Does this now delete and recreate the local db each time? _var store = new MobileServiceSQLiteStore(dbPath);_
Or this? await client.SyncContext.InitializeAsync(store);

Not sure if I've missed something in the updates or should be doing something differently, but local data cannot be deleted every time the app quits and is restarted. Local should persist until a sync is called...

Anyone?

## What platforms?

Xamarin.Forms, iOS and Android. Local issue only, for now.

**Comment by adrianhall** [comment]
You are using an unsupported version of Azure Mobile Apps.  We haven't changed anything in that release in a number of years.

While the upgrade to the Microsoft.Datasync.Client library (and the update from ASP.NET Framework to ASP.NET Core that the server requires) are non-trivial, we can't support you unless you are on a supported version.

**Comment by blmiles** [comment]
Hi @adrianhall 

Thanks for that feedback. 

It's unfortunate that such breaking changes get introduced to frameworks and libraries that are live and one needs to jump through such large hoops to make their apps work again... Everything I have live WORKs right now.
All these updates have broken so much and adds so much dev time just to handle these changes and be up-to-date with the app stores.

Sorry for the rant, just frustrating, albeit the work you guys do do ultimately make much of this possible.

I'll bump up to Microsoft.Datasync.Client and look into what I need to do to the Azure service I have.
If you have any link/info re the update from ASP.NET Framework to ASP.NET Core, that'd be helpful.

I'm sure I'll be in touch through here again.

Thanks again.

**Comment by adrianhall** [comment]
The mobile application will be relatively small changes (namespace changes for the most part, but there is a change to the format of the SQLite database location).

The ASP.NET Core part is a complete re-write, mostly because framework -> core generally comes down to a complete rewrite.  You can find all the details in the docs (which you've already found).
