### ISSUE TITLE
Support for non-Microsoft authorization

### ISSUE THREAD

**Issue by blmiles** [Azure/azure-mobile-apps#712]
Hello,

You previous framework had support to authorize/authenticate external 3rd party credentials with JwtSecurityTokenHandler etc.
That was implemented on my side and it works.

I use Auth0 as my login/security provider.

Here's a short snippet which might ring a bell...

`
using System.IdentityModel.Tokens;
using System.Security.Claims;
using System.Web.Http;
using Microsoft.Azure.Mobile.Server.Login;
using Newtonsoft.Json.Linq;
......

namespace MyCompanyAzure.Controllers
{
    [Route(".auth/login/auth0")]
    public class Auth0Controller : ApiController
    {
        private JwtSecurityTokenHandler tokenHandler;

Authorization/Authentication is all handled from here on...
`

**Does the new framework have something similar?
Is there sample code? Any guide to doing this using the new framework?**

I don't want to implement MS AD. Too many users in Auth0

**Comment by adrianhall** [comment]
We don't prescribe an authentication mechanism any more.  There is a `GenericAuthenticationProvider` that takes an async task to allow you to give us an access token, which we then add as an Authorization header to every request.

Short version - you should be able to add Auth0 really simply.  

Long version:
1. Add Auth0 authentication / authorization to your ASP.NET Core application - instructions here: https://developer.auth0.com/resources/get-started/web-app/aspnet-core
2. Follow the instructions for adding auth to your application from the tutorial.
3. Add Auth0 authentication / authorization for your platform of choice - instructions for Xamarin Forms here: https://auth0.com/docs/quickstart/native/xamarin

I have not tried it, nor am I going to support 3P authentication providers.

**Comment by blmiles** [comment]
Thanks @adrianhall

I already have all 3 steps in place (step one within the old framework - see attached file) in the current LIVE app and service.
Your step 1 is what I need to refactor into the new [myservice].Net6 but at the moment the various plugins that WERE being used don't, as even the latest don't play nicely in/with .Net6

Haven't looked at this for a while so will look at what Auth0 prescribe, hopefully with latest ASP.Net Core.

[Auth0ControllerForGit.txt](https://github.com/Azure/azure-mobile-apps/files/12312541/Auth0ControllerForGit.txt)
