### ISSUE TITLE
Update LiteDbRepository to expose Collection

### ISSUE THREAD

**Issue by powerdude** [Azure/azure-mobile-apps#727]
**Is your feature request related to a problem? Please describe.**
I found myself need to make additional calls to `EnsureIndex` and tried to get the collection, but not initially knowing the `collection` nam used in the constructor led to problems.

**Describe the solution you'd like**
change the `collection` field to a read-only `Collection` property

**Describe alternatives you've considered**
I currently copy the class into my solution to make this change.

**Additional context**
nothing else.

**Comment by adrianhall** [comment]
Seems reasonable.  I'll do the change; non-urgent, so it will go out in the next release.

**Comment by adrianhall** [comment]
Fixed in ffe17c1
