### ISSUE TITLE
IReadOnlyOfflineTable empty result

### ISSUE THREAD

**Issue by fileman** [Azure/azure-mobile-apps#730]
## Describe the bug
I'm tring to switch from an IOfflineTable<TodoItem> to IReadOnlyOfflineTable<TodoItem>, so I have removed call to PullItemsAsync and PurgeItemsAsync since not available in ReadOnly, but I get an empty table result.

## To Reproduce

Change this working code:
```
private IOfflineTable<TodoItem> _todoItems = null;

public async Task<IEnumerable<TodoItem>> GetTodoItemsAsync()
{
    await InitializeAsync();
    await _todoItems.PullItemsAsync(_todoItems.IncludeDeletedItems());
    TodoItems = await _todoItems.GetAsyncItems().ToListAsync();
    var purgeDeletedItemsQuery = _todoItems.CreateQuery().Where(x => x.Deleted == true);
    await _todoItems.PurgeItemsAsync(purgeDeletedItemsQuery, new PurgeOptions { DiscardPendingOperations = false });
    return TodoItems;
}
```
to:
```
private IReadOnlyOfflineTable<TodoItem> _todoItems = null;

public async Task<IEnumerable<TodoItem>> GetTodoItemsAsync()
{
    await InitializeAsync();
    TodoItems = await _todoItems.GetAsyncItems().ToListAsync();
    return TodoItems;
}
```

## Expected behavior

Get same items as IOfflineTable... it is correct that we do not call PullItemsAsync in ReadOnly table?
Am I doing something else wrong?

## What platforms?

* Server: ASP.NET Core
  * Library versions 5.1.8

* Client .NET:
  * .NET Runtime Environment: MAUI
  * Library versions: 5.1.8
  * Does it happen in an emulator

**Comment by adrianhall** [comment]
You need to pull items at some point, which means something in your application needs to be able to "pull" at some point (and hence write to the database).  If you have an application with a background worker and a UI, and the UI needs to "only read", then your background worker can have a read/write connection to the table to do the pull, but the UI doesn't have the ability to add/remove items.

**Comment by fileman** [comment]
Ok, I need a Offline table and expose ReadOnly to UI.

It wouldn't be easier to have pull and purge methods even in readonly?

**Comment by adrianhall** [comment]
I agree with PullItemsAsync.  I think your specific purge would be better off being an option on the end of PullItemsAsync, so I'll do that as well.

Something like:

``` csharp
await _todoItems.PullItemsAsync(_todoItems.IncludeDeletedItems(), new PullOptions { PurgeDeletedItems = true });
```
