### ISSUE TITLE
PurgeItems dont clear incremental sync cache

### ISSUE THREAD

**Issue by fileman** [Azure/azure-mobile-apps#740]
## Describe the bug

After purge a table, incremental sync cache isnt deleted, so the oldest items wasn't downloaded again.
I'have to uninstall & reinstall the app, it's my error or a bug?
thanks

## To Reproduce
Invoke:
`await table.PurgeItemsAsync("", new PurgeOptions { DiscardPendingOperations = true });`
or
`await table.PurgeItemsAsync(table.CreateQuery(), new PurgeOptions { DiscardPendingOperations = true });`

Pull request:
https://10.0.2.2:44313/tables/items?$filter=%28updatedAt%20gt%20cast%282023-09-07T18%3A16%3A33.597Z%2CEdm.DateTimeOffset%29%29&$orderby=updatedAt&$count=true&__includedeleted=true

## Expected behavior

An empty request like first run of app
https://10.0.2.2:44313/tables/items?$orderby=updatedAt&$count=true

* Client: 5.1.8

**Comment by adrianhall** [comment]
I'm thinking adding a PurgeOption:

``` csharp
new PurgeOptions 
{
    DiscardPendingOperations = true,
    UpdateSyncTimestamp = true
};
```

If I set UpdateSyncTimestamp to true, then the timestamp is set to the largest UpdatedAt value in the local cache at the time.

Does that seem like a reasonable solution, @fileman
