### ISSUE TITLE
Need Documentation/Help - Conflict resolution...

### ISSUE THREAD

**Issue by nvrnight** [Azure/azure-mobile-apps#747]
A conflict occurs when a record that is sync'd on the client and server gets modified on both and then the client performs a push or pull. An error is provided in the push results that gives the Item, the Result Item and a Status of "Conflict". How do I deal with this? I looked for documentation for dealing with the scenario, but I didn't find anything. Possible I just am not looking in the correct place.

Any help would be greatly appreciated, I'm going to have to have some hard conversations if I can't get this working.

**Comment by nvrnight** [comment]
I finally found the documentation, Google just wasn't bringing it up for me, Sorry about the ticket. Here's the link for anyone that needs it in the future.

https://learn.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/howto/client/dotnet#conflict-resolution-and-optimistic-concurrency

**Comment by adrianhall** [comment]
Glad you found it - our docs on learn.microsoft.com are a great place to bookmark!
