### ISSUE TITLE
TimestampUpdatePolicy enum missing description

### ISSUE THREAD

**Issue by fileman** [Azure/azure-mobile-apps#757]
## Describe the bug
Source code contains description for TimestampUpdatePolicy enum, but in nuget is lost, so VS Intellisense dosen't show it

## To Reproduce
add TimestampUpdatePolicy

## Expected behavior
see description like in source

**Comment by adrianhall** [comment]
Added descriptions to each option, and summary to the entire thing.  Hopefully, that will solve the intellisense problem.  After that, not sure what else I can do.
