### ISSUE TITLE
Resolve "conflict" on a PushItemsAsync() call...

### ISSUE THREAD

**Issue by blmiles** [Azure/azure-mobile-apps#759]
## Describe the bug

Not sure if this can be considered a bug or a gap...
Cannot find info on this so will ask question here...might be some option worth building into the framework.
could also be controversial too :)

## Scenario

I have a currentDb in Azure, currentAppService syncs data from currentApp. No problems.

I made a copiedDb in Azure and a syncgroup from the currentDb and the copiedDb. No probs.

New MauiApp on device using originaldeviceDB, all db operations work locally.

When I hit the PushItemsAsync() call, I have a number of records existing both on remote/app db AND in the currentDb and copiedDB on Azure that cause a failure citing a conflict. Looking at the PushResult, the PushItemsAsync() is trying to do an insert with those records that already exist.

Is there any amendment that can be made on the AppService side to check for existing before Insert and force an update instead?
Wonder too if that'd be needed on the Pull into the app too as it might see the server-side records as new too and try Insert into app Db causing a failure that way as well.

Apologies for posting here as a bug, but this is so specific to this framework, not sure where else to ask.

## Expected behavior

Possibly in the Push or Pull, if conflict/record exist in target db, UPDATE, not Insert ??
Maybe as an option in PushOptions and PullOptions?

## What platforms?

Android, iOS, Windows. All target .Net 7
Azure App Service. Targets .Net 6
Azure SQLServer

**Comment by adrianhall** [comment]
I suspect the copiedDb has different Version / UpdatedAt fields that the equivalent records in the currentDb.  This means that the data is considered "different" by the client.  If that's the case, then you also need a clean database on the client side to accomodate the two versions.

**Comment by blmiles** [comment]
Yeah,

I'm stumped how to do this without screwing up all.

You're right, both fields are different to the currentDb.
I cannot replicate the currentDb on the same SQLServer instance and need to
spin up a new instance I guess. That is, assuming replication would solve
the problem.

I tested deleting the client side db to see if the pull to the client would
solve the problem but it won't pull data either, no errors thrown.
So that's something else I need to look into now too...

I cannot delete client-side local db either anyway, as 70% of users don't
sync data to cloud as that is behind a subscription.

I think I might disable data sync in the Android version temporarily,
running out of time. Android app needs to be updated before Nov 1st else it
can no longer be updated and will need a new app instance and new app
name/id etc.
That'll screw all my Android users. And I don't need to deploy a new iOS
version anyway.

All else works in the app so I'll deploy that just to make the Android
deadline and buy time to get the data sync'ing right, then update again.

I did look at your code as suggested but I think other blocks need to be
overcome before I mess with that as a last resort.

I'm sure I'll ask more questions.
Need to tidy up infrastructure first methinks.

Further suggestions are always welcome :)

Thanks again Adrian!

**Comment by adrianhall** [comment]
My pleasure.  I hope it works out for you.

**Comment by blmiles** [comment]
Adrian, FYI,

I replicated the currentDb, repointed the app service at that replication,
checked fields - all identical.

Still seeing this come back in the PushResult:

Microsoft.Datasync.Client.Offline.Queue.TableOperationKind.Insert

System.Net.HttpStatusCode.InternalServerError


if the local db is new, nothing to push, the pull returns nothing from the
cloud db, expected 7 records.
if items are added client-side, subsequent push fails with above issues.

I'll first look at why the pull fails into an empty db.

I'll send findings IF I think they could be interesting to you.

Lindsay Miles

**Comment by dburrell67** [comment]
I'm seeing this same issue. I've put data into the offline table using <table>.InsertItemAsync(item), then I'd like to push that data to the Web Application, so I do a <table>.PushItemsAsync(). When that happens, I get the Microsoft.Datasync.Client.Offline.Queue.TableOperationError. HTTPStatusCode - Conflict. When I look at my database the data is there. Does the InsertItemAsync get the data there? Am I not supposed to do a PushItemsAsync?

**Comment by adrianhall** [comment]
Hi @dburrell67 - I didn't see this, unfortunately.  This is a closed issue - please open a discussion for questions.
