### ISSUE TITLE
JsonContainer attribute mechanism for naming tables does not work.

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps#763]
I should be able to do something like:

```csharp
[JsonContainer("MyTable")]
public class MyTableDao : DatasyncClientData {
...
}
```

But it doesn't work for naming the table.

### Discussed in https://github.com/Azure/azure-mobile-apps/discussions/762

<div type='discussions-op-text'>

<sup>Originally posted by **henda79** September 24, 2023</sup>
In relation to my other discussion #761 , when using Attributes to set the SQL Table name on the data model, the documents state to use either `DataTable` or Json Attributes and then links to https://www.newtonsoft.com/json/help/html/SerializationAttributes.htm

Which attribute is used ? I've used `JsonObject("MyTable")` but the resolver code does not work as it uses the `Title` property, but would work fine with the `Id` property

```
if (!string.IsNullOrWhiteSpace(jsonattr.Title))
{
    name = jsonattr.Title;
}
```
Again, is this something I am doing wrong ?
</div>

**Comment by amertlich** [comment]
We're using System.ComponentModel.DataAnnotations.Schema.TableAttribute to annotate our classes with a `Table["TableName"]` attribute and it seems to work?

**Comment by adrianhall** [comment]
Not for Azure Mobile Apps - you can use `[JsonObject("tableName")]` or `[DataTable("tableName")]`.

**Comment by amertlich** [comment]
Whoops, you're right client side that's what we're using (DataTable).  Server side it's the other (Table).
