### ISSUE TITLE
Using IOfflineStoreExtensions DefineTable

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps#764]
### Discussed in https://github.com/Azure/azure-mobile-apps/discussions/761

<div type='discussions-op-text'>

<sup>Originally posted by **henda79** September 24, 2023</sup>
Hi, I've recently started porting to MAUI... oh the joys.

I've took this opportunity to refactor some code. Previously our table names matched the model names, but now my model are suffixed with Dto, so `UserDto` for example and the table name is `Users`. So with this in mind, I define all my tables using:

`IOfflineStoreExtensions.DefineTable<UserDto>("Users");`

However I notice when calling the `GetOfflineTable` method, it prepares the SQL statement using the table name `userdto`. I've looked at the code I can see that `DatasyncContractresolver.ResolveTableName` only gets the table name from the attribute in the model, which is great, but the question here is what is the point in defining the tables with explicit names ?

What I'd like to see is the resolution of table names from here or the attributes. Correct me please if I've missed something :)</div>

**Comment by henda79** [comment]
@adrianhall since it is possible to define the tables like

`store.DefineTable<UserDto>("Users");`

I was hoping the method

`var table = client.GetOfflineTable<UserDto>();`

would resolve the name from where I have already defined the table. So basically use the type and lookup in the definitions dictionary and see there is another name to use... or as you say just use attributes.

**Comment by adrianhall** [comment]
The problem is when you have two distinct ways of accessing the same data - one might use JSON/JObject and the other might use a subset of the data via a different model.  There are too many permutations, which is why we prefer you to use the DataTable attribute for this.

**Comment by henda79** [comment]
Fair enough, I'll use the Attributes then.

Thanks Adrian for addressing these issues.
