### ISSUE TITLE
DatasyncDocumentFilter does not work with custom BaseTableController

### ISSUE THREAD

**Issue by asierpn** [Azure/azure-mobile-apps#770]
## Describe the bug

If you create a custom BaseTableController derived from TableController as the base class for the endpoints, the DatasyncDocumentFilter won't process them, so the OpenApi parameter definitions won't be added.

## To Reproduce

1. Create a BaseTableController class that derives from TableController.
2. Modify TodoItemController to use BaseTableController as its base class.
3. Configure the backend to use Swashbuckle and run it.
4. The OpenApi schema is not generated and there is no way to test the controller.

## Expected behavior

The OpenApi parameter definitions should be generated.

## Additional context

I have overcome this issue by creating a custom IDocumentFilter with the same code as the DatasyncDocumentFilter and changing this method, but it would be great if it was handled by design.

    internal static List<Type> GetAllTableControllers(Assembly assembly = null)
    {
      return (assembly ?? Assembly.GetCallingAssembly())
          .GetTypes()
          .Where(t => t.BaseType?.IsGenericType == true && !t.IsAbstract && t.GetCustomAttributes().Any(s => s.GetType().Name.Contains("DatasyncControllerAttribute")))
          .ToList();
    }

**Comment by adrianhall** [comment]
Love the solution.  I'll get this fix into 6.0.3.
