### ISSUE TITLE
DatasyncDocumentFilter does not work with ReadOnlyTableController

### ISSUE THREAD

**Issue by asierpn** [Azure/azure-mobile-apps#771]
## Describe the bug

Similar issue than #770 but when using a ReadOnlyTableController as the base class like this one:

    [NonAction]
    public override Task<IActionResult> CreateAsync([FromBody] TData item, CancellationToken token = default)
    {
      return base.CreateAsync(item, token);
    }

    [NonAction]
    public override Task<IActionResult> DeleteAsync([FromRoute] string id, CancellationToken token = default)
    {
      return base.DeleteAsync(id, token);
    }

    [NonAction]
    public override Task<IActionResult> PatchAsync([FromRoute] string id, CancellationToken token = default)
    {
      return base.PatchAsync(id, token);
    }

    [NonAction]
    public override Task<IActionResult> ReplaceAsync([FromRoute] string id, [FromBody] TData item, CancellationToken token = default)
    {
      return base.ReplaceAsync(id, item, token);
    }

## To Reproduce

1. Create a ReadOnlyTableController class that derives from TableController and override the write methods to make them unavailable.
2. Modify TodoItemController to use ReadOnlyTableController as its base class.
3. Configure the backend to use Swashbuckle and run it.
4. The OpenApi schema is not generated and there is no way to test the controller.

## Expected behavior

The OpenApi parameter definitions should be generated.

## Additional context

I have overcome this issue modifying the DatasyncDocumentFilter and changing these methods, but it would be great if it was handled by design.

    internal static bool IsApiDescriptionForController(ApiDescription description, Type controllerType)
    {
      if (description.TryGetMethodInfo(out MethodInfo methodInfo))
      {
        return methodInfo.ReflectedType == controllerType && (methodInfo.Name.Equals("GetAsync") || methodInfo.Name.Equals("QueryAsync"));
      }
      return false;
    }

Apply method:

        // Get the various operations
        var operations = new Dictionary<OpType, OpenApiOperation>();
        if (document.Paths[allEntitiesPath].Operations.TryGetValue(OperationType.Post, out OpenApiOperation createOperation))
          operations.Add(OpType.Create, createOperation);
        if (document.Paths[singleEntityPath].Operations.TryGetValue(OperationType.Delete, out OpenApiOperation deleteOperation))
          operations.Add(OpType.Delete, deleteOperation);
        if (document.Paths[singleEntityPath].Operations.TryGetValue(OperationType.Get, out OpenApiOperation getByIdOperation))
          operations.Add(OpType.GetById, getByIdOperation);
        if (document.Paths[allEntitiesPath].Operations.TryGetValue(OperationType.Get, out OpenApiOperation listOperation))
          operations.Add(OpType.List, listOperation);
        if (document.Paths[singleEntityPath].Operations.TryGetValue(OperationType.Patch, out OpenApiOperation patchOperation))
          operations.Add(OpType.Patch, patchOperation);

        // Make the system properties in the entity read-only
        if (!processedEntityNames.Contains(entityType.Name) && context.SchemaRepository.Schemas.TryGetValue(entityType.Name, out var openApiSchema))
        {
          openApiSchema.MakeSystemPropertiesReadonly();
          openApiSchema.UnresolvedReference = false;
          openApiSchema.Reference = new OpenApiReference
          {
            Id = entityType.Name,
            Type = ReferenceType.Schema
          };
        }

**Comment by adrianhall** [comment]
Turns out this one was fixed by the fix for #770.  I also fixed NSwag at the same time (which was a little more complicated).

**Comment by adrianhall** [comment]
Fixed in #778
