### ISSUE TITLE
Implement a PostCommitHookAsync method

### ISSUE THREAD

**Issue by asierpn** [Azure/azure-mobile-apps#775]
**Is your feature request related to a problem? Please describe.**
It would be useful to implement a PostCommitHookAsync method to execute custom code after an entity has been successfully (or not) inserted, updated or deleted.

**Describe the solution you'd like**
Implement a PostCommitHookAsync method and call it just before the action method finishes to be able to execute custom code.

**Describe alternatives you've considered**
I'm overriding the CreateAsync, PatchAsync, ReplaceAsync and DeleteAsync methods to get the result and act depending on its value, but a PostCommitHookAsync method would be more convenient.

**Comment by adrianhall** [comment]
I like this idea, but I want to get more information on what you want to do with it so I can implement it the right way.

What sort of things are you thinking of doing in the PostCommitHook?

There are basically three ways to do this.

1. Register an event handler with the table controller.  Call the event handler right before you return.
2. Create a new type like the IAccessControlProvider that has the PostCommitHook inside it - allows you to access the HttpContext reasonably.
3. Add the PostCommitHook to the IAccessControlProvider.

Thoughts on which mechanism would fit your use case and why?

**Comment by asierpn** [comment]
I usually do things like logging, sending notifications or starting batch jobs. Options 2 or 3 fit my scenarios better, as I usually access the HttpContext to get information about the current user. I implement the IAccessControlProvider in our custom BaseTableController, so centralising logging in the PostCommitHook is also easy using the PostCommitHook option.
