### ISSUE TITLE
Ability to do custom validation before commit in TableController

### ISSUE THREAD

**Issue by asierpn** [Azure/azure-mobile-apps#781]
**Is your feature request related to a problem? Please describe.**
We have scenarios where we need to perform some custom complex validations against databases or external servers before doing a commit, and if the validation fails we return an error to the client.

**Describe the solution you'd like**
It would be useful to have the ability to return a custom IActionResult before a commit is executed, for example adding an IActionResult return value to the PreCommitHookAsync and returning it from the TableController action methods when provided by the PreCommitHookAsync method.
I know that adding a return value or output parameter to the PreCommitHookAsync method is a breaking change, so another option is to create a new PreCommitResultAsync or PreCommitValidationAsync method to do these actions on it.

**Describe alternatives you've considered**
I'm overriding the CreateAsync, PatchAsync, ReplaceAsync and DeleteAsync methods to perform the validations and return a custom result, but a centralised way to do this would be more convenient.

**Comment by adrianhall** [comment]
The response from the server is not propagated to the user in the client.  How are you getting the IActionResult today?

**Comment by asierpn** [comment]
I'm doing something like this:

    public override async Task<IActionResult> CreateAsync([FromBody] TodoItem item, CancellationToken token = default)
    {
      if (await CheckDuplicated(item))
        return new ObjectResult(Strings.Validation_DuplicatedItem)
        {
          StatusCode = StatusCodes.Status500InternalServerError,
        };
      return await base.CreateAsync(item, token);
    }

**Comment by adrianhall** [comment]
This type of thing is better done as a custom repository.  The duplication check is a part of the data model.  You can throw anything you want from the repository.  All exceptions are propagated through the stack.  There is a HttpException that allows you to specify a status code.  So from within your repository, you can do something like:

```csharp
if (await CheckDuplicatedAsync(item))
{
    throw new HttpException(Strings.Validation_DuplicatedItem) { StatusCode = 500, Payload = item };
}
```

**Comment by asierpn** [comment]
But how can I implement a custom repository without rewriting the entire EntityTableRepository, the EntityTableRepository class is not extensible in this way:


  public class EntityTableRepositoryEx<TEntity> : EntityTableRepository<TEntity> where TEntity : class, ITableData
  {

    private Action<TEntity> ValidateItemAction { get; }
    public EntityTableRepositoryEx(DbContext context, Action<TEntity> validateItemAction = null) : base(context)
    {
      ValidateItemAction = validateItemAction;
    }

    public override async Task<TEntity> CreateAsync(TEntity item, CancellationToken token = default)
    {
      ValidateItemAction?.Invoke(item);
      return await base.CreateAsync(item, token);
    }

    public override async Task<TEntity> ReplaceAsync(TEntity item, byte[] version = null, CancellationToken token = default)
    {
      ValidateItemAction?.Invoke(item);
      return await base.ReplaceAsync(item, version, token);
    }
  }

**Comment by fileman** [comment]
You have to implement IRepository<TEntity> in your custom repository, I'm using internal repository inside MyEntityRepository : IRepository<TEntity>

**Comment by asierpn** [comment]
> You have to implement IRepository in your custom repository, I'm using internal repository inside MyEntityRepository : IRepository

Create a TableEntityRepository inside a custom implementation of IRepository and map all method calls? Yes, it's an option.

**Comment by asierpn** [comment]
Ok, I will do it that way. Thanks for pointing me in the right direction.
