### ISSUE TITLE
Allow ContractResolver override

### ISSUE THREAD

**Issue by fileman** [Azure/azure-mobile-apps#795]
**Is your feature request related to a problem? Please describe.**
I'm using Datasync inside a solution that conflict with CamelCasePropertyNamesContractResolver

**Describe the solution you'd like**
override ContractResolver on AddDatasyncControllers method

@adrianhall CamelCase is mandatory or your preference?

**Comment by adrianhall** [comment]
CamelCase is not necessary, but both sides need to agree on the format.  So if you make the change there, you also need to make the change on the client side.

Probably a good over-ride to do, and small effort.

**Comment by adrianhall** [comment]
Note that there are explicitly no integration tests that cover non-camelcase (default) contract resolvers.  If you want to validate that this is working long term, I suggest writing a few integration tests in the "kitchen sink" area and submitting as a PR.

**Comment by fileman** [comment]
I'm working on it, based on same server side changes

**Comment by fileman** [comment]
In client system properties are [hard coded](https://github.com/Azure/azure-mobile-apps/blob/ebef7a62183fac8df4e0b1ed1c42f1febcdcb607/sdk/dotnet/src/Microsoft.Datasync.Client/Serialization/SystemProperties.cs) as camel case ... @adrianhall any suggestion to solve this?
