### ISSUE TITLE
DefaultContractResolver broke client get item query

### ISSUE THREAD

**Issue by fileman** [Azure/azure-mobile-apps#800]
## Describe the bug
when using DefaultContractResolver in AddDatasyncControllers (#796), client query items broken, all integration tests fail.
Table GetAsyncItems and GetItemAsync return null or empty from sql statement, but Sqlite is case-insensitive so issue is somewhere but I not able to find where.

## To Reproduce
use services.AddDatasyncControllers(new DefaultContractResolver());

## Expected behavior
all test pass (after case-insensitive fixes)

## Additional
some integration tests can be solved changing comparison of hardcoded system and page properties to case-insensitive

**Comment by adrianhall** [comment]
This would be expected.  A lot of the tests basically do something like:

1. Set up test
2. Run test
3. Check that the JSON is correct.

You have changed the semantics of that JSON, so we would have to go through each and every one of the integration tests to ensure that the correct JSON is expected.

The question is - does your application work?  If not, write a few tests (it should not take more than a few tests) in the integration test suite for your specific requirements.

**Comment by fileman** [comment]
Ok, some tests fail for case sensitivity as expected without case-sensitive refactoring, but that's not my goal now.
I have create a #803 to test basic crud operation with DefualtContractResolver
