### ISSUE TITLE
Implement InvokeApiAsync method in DatasyncClient

### ISSUE THREAD

**Issue by asierpn** [Azure/azure-mobile-apps#808]
**Is your feature request related to a problem? Please describe.**
I am migrating from v4.2.0 and there is no InvokeApiAsync method available in the DatasyncClient class.

**Describe the solution you'd like**
Add InvokeApiAsync methods to the DatasyncClient class, similar to those in the old MobileServiceClient, to allow calling and retrieving data from custom API controllers (e.g. "api/SendMail").

**Describe alternatives you've considered**
The only alternatives I can see are to implement my own DatasyncClient or fork the current implementation and extend it. Maybe I am missing something.

**Comment by adrianhall** [comment]
I can certainly expose the `HttpClient` we use to send requests.  I think this would be the better option as you get to do anything you want there; the pipeline inside the HttpClient already sets up authentication and any custom pipeline providers you might have (like adding extra headers or logging).

**Comment by asierpn** [comment]
Yes, that is perfect for me, thank you.

**Comment by adrianhall** [comment]
Added SendAsync() to the DatasyncClient, which calls the underlying HttpClient.SendAsync() with the same parameters / signature.

Will be released in 6.0.5 release.
