### ISSUE TITLE
Use different naming convention on server side breaks client

### ISSUE THREAD

**Issue by fileman** [Azure/azure-mobile-apps#815]
## Describe the bug
As I feared seeing the failed tests (#800), changing the server-side a different ContractResolver with another naming convention breaks the client-side operation, so the Remote or Offline tables are empty. 

## To Reproduce
use services.AddDatasyncControllers(new DefaultContractResolver());

## Expected behavior
populate client side table with data sended from server, even if not in camelCase

## What platforms?
* Client:
  * Library versions 6.0.5

## Additional context
I have tried the CamelCasePropertyNames of DatasyncSerializerSettings but doesnt work for this issue.
I also found an error in Contract Resolver tests  #814

**Comment by adrianhall** [comment]
So, lets start with - based on this, I am going to back out the change that allows you to change the contract resolver.

I'd like to understand WHY you need to change the contract resolver?  

If it's to use the same stuff for non-DatasyncClient stuff, I'd suggest creating a different controller.  But it sounds like you are continuing to use the DatasyncClient.  The serializer is deeply embedded in the system here; any changes are likely to have ripple effects across the datasync protocol.

**Comment by fileman** [comment]
It's better to remove the server-side possibility to change the contract resolver. 

I use Datasync in conjunction with ABP.IO which uses PascalCase while Datasync uses CamelCase. The AddDatasyncControllers() method changes the serialization for the entire application. 

If is possible, it would be simplier and useful to have the ability to use the Datasync contract resolver only on controllers that depend on it and leave the serialization of the application unchanged... maybe in v8

**Comment by adrianhall** [comment]
ABP.IO uses the core Json serializer (in this case, camelcase throughout).  Unless you mean that you use the dynamic JSON client that comes along with ABP.

I'll research if I can change the serialization for just a single controller in ASP.NET Core.  I'm not sure I can - I believe serialization is global.

**Comment by fileman** [comment]
ABP has permission exposed by builtin controllers in PascalCase, but this is my specific case, in general it might be useful not to interfere with the serialization of other libraries used.

I have created an Attribute for TableController #822 , but need more work because some tests fail

**Comment by adrianhall** [comment]
I think it better to keep this in your own implementation.  I’ll look at what it takes to update the controllers for .NET8 (in the v8 branch) to support JSON encoding only for table controllers.

**Comment by adrianhall** [comment]
THis is a serious breaking change and I cannot admit it in the v6 branch.  I'm going to consider it very strongly for the v8 branch.
