### ISSUE TITLE
PurgeItemsAsync: When purging all items in a table, I would like to also reset all of the table's delta tokens

### ISSUE THREAD

**Issue by dylan-mills** [Azure/azure-mobile-apps#826]
**Is your feature request related to a problem? Please describe.**
`TimestampUpdatePolicy.UpdateToEpoch` has the following summary: 
> "Update the timestamp to the beginning of time, which will cause all records to be re-synchronized."
> "Only select this option if you purged all items in the table."

Originally, I thought this would reset all deltas to epoch time, because we are purging all items in the table that.
I see now that that only the delta for the query ID specified in `PurgeOption.QueryId` or the default query are reset.

**Describe the solution you'd like**
I'm not sure what the best approach is, but I've included a few ideas below:

1. `PurgeOption.UpdateToEpoch` would reset all of the deltas to the epoch time for the given table, possibly by adding a new method called`ResetAllTokens()` to the `IDeltaTokenStore`. 

1. To avoid a breaking change for anyone currently using `UpdateToEpoch`, an alternative solution might be to add a new method called `ResetTable()` to `IReadOnlyOfflineTable` that would purge all items from the table and reset all the tokens.

1. Add a new option to `PurgeOptions` to reset all tokens or alternatively add another `TimestampUpdatePolicy` enumerator to reset all tokens.

I would be happy to help code something up if you provide some guidance on how you think resetting a table should work.

**Describe alternatives you've considered**
I've tried to find a way to get all of the delta tokens for a given table, but the IDeltaTokenStore only has get, set and reset for a given table/queryId combination. 

**Additional context**
Relevant code:
![image](https://github.com/Azure/azure-mobile-apps/assets/33838865/93de1716-89be-4929-b4b1-b2bb6e7dba6e)

![image](https://github.com/Azure/azure-mobile-apps/assets/33838865/658f24f4-edaa-4ffc-a204-2f34e02a354e)
![image](https://github.com/Azure/azure-mobile-apps/assets/33838865/0db754b4-ca84-4dae-a138-2420ae7ec116)

**Comment by adrianhall** [comment]
How about PurgeOptions.ResetAssociatedQueries (default: false, set to true), which resets all the delta tokens for a specific table per the PurgeOptions.TimestampUpdatePolicy?

I think this would be a non-breaking change I could get in for 6.0.6.  Obviously, I’m willing to take a PR, but that’s not a lot of code, so I can get it in pretty easily.

**Comment by dylan-mills** [comment]
PurgeOptions.ResetAssociatedQueries sounds like a good solution for me, thanks!
