### ISSUE TITLE
ResolveConflict: guidance and/or feature for using the local item

### ISSUE THREAD

**Issue by dylan-mills** [Azure/azure-mobile-apps#827]
**Is your feature request related to a problem? Please describe.**
Not sure if this is a feature or a bug or just a call for guidance...

When resolving conflicts, we have these three options:

- `CancelAndDiscardItemAsync()`: Cancels the table operation and discards the local instance of the item.
- `CancelAndUpdateItemAsync(item)`: Cancels the table operation and updates the local instance of the item with the given item.
- `UpdateOperationAsync(item)`: Updates the table operation and updates the local instance of the item with the given item. Clears the error and sets the operation state to pending.

If I want to keep the server item, then `CancelAndUpdateItemAsync(error.Result)` seems to be my best option (as long as the item is not null).

If I want to keep the local item, then I thought I should use `UpdateOperationAsync(error.Item)`, but this just causes another `PushFailedException` because the error.Item's version hasn't changed to match the server version.

Should I be manually updating the version of the local item to the server? 

**Describe the solution you'd like**
Update to the documentation for [Synchronize an Offline Table](https://learn.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/howto/client/dotnet#synchronize-an-offline-table) with an example of best practices for keeping the local item.

![image](https://github.com/Azure/azure-mobile-apps/assets/6576706/3b82ff59-b5c3-4033-9bbd-a2cda54e7c22)

Then it would be handy for `CancelAndUpdateItemAsync()` and/or `UpdateOperationAsync()` to set the version on the item passed in.

**Describe alternatives you've considered**
Manually setting the version to the `error.Result.Version` prior to calling `UpdateOperationAsync()`.

**Additional context**

**Comment by adrianhall** [comment]
@amertlich is right - you need to copy the Version from the server copy of the entity to the client copy of the entity.  Once you do that, the push will succeed.

I never liked the naming for the conflict resolution stuff, and I think we should have strategies which just auto-do it.  I like the proposed extension method and can easily add that to 6.0.6 if it makes it easier for you.

**Comment by dylan-mills** [comment]
Thanks @adrianhall  and @amertlich for confirming we are handling this correctly by copying the version from the error.Result to the error.Item prior to calling `UpdateOperationAsync()`. And adding in some extensions would be great!

**Comment by adrianhall** [comment]
Have added an optional parameter to UpdateOperationAsync(), so you will call `error.UpdateOperationAsync(item, true);` to update the version.  The existing version behavior does not change.
