### ISSUE TITLE
Password Protection for offline SQLite database

### ISSUE THREAD

**Issue by CaseNewmark** [Azure/azure-mobile-apps#838]
# Description
The offline database can contain sensible data and as a minimal precaution we would like to protect the database with a passsword.

# Request
We establishing the connection to the SQLite database we want to use a password.

# Alternative
Encrypt the data within the database: we already thought about adding a custom JSON serializer to encrypt/decrypt the data.

**Comment by adrianhall** [comment]
The appropriate thing to do here would be to use Sqlite SEE (the official encryption tech) or SqliteCipher (which I see more normally here).  You would create a copy of the OfflineSQLiteStore with your updated code to initialize.  While I haven't done it myself, I am aware of others who have take this path.

I have no experience here, but I'm happy to take suggestions on how to improve OfflineSQLiteStore such that it can be inherited to support encryption.

**Comment by adrianhall** [comment]
Thought of a way to do this - simply allow the passing in of a SqliteConnection and use that.  It may even fix other issues around shared Sqlite databases.

TODO:
* Constructor on OfflineSqliteStore that takes a SqliteConnection

**Comment by CaseNewmark** [comment]
Forgot to say thank you for the implementation.
Thank you. :)
