### ISSUE TITLE
DatasyncClient.Serializer.Deserialize fails due to null values

### ISSUE THREAD

**Issue by georg138** [Azure/azure-mobile-apps#844]
## Describe the bug

Using `DatasyncClient.Serializer.Deserialize()` fails if the offline Table was not used before. The JSON Serializer throw an exception about null values: `{"Error converting value {null} to type 'System.Boolean'. Path 'deleted'."}`

## To Reproduce
- Do NOT use `DatasyncClient.GetOfflineTable()`
- Use an SQL query to directly query the offline storage
- Use `DatasyncClient.Serializer.Deserialize()` to convert the `jObject` to the target type.

## Expected behavior

The Serializer should handle null value from the database (i.e. convert `null` to `false` for the `deleted` property).

## What platforms?

* Server: offline

* Client:
  * .NET 12
  * WinUI 3
  * Datasync 6.0.5

## Additional context
Before using `DatasyncClient.GetOfflineTable()`, the `NullHandlingConverter` is not assigned to the value type properties:
![image](https://github.com/Azure/azure-mobile-apps/assets/53263304/edc913bc-25d0-4deb-b6b2-e4d98ed447b3)
After using `DatasyncClient.GetOfflineTable()`, the converters are correctly set:
![image](https://github.com/Azure/azure-mobile-apps/assets/53263304/7cf63abe-8cd3-4be5-b050-1cb0c920b897)

**Comment by adrianhall** [comment]
So the workaround is to use DatasyncClient.GetOfflineTable() before running SQL?

**Comment by georg138** [comment]
Using `DatasyncClient.GetOfflineTable()` once to initialize is the current workaround. 

 `DefineTable()` does not help. I guess this is due to using new settings for each invocation. So the `ContractResolver` configures all properties correctly but is then discarded.
```cs
	public static void DefineTable<T>(this IOfflineStore store)
	{
		store.DefineTable<T>(new DatasyncSerializerSettings());
	}
```

**Comment by adrianhall** [comment]
Not a lot I can do here (without a mountain of breaking changes).

I suggest you use, instead

```csharp
store.DefineTable<T>(client.Serializer.SerializerSettings);
```
