### ISSUE TITLE
Source link support

### ISSUE THREAD

**Issue by hansmbakker** [Azure/azure-mobile-apps#845]
**Is your feature request related to a problem? Please describe.**
While debugging, even though Visual Studio added decompilation support, it seems Visual Studio does not want to step into the internals of the DataSync libraries.

**Describe the solution you'd like**
Support for https://github.com/dotnet/sourcelink so that Visual Studio automatically can find and debug the source code of the DataSync libraries

**Describe alternatives you've considered**
Using https://github.com/RicoSuter/DNT with `switch-to-projects` to manually include the source code to step through the code.

**Additional context**

**Comment by adrianhall** [comment]
I have not used sourcelink, but the instructions seem pretty straight forward.  Will try and get this in for the next milestone.

**Comment by hansmbakker** [comment]
Wow, that’s fast! Great, thank you!
