### ISSUE TITLE
Enums are always stored as strings in sqlite / how to allow enums being stored as integer in sqlite?

### ISSUE THREAD

**Issue by hansmbakker** [Azure/azure-mobile-apps#846]
I'm trying to have the `Microsoft.Datasync.Client.SQLiteStore` package store `enum` values as `INTEGER` instead of `TEXT` in the sqlite database. The reason for this is that I want to be able to do raw SQL queries based on those integer values instead of based on string types.

The issue is that I can't find how to make the library do that.

In `public virtual void DefineTable<T>(string tableName, DatasyncSerializerSettings settings)`, the library serializes a default ("prototype") object to JSON and deserializes it back to base its types on:

https://github.com/Azure/azure-mobile-apps/blob/878d25e9085e045a5bfccb185384469e51070f56/sdk/dotnet/src/Microsoft.Datasync.Client/Offline/AbstractOfflineStore.cs#L143-L145

In that conversion, the enum values are converted to strings even when I pass a modified `DatasyncSerializerSettings` object having the `StringEnumConverter` removed.

The default `DatasyncSerializerSettings` has a `StringEnumConverter` added:
https://github.com/Azure/azure-mobile-apps/blob/878d25e9085e045a5bfccb185384469e51070f56/sdk/dotnet/src/Microsoft.Datasync.Client/Serialization/DatasyncSerializerSettings.cs#L28

I tried to use a `DatasyncSerializerSettings` **without** a `StringEnumConverter` using the following code:
```charp
private static void DefineTables(IOfflineStore store)
{
    var settings = new DatasyncSerializerSettings();
    var converter = settings.Converters.FirstOrDefault(c => c is StringEnumConverter);
    if (converter is not null)
    {
        settings.Converters.Remove(converter);
    }

    store.DefineTable<Inspection>(settings);
}
```

When debugging, the correct `settings` object is being used, having only the `DatasyncIsoDateTimeConverter` and the `StringEnumConverter` is correctly removed, but enums are still converted to strings. Do you see what I'm missing?

**Comment by adrianhall** [comment]
This is not an easily fixed thing; mostly because the conversion is embedded in the convert to SQL methods rather than the DatasyncSerializerSettings.  I won't be able to do anything about this in the v6 version of the service, so equality is the ONLY operation allowed against enums.

In the v8 version, we'll be switching over to Entity Framework Core and what you want will be possible.

Sorry I don't have better news, other than "wait for May"

**Comment by hansmbakker** [comment]
Thank you for the explanation!
