### ISSUE TITLE
ASP.NET Core: TableController.PrepareItemForStore should offer an Async alternative

### ISSUE THREAD

**Issue by cjaliaga** [Azure/azure-mobile-apps#85]
**Is your feature request related to a problem? Please describe.**
When trying to prepare an item there's no option for performing async operations without blocking.

**Describe the solution you'd like**
```csharp
Task<TEntity> PrepareItemForStoreAsync(TEntity item);
```

**Comment by adrianhall** [comment]
Implemented in a470a36
