### ISSUE TITLE
PreconditionFailed deleting item in Xamarin.iOS

### ISSUE THREAD

**Issue by asierpn** [Azure/azure-mobile-apps#857]
## Describe the bug

The call to DeleteItemAsync returns PreconditionFailed when it is done in Xamarin.iOS, but it works fine in other platforms (Xamarin.Android and WinAppSDK). If I inspect the request headers on the server side I see these two headers which should not be there: "If-Modified-Since" and "If-None-Match" in addition to the correct header "If-Match", but I didn't see where are populated these wrong headers.

## To Reproduce

1. Try to delete an item of a RemoteTable from a Xamarin.iOS client

## Expected behavior

The item must be deleted from database

## What platforms?

Xamarin.iOS

* Server:
  * Version of dotnet being used to compile? Tested with net7 and net8
  * Library versions? Microsoft.AspNetCore.Datasync.EFCore 6.0.7
  * What database are you using? SQL Server
  * Where are you running the server? Azure App Service linux container

* Client:
  * Version of dotnet being used to compile? Tested with net7 and net8
  * .NET Runtime Environment (WPF, UWP, Xamarin.Forms, etc.): Xamarin.iOS
  * Library versions? Microsoft.Datasync.Client 6.0.7
  * What platform versions are you running on? WAPPSDK, Xamarin.Android and Xamarin.iOS
  * Does it happen in an emulator / simulator, or only on a real device? both

**Comment by adrianhall** [comment]
This must be something you are doing.  There is no difference in the code paths for Xamarin.iOS and any other platform, so the thing we send would be the same in all cases.  I'd start by adding some logging into the client side - you can find an example logging provider int he docs.

**Comment by asierpn** [comment]
Yes, I think so too, but after hours of research I couldn't find where the wrong headers were added. This is what I log on the client side using your LoggingHandler:

```
[0:] [HTTP] >>> DELETE https://xxx.azurewebsites.net/tables/xxx/C54FD1D2-C947-4772-9E1E-D622AAB5A553
[0:] [HTTP] >>> If-Match: "AAAAAAHJbZI="
[0:] [HTTP] >>> ZUMO-API-VERSION: 3.0.0
[0:] [HTTP] >>> User-Agent: Datasync/6.0.0.0
[0:] [HTTP] >>> User-Agent: (lang=Managed;os=Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:17:35 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8112/Unix 17.2.0;arch=X64;version=6.0.0.0;test)
[0:] [HTTP] >>> X-ZUMO-VERSION: Datasync/6.0.0.0 (lang=Managed;os=Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:17:35 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8112/Unix 17.2.0;arch=X64;version=6.0.0.0;test)
[0:] [HTTP] <<< PreconditionFailed Precondition Failed
[0:] [HTTP] <<< Server: Kestrel
[0:] [HTTP] <<< request-context: appId=cid-v1:306b5d65-39ea-47c6-9be1-cd3545152225
[0:] [HTTP] <<< Strict-Transport-Security: max-age=31536000; includeSubDomains
[0:] [HTTP] <<< Date: Wed, 03 Jan 2024 09:40:24 GMT
[0:] [HTTP] <<< ETag: "AAAAAAHJbZI="
[0:] [HTTP] <<< Set-Cookie: ARRAffinity=5cf27fc3d7c8550414fe859873ccd12aeaf17c968ff7abb8453b8c3c80f6d58d; Path=/; Domain=.xxx.azurewebsites.net; Version=0; Discard; Secure; httponly
[0:] [HTTP] <<< Set-Cookie: ARRAffinitySameSite=5cf27fc3d7c8550414fe859873ccd12aeaf17c968ff7abb8453b8c3c80f6d58d; Path=/; Domain=.xxx.azurewebsites.net; Version=0; Discard; Secure; httponly
[0:] [HTTP] <<< Content-Type: application/json; charset=utf-8
[0:] [HTTP] <<< request-context: appId=cid-v1:306b5d65-39ea-47c6-9be1-cd3545152225
[0:] [HTTP] <<< Last-Modified: Wed, 03 Jan 2024 09:36:41 GMT
[0:] [HTTP] <<< Strict-Transport-Security: max-age=31536000; includeSubDomains
[0:] [HTTP] <<< Content-Length: 330
[0:] [HTTP] <<< {"id":"C54FD1D2-C947-4772-9E1E-D622AAB5A553","updatedAt":"2024-01-03T09:36:41.8286906+00:00","version":"AAAAAAHJbZI=","deleted":false}
```

And these are the request headers logged on the server side using a custom middleware:

```
Accept: */*
Host: xxx.azurewebsites.net
User-Agent: Datasync/6.0.0.0 (lang=Managed;os=Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:17:35 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8112/Unix 17.2.0;arch=X64;version=6.0.0.0;test)
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: ARRAffinity=5cf27fc3d7c8550414fe859873ccd12aeaf17c968ff7abb8453b8c3c80f6d58d; ARRAffinitySameSite=5cf27fc3d7c8550414fe859873ccd12aeaf17c968ff7abb8453b8c3c80f6d58d
If-Match: "AAAAAAHJbZI="
If-Modified-Since: Wed, 03 Jan 2024 09:36:41 GMT
If-None-Match: "AAAAAAHJbZI="
Max-Forwards: 10
traceparent: 00-b40440d6cdb07e511a112ac3575c81aa-979139e5543540d8-00
Content-Length: 0
zumo-api-version: 3.0.0
x-zumo-version: Datasync/6.0.0.0 (lang=Managed;os=Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:17:35 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8112/Unix 17.2.0;arch=X64;version=6.0.0.0;test)
X-ARR-LOG-ID: aaf00fe0-fc2a-4c47-b5be-c6f4ea14788d
CLIENT-IP: x.x.x.x:63460
X-Client-IP: x.x.x.x
DISGUISED-HOST: xxx.azurewebsites.net
X-SITE-DEPLOYMENT-ID: xxx
WAS-DEFAULT-HOSTNAME: xxx.azurewebsites.net
X-AppService-Proto: https
X-ARR-SSL: 2048|256|CN=Microsoft Azure TLS Issuing CA 01, O=Microsoft Corporation, C=US|CN=*.azurewebsites.net, O=Microsoft Corporation, L=Redmond, S=WA, C=US
X-Forwarded-TlsVersion: 1.2
X-Original-Proto: http
X-Original-URL: /tables/xxx/C54FD1D2-C947-4772-9E1E-D622AAB5A553
X-WAWS-Unencoded-URL: /tables/xxx/C54FD1D2-C947-4772-9E1E-D622AAB5A553
X-Client-Port: 63460
X-Original-For: [::ffff:169.254.130.10]:48066
```

If I construct the call to the endpoint manually I get the same result, but I've noticed that the If-Modified-Since and If-None-Match headers are only added if I call a tablecontroller endpoint, if the endpoint does not exist or is an api controller these headers are not added.

        var client = new HttpClient();
        var request = new HttpRequestMessage(HttpMethod.Delete, "https://xxx.azurewebsites.net/tables/xxx/1EA6DCB2-D0A5-404B-A048-8F4274564BD9");
        request.Headers.Add("If-Match", ToETagValue(Item.Version));
        request.Headers.Add("ZUMO-API-VERSION", "3.0.0");
        var response = await client.SendAsync(request);

I'm also trying to reproduce the problem using the TodoApp sample, but have had no luck.

**Comment by adrianhall** [comment]
The fact that you call the endpoint manually and get the same result is weird and indicates that it isn't Azure Mobile Apps that is causing it.

Can you sniff the wire with a web debugging proxy like charles (on the emulator)?

**Comment by asierpn** [comment]
I've used Proxyman to sniff the wire and I can see the headers added in the requests on the client side, analysing the request sequence and considering [this post](https://social.msdn.microsoft.com/Forums/security/en-US/ee3d936c-672e-4a26-a644-40edec5f324d/ifnonematch-not-working-on-ios?forum=xamarinforms) I determined that the issue was caused by IOS caching. The incorrect headers were from previous requests that were cached by iOS. I disabled IOS caching by injecting this handler into the client HttpPipeline and now it works fine:

        var sessionHandler = new NSUrlSessionHandler
        {
          DisableCaching = true
        };

Thanks for your help @adrianhall

**Comment by adrianhall** [comment]
I’m going to add an issue to the v8 backlog to add cache hint headings to indicate that caching is not appropriate on this service.  That may not help your case, but it can’t hurt.  (FWIW, iOS is doing caching wrong if they are caching random headers from other calls, but that’s another story).
