### ISSUE TITLE
Using a custom sqlite connection fails

### ISSUE THREAD

**Issue by georg138** [Azure/azure-mobile-apps#858]
## Describe the bug

Using a custom sqlite connection fails.

## To Reproduce

- Create a sqlite connection using `SQLitePCL.raw.sqlite3_open()` and pass it to the `SqliteConnection` constructor
- try to sync the database.

This fails in  `BatchInsert()`  with an `InvalidOperationException`, probably because `DbConnection.MaxParametersPerQuery` is not initialized in the `SqliteConnection` constructor for custom connections.
https://github.com/Azure/azure-mobile-apps/blob/bd2d79b0c0f4a96d0fe9d75015b30402cfdba8b9/sdk/dotnet/src/Microsoft.Datasync.Client.SQLiteStore/Driver/SqliteConnection.cs#L70

![image](https://github.com/Azure/azure-mobile-apps/assets/53263304/09b503a1-751d-4fb4-a209-0ab31efc47c6)

## What platforms?

Datasync 6.0.7

**Comment by adrianhall** [comment]
Great point - I'll get this into the 6.0.8 release.

**Comment by adrianhall** [comment]
Fixed in bc9691a

**Comment by georg138** [comment]
Looks good, thank you!
