### ISSUE TITLE
TableOperation deserialization fails on JObject Item field

### ISSUE THREAD

**Issue by acidindustries** [Azure/azure-mobile-apps#870]
## Describe the bug

When trying to execute pending table operations, if the "item" field of the __operations table contains a JObject, the deserialization fails with an InvalidCastException.

```
System.InvalidCastException: Cannot cast Newtonsoft.Json.Linq.JObject to Newtonsoft.Json.Linq.JToken.
   at Newtonsoft.Json.Linq.Extensions.Convert[T,U](T token)
   at Newtonsoft.Json.Linq.JToken.Value[T](Object key)
   at Microsoft.Datasync.Client.Offline.Queue.TableOperation.Deserialize(JObject obj)
   at Microsoft.Datasync.Client.Offline.Queue.OperationsQueue.PeekAsync(Int64 previousSequenceId, IEnumerable`1 tableNames, CancellationToken cancellationToken)
   at Microsoft.Datasync.Client.Offline.SyncContext.PushItemsAsync(String[] tableNames, PushOptions options, CancellationToken cancellationToken)
```

## To Reproduce

1. Create an item in an offline table.
2. Delete the item to create a delete operation in the __operations table.
3. Sync the data to the remote endpoint
4. The issue is triggered.

## Expected behavior

Data should be deserialized correctly into the JsonItem field.

## What platforms?

.net7
windows 10 x64
Offline db is LiteDB and remote DB is MongoDB

## Screenshots
![image](https://github.com/Azure/azure-mobile-apps/assets/112872354/c8bd6046-e0ff-4b99-bb7b-67d548b97b87)

![image](https://github.com/Azure/azure-mobile-apps/assets/112872354/22a87656-c07e-4882-8faa-2d8b344b5fd7)

**Comment by adrianhall** [comment]
We don't support synchronizing JSON objects.   The types we do support are listed in the documentation.  For this particular case, you want to transmit via a string and have a view model that transforms it into a JObject.

We are not going to be supporting JSON objects in the new service either.  There are complexities in transforming JSON inside JSON that will cause wierd edge cases.

**Comment by acidindustries** [comment]
That works for me. Thanks!
