### ISSUE TITLE
The In $filter option is not supported by DatasyncClient

### ISSUE THREAD

**Issue by asierpn** [Azure/azure-mobile-apps#877]
## Describe the bug

The In $filter option is not supported by DatasyncClient, although it was supported in v4.2.0, this exception is thrown if you try to do it:

System.NotSupportedException : 'value(System.Collections.Generic.List`1[System.String]).Contains(m.Id)' is not supported in a 'Where' clause

## To Reproduce

Run this test in the Linq.Test.cs scope:

```
  [Fact]
  public void Linq_Contains()
  {
    var ids = new List<string> { "foo", "bar" };
    ExecuteWhereQuery(
        m => ids.Contains(m.Id),
        "$filter=Id%20in%20%28%27foo%27%2C%27bar%27%29" // Id in ('foo','bar')
    );
  }
```

## Expected behavior

The OData filter is correctly generated and applied on the server side.

**Comment by adrianhall** [comment]
I just checked the v4.2.0 code and IN was NOT supported.

I'll add a test for the IN operator to the LINQ tests in v8; then I can see about coding contains in the OData expression visitor in the v8 code.

**Comment by asierpn** [comment]
Yes, I checked it too. I'm sure that it works in the old version because we're migrating a working code and that fails in the new version, but I haven't debugged it in the old version.

Fortunately, we don't use it very often, and I think that we can change that by creating an Or expression.

Thanks @adrianhall

**Comment by adrianhall** [comment]
You can certainly use it for string.Contains(string|char), but not string[].Contains(string) - that’s definitely not in there.  Having said that, you can use the IN operator with a direct OData query, so you may just be doing that.

**Comment by adrianhall** [comment]
I've added support for `IEnumerable<string>.Contains(string)` to the OData string creator and LINQ expression parser, which means it works on REMOTE TABLES.

Still to do - need to add the same thing to the OData string parser and SQL expression creator, for OFFLINE table support - IN does not work in offline tables with the code I've just checked in.

**Comment by adrianhall** [comment]
Have added issue for offline support of IN / Contains syntax.  Will close this one as remote tables now support it.
