### ISSUE TITLE
External visibility on DatasyncClient's ServiceHttpClient

### ISSUE THREAD

**Issue by acidindustries** [Azure/azure-mobile-apps#883]
Would it be possible to change the ServiceHttpClient from internal to public or have some sort of getter to retrieve the Http Context that was used in DatasyncClient? One use case I am seeing right now is when you hook into the SynchronizationProgress event.

It would be nice to have access to HttpClient or at least the HttpContext.Request of the sync request.

In the context I am using my extended implementation, it would be nice to retrieve query string parameters from the original to be sent back on a following request when the SynchronizationProgress SynchronizationEventType.ItemWasStored triggers.

**Comment by adrianhall** [comment]
The SyncContext doesn't have access to the query parameters used.  They are generated on the fly when the LINQ query is executed.   The SyncContext never sees anything about the HTTP request.

What are you actually trying to solve for here?

**Comment by acidindustries** [comment]
I would like be able to reuse Datasync Client's internal HttpClient to send a request on behalf of the client to an endpoint. 

Basically, I am in the process of wrapping a layer around Datasync for MongoDB and made an AbstractOfflineStore to enable storing files through GridFS. 

I can create a new HttpClient and point it to the endpoint I need to retrieve the actual files but it would be preferable if I could use the one configured for the client since it's got some HttpPipeline configuration that I need to have access to from within that wrapper.

For now, I am looking at passing down the HttpPipeline from DatasyncClientOptions to my custom AbstractOfflineStore.

**Comment by adrianhall** [comment]
Any reason why you can't use `DatasyncClient.SendAsync(HttpRequestMessage, CancellationToken)` for this purpose?

**Comment by adrianhall** [comment]
(To adjust that - yes, I'm working on making an underlying HttpClient be available, but the mechanism for re-use is already there)
