### ISSUE TITLE
Offline photo/file sync

### ISSUE THREAD

**Issue by KieranFleckney** [Azure/azure-mobile-apps#897]
I am looking to sync photos, however, files would possible be needed in the future (Multipart support for large files). I was wondering if you would ever support something like that. Storage location like Azure Blob and AWS S3 would be a good start too. Or even open to PR implementing said feature.  Current I have a app which allows you to take/pick photo to add to report. I would like to be able to sync the photos with the report data.

Maybe there already is a solution to this, would be happy to hear. In regards to adding a solution to this project I have no idea the best approach but would be open to ideas.

**Comment by adrianhall** [comment]
I believe this would be a different library - it's completely orthogonal to the problem of data table synchronization.

Fortunately, it's relatively easy to implement.  We can certainly have a discussion as to how to effect this (over in discussions), but it's not something I would take into this library.
