### ISSUE TITLE
Source code for Cordova plugin?

### ISSUE THREAD

**Issue by eswann** [Azure/azure-mobile-apps#901]
Hello, I was attempting to view the source for the Cordova plugin. The version as listed in NPM is 6 years old, meaning it probably has a number of security issues. However, the source and project links from NPM return 404s. Does the source for the Cordova project still exists somewhere?

**Comment by asierpn** [comment]
I think you can get it from here https://github.com/Azure/azure-mobile-apps/tree/archive

**Comment by adrianhall** [comment]
Correct - there is an archive branch to this repository, and all the old versions (pre v6 stuff) are there.

**Comment by eswann** [comment]
Thanks for the info!
