### ISSUE TITLE
PendingOperations returned value is not correct

### ISSUE THREAD

**Issue by Arslan007** [Azure/azure-mobile-apps#907]
## Describe the bug

When checking the `PendingOperations` for a table then it returns the wrong value

## To Reproduce

Have multiple table updates while you are offline. Kill the app then turn on internet and launch app. Push the changes to server and verify results

## Expected behavior

After successful push it should return correct `pendingOperations` count which is 0

## What platforms?

iOS/Windows with offline store

* Server:

1. .NET7
2. VS2022
3. 6.1.0

* Client:

1. .NET7
2. VS2022
3. 6.10
4. Azure K8S

## Additional context

I have added my additional logging in `OperationQueue.cs` to see if `pendingOperation` variable is set properly or not

```
InitializeAsync:: [PageCount]: 2 [PendingOperations]: 2

[12:59:30 INF] Syncing [report]: "PushStarted" Success: null Pulled: -1
EnqueueOperationAsync:: [PendingOperations - BeforeDecrement]: 2
EnqueueOperationAsync:: [PendingOperations - AfterDecrement]: 1
[12:59:32 INF] Syncing [report]: "PushFinished"

[12:59:32 INF] Syncing [userreport]: "PushStarted" Success: null Pulled: -1
EnqueueOperationAsync:: [PendingOperations - BeforeDecrement]: 2
EnqueueOperationAsync:: [PendingOperations - AfterDecrement]: 1
[12:59:33 INF] Syncing [userreport]: "PushFinished"
```
I had 2 items in operation queue which are correct in `InitializeAsync` method and when `report`is being pushed then in `EnqueueOperationAsync` method it had  count of 2 `pendingOperations` for which are so far good and after decrement with this 

` Interlocked.Decrement(ref pendingOperations);`

it shows the correct count to 1. Still so far all good and happy at this point

Now second table `userreport` start pushing data to server and it shows in `EnqueueOperationAsync` method `pendingOperation` as 2 which should be 1.

So here is the problem now rather than 1 its using 2 and decrement value so you will always get wrong result.

**Comment by adrianhall** [comment]
Thanks for the report.  I'll see if it's an easy fix.  If not, I'll defer it to 6.1.2, but I'm going to be releasing 6.1.1 this afternoon, so I'll take a look this morning.

**Comment by adrianhall** [comment]
I've added the following test to ensure PendingOperations is updated properly:

```csharp
    [Fact]
    public async Task KS7_EndToEndSyncTest()
    {
        const int insertedItems = 5;

        await InitializeAsync();

        Assert.Equal(0, client.PendingOperations);

        // Add a couple of new items, and ensure pending operations are updated.
        for (int i = 0; i < insertedItems; i++)
        {
            var insertion = new KitchenSinkDto { StringValue = $"Item {i}" };
            await offlineTable!.InsertItemAsync(insertion);
            Assert.Equal(i + 1, client.PendingOperations);
        }

        await offlineTable!.PushItemsAsync();
        await offlineTable!.PullItemsAsync();

        Assert.Equal(0, client.PendingOperations);
        var nItems = await offlineTable!.CountItemsAsync();
        Assert.Equal(insertedItems, nItems);
    }
```

This test passes, so basics of pending operations works.  I'm wondering if it's a multi-table issue (so that's my next task - to add a new test for multiple tables).

In the interim, if you have an integration test that demonstrates the failure you experience, that would be immensely helpful.

**Comment by adrianhall** [comment]
... and the equivalent multi-table version:

```csharp
    [Fact]
    public async Task KS7_EndToEndSyncTest()
    {
        const int insertedItems = 5;

        await InitializeAsync(true);

        Assert.Equal(0, client.PendingOperations);

        // Add a couple of new items, and ensure pending operations are updated.
        for (int i = 0; i < insertedItems; i++)
        {
            var insertion = new KitchenSinkDto { StringValue = $"Item {i}" };
            await offlineTable!.InsertItemAsync(insertion);
            Assert.Equal(i + 1, client.PendingOperations);
        }

        // Also add a movie, in case there is a multi-table issue
        var movie = GetSampleMovie<ClientMovie>();
        await offlineMovieTable!.InsertItemAsync(movie);
        Assert.Equal(insertedItems + 1, client.PendingOperations);

        await offlineTable!.PushItemsAsync();
        Assert.Equal(1, client.PendingOperations);
        await offlineTable!.PullItemsAsync();
        Assert.Equal(1, client.PendingOperations);

        await offlineMovieTable!.PushItemsAsync();
        Assert.Equal(0, client.PendingOperations);
        await offlineMovieTable!.PullItemsAsync();
        Assert.Equal(0, client.PendingOperations);

        Assert.Equal(0, client.PendingOperations);
        var nItems = await offlineTable!.CountItemsAsync();
        Assert.Equal(insertedItems, nItems);
    }
```

... also works.  Thus I need a test that shows the problem off before I can proceed.

**Comment by Arslan007** [comment]
Thanks @adrianhall for checking. Sure I will try with integration test.
