### ISSUE TITLE
Should `TEntity entity` be marked nullable?

### ISSUE THREAD

**Issue by hansmbakker** [Azure/azure-mobile-apps#909]
`TEntity entity` in 
https://github.com/Azure/azure-mobile-apps/blob/102c88bdb49111e4668356b86273ddece12be888/sdk/dotnet/src/Microsoft.AspNetCore.Datasync.Abstractions/Interfaces/IAccessControlProvider.cs#L39

is currently not marked nullable. This looks like it assumes it is always called in the context of a specific entity.

However, we would like to call it outside the context of a specific entity: when running a query on a table. In this case, the entity is unknown and therefore null.

Could this be marked nullable?

Cc @desjoerd

**Comment by desjoerd** [comment]
I assume it will be fixed in v8, as Nullable Reference Types is not enabled in v6, and is enabled for v8

**Comment by adrianhall** [comment]
Correct - current code base does not have nullable reference types enabled.  We'll fix that in v8.
