### ISSUE TITLE
Possibility to mock HttpClient

### ISSUE THREAD

**Issue by hansmbakker** [Azure/azure-mobile-apps#913]
**Is your feature request related to a problem? Please describe.**
We would like to build in-memory integration tests. For this we would like to provide our own HttpClient to the DataSync client library, for example to provide mocked authentication functionality.

I saw in #887 the HttpClient was exposed, but it cannot be set.

**Describe the solution you'd like**
Being able to set HttpClient for the DataSync client library

**Describe alternatives you've considered**

**Additional context**

**Comment by adrianhall** [comment]
You don't need to set the HttpClient for unit tests.  

For faking, create a FakeDelegatingHandler and push that into the config for the client - we do this ourselves in our tests - see https://github.com/Azure/azure-mobile-apps/blob/main/sdk/dotnet/test/Datasync.Common.Test/Mocks/MockDelegatingHandler.cs

You could, as an alternative, provide a mocked HttpClientHandler instead (as the last item in the pipeline)

For mocking, mock the IRemoteTable or IOfflineTable instead.  You can then inject that and bypass testing at a HTTP layer.

I don't think it's a good idea to replace the HttpClient as it requires a relatively specific setup for client/server commuication.  We've provided the facilities to inject into the pipeline at the proper point.

I'm going to mark this as resolved, so it will auto-close 7 days after the final comment.

**Comment by asmolarczyk** [comment]
I think this is related, therefore I'm commenting here: I would like to use Microsoft.AspNetCore.Mvc.Testing package in integration tests. Ist it possible to use the HttpClient created from WebApplicationFactory<TEntryPoint>.CreateClient() with DatasyncClient?
Thank you!

**Comment by adrianhall** [comment]
We do that ourselves in our test projects.  Take a look at the Integration tests to see how we set it up.
